### ISSUE TITLE
Trodden Dirt maintains momentum in direction you were moving

### ISSUE THREAD

**Issue by keyangel** [williewillus/Botania#103]
Entering a patch of Trodden Dirt maintains your momentum in whatever direction you were going when you entered, making you zoom off in whatever direction you were going whether you're currently moving that way or not.

**Comment by keyangel** [comment]
Ah, I see this was reported already, looks like I jumped the gun:

https://github.com/williewillus/Botania/issues/68

Seems to be an issue still, though in the version that's on FTB Unstable 3.0.19:  Botania.r1.8-248-MC1.8-779cc76

**Comment by williewillus** [comment]
solved in next build
