### ISSUE TITLE
Missing/Broken texture. (Purple and Black blocks)

### ISSUE THREAD

**Issue by edddyeee** [williewillus/Botania#104]
I have Botania installed in my modpack folder for 1.7.10 and when I go ingame, there are these purple and black blocks. So does anyone know how to fix it. Also there are some items with the name "tile.botania.flower" instead of "flower". So can anyone help me fix my 2 issues?

**Comment by howtonotwin** [comment]
This repo is for 1.8, not 1.7. 1.7 is maintained by Vazkii and williewillus is only in charge of 1.8. Use the 1.7 version and report issues to [Vazkii/Botania](https://github.com/Vazkii/Botania).

**Comment by edddyeee** [comment]
I already asked him and he said go to github and now your saying ask him. Is there someone else who know how to fix this problem?

Sent from my iPhone

On Feb 6, 2016, at 4:21 PM, howtonotwin <notifications@github.com<mailto:notifications@github.com>> wrote:

This repo is for 1.8, not 1.7. 1.7 is maintained by Vazkii and williewillus is only in charge of 1.8. Use the 1.7 version and report issues to Vazkii/Botania.

##

**Comment by howtonotwin** [comment]
Yes, go to HIS repoisitory. Put an issue on [Vazkii/Botania](http://github.com/Vazkii/Botania/issues/new), and close this one, because 1.7 problems don't belong here. Vazkii wants issues there so they can found and tracked without sifting through whatever you were using before.

**Comment by yrsegal** [comment]
- [Vazkii/Botania](github.com/Vazkii/Botania/issues/new)

**Comment by howtonotwin** [comment]
@yrsegal Oh GitHub, what would we do without out you? :stuck_out_tongue_closed_eyes:

**Comment by yrsegal** [comment]
actually that's markdown

**Comment by howtonotwin** [comment]
Let's just blame relative links and be done with it.
