### ISSUE TITLE
[1.8.9] Lexica botania rendering crash

### ISSUE THREAD

**Issue by iarspider** [williewillus/Botania#105]
Botania version: Botania.r1.8-248-MC1.8-d0e4e43.jar
Forge 1724

Got a crash while browsing through Lexica Botania: http://pastebin.com/A4sv3W2y

**Comment by howtonotwin** [comment]
Please use the latest Botania, I believe it has fixed this problem already. The latest version disables the problematic portion of code (Thaumcraft integration) and the next build should fix it.

**Comment by williewillus** [comment]
yup, it's fully fixed in the next build, thanks for the patience! ^
