### ISSUE TITLE
Server startup crash with latest version

### ISSUE THREAD

**Issue by SeriousCreeper** [williewillus/Botania#107]
Crash Log: http://pastebin.com/UunDksUL 

Is it due to botania or another mod?

**Comment by yrsegal** [comment]
that's botania's fault.

**Comment by yrsegal** [comment]
uh... version? o.o

**Comment by GirafiStudios** [comment]
Botania.r1.8-248-MC1.8-0f41f1f.jar, it says that in the crashlog if you look.

**Comment by yrsegal** [comment]
oh right, i'm a derp >.<

**Comment by yrsegal** [comment]
huh, it appears to not like the Minecraft.getMinecraft().thePlayer? maybe?

**Comment by williewillus** [comment]
goddammit. yeah, bad call in the API, didn't even notice that it was in common code

hotfix coming

**Comment by williewillus** [comment]
wait what this is strange, it's crashing on the wiki integration for the lexicon

**Comment by yrsegal** [comment]
yeah, the wiki class uses Minecraft.getMinecraft().thePlayer

**Comment by williewillus** [comment]
yeah found it - was in common code even though that specific method only gets called clientside

**Comment by williewillus** [comment]
5128847

**Comment by SeriousCreeper** [comment]
Awesome, thanks a lot guys :D

**Comment by williewillus** [comment]
new build out
