### ISSUE TITLE
Platform crash with the Chisel Mod

### ISSUE THREAD

**Issue by Darkhax** [williewillus/Botania#108]
When applying a chisel block to a platform from Botania, a pretty bad crash takes place. This crash also re-occurs every time the world is loaded up again. Not certain which mod would be responsible for fixing this issue, so I am reporting it to both. The crash log can be seen [here](https://gist.github.com/darkhax/9c4389ffe6134f209834) The Chisel version of this report can be seen [here](https://github.com/Chisel-Team/Chisel/issues/124)

**Comment by williewillus** [comment]
Should no longer crash, but still doesn't look fully right (see the other platform issue)
