### ISSUE TITLE
Pylons render incorrectly

### ISSUE THREAD

**Issue by williewillus** [williewillus/Botania#11]
Item model: needs some groups disabled
World TESR: awaiting OBJ fixes

**Comment by yrsegal** [comment]
you can just do a checklist, willie, and not spam those of us watching

```
- [ ] thing
- [x] second thing
```

becomes
- [ ] thing
- [x] second thing

and clicking on a box will check it off.

**Comment by williewillus** [comment]
I'm just making the initial batch of tickets, sorry for the spam. A checklist really isn't how an issue tracker should be used :p

**Comment by yrsegal** [comment]
it works very well for this purpose, though

**Comment by williewillus** [comment]
85102de
