### ISSUE TITLE
Platforms don't take other state data into account. 

### ISSUE THREAD

**Issue by Darkhax** [williewillus/Botania#110]
Several blocks have special state information which does not get taken into consideration. This is a pretty difficult issue to solve, as there are too many cases to have 100% coverage, however I might have a possible solution. The idea I have would be to take advantage of Block#onBlockPlaced which returns an IBlockState. You can take the arguments passed to the activation method where the state is applied, and cast that to the onBlockedPlaced method. I have made some changes to my code that is based off of the render primer case study, and that seems to fix many of these issues. The onBlockPlaced method seems relatively safe to use in this situation, however it is conceivable that some mod might do something in this method which might cause some issues. 

![2016-02-08_23 09 58](https://cloud.githubusercontent.com/assets/2250798/12908996/a42f6408-ceb9-11e5-8017-b1dfe432d701.png)

**Comment by williewillus** [comment]
Huh, I really shouldn't even be allowing partial blocks like that to be mimicked (iirc they werent allowed in 1.7)
