### ISSUE TITLE
Managlass uncraftable

### ISSUE THREAD

**Issue by KaseiFR** [williewillus/Botania#111]
Hello,

Using Botania 248 (779cc76), I can't make managlass by tossing glass into a manapool. Other mana infusion such as the manasteel still work though. Having a piece of glass in hand add the correct overlay, but nothing happen when I drop it. [Screenshots](http://imgur.com/a/7wO5p)

**Comment by MrGraphic** [comment]
Do you have Intangible installed by any chance ? If so, you will need to turn off "B:ReplaceDroppedGlass" in Intangible config.

**Comment by KaseiFR** [comment]
Of course, cross mod interaction... I'll try to signal it to the FTB Unstable devs. Thank you.

**Comment by MrGraphic** [comment]
No problem and if you ever want to use Blow Mold from Intangible that requires this "converted dropped glass" after turning it off just use dropper and it will spit out this one despite configs.

**Comment by williewillus** [comment]
Ah good to hear it got resolved
