### ISSUE TITLE
gradle build error

### ISSUE THREAD

**Issue by kotoroshinoto** [williewillus/Botania#112]
- What went wrong:
  A problem occurred configuring root project 'Botania'.
  > Failed to notify project evaluation listener.
  > org.gradle.api.artifacts.ResolvedArtifact.getId()Lorg/gradle/api/artifacts/component/ComponentArtifactIdentifier;

**Comment by kotoroshinoto** [comment]
if I use the included wrapper, I get this error instead:
- What went wrong:
  Task 'curse' is ambiguous in root project 'Botania'. Candidates are: 'curseforge', 'curseforge225643'.

**Comment by williewillus** [comment]
for the first problem - your system gradle is probably outdated

for the second one, I can't reproduce, it builds fine for me: http://pastebin.com/tPf7uYbJ

make sure you're on the MC18 branch, not master (that's the 1.7 branch)

**Comment by kotoroshinoto** [comment]
doing a version check I am one version old so that is probably true. I'll try to figure out the second thing, but I have the correct branch pulled

**Comment by williewillus** [comment]
I just built another release successfully (with system Gradle) - are you still having a problem?
