### ISSUE TITLE
No Mana Glass

### ISSUE THREAD

**Issue by Unatan63** [williewillus/Botania#117]
Am running FTB Unstable 3.0.28 w/ Botania.r1.8-248-MC1.8-b9b0666, Tossing Minecraft glass into mana pool won't create Mana glass, with or without a alchemy catalyst, even tried the everlasting guilty manapool, No mana glass

**Comment by yrsegal** [comment]
It's a bug with intangible. It converts dropped glass to its own entity.
There's something in Intangible's config to fix it.

**Comment by Unatan63** [comment]
Does turning that comment to False change how intangible functions?

**Comment by yrsegal** [comment]
It does but droppers will still create the glass entity, if you need it.

**Comment by Unatan63** [comment]
I guess I should report to Intangible or is this already known?

**Comment by yrsegal** [comment]
it's been reported.
