### ISSUE TITLE
Solegnolia doesnt disrupt ring of magnetization

### ISSUE THREAD

**Issue by Makin91** [williewillus/Botania#118]
on version Beta 0.5.4.1

**Comment by williewillus** [comment]
put on the manaseer monocles and make sure the item is actually within range of the flower.
show screenshots of your setup, also.

**Comment by williewillus** [comment]
I can't reproduce

**Comment by yrsegal** [comment]
he probably powered it

**Comment by williewillus** [comment]
yeah closing for now
