### ISSUE TITLE
Managlass cannot be crafted when throwing glass into a mana pool

### ISSUE THREAD

**Issue by Ugaps** [williewillus/Botania#122]
This was happening in 0.6 beta, but as it wasn't mentioned in the 0.6.1 changelog I assume that it hasn't been fixed yet.

When I had glass selected on my hotbar and I was pointing my crosshair at a mana pool, the pool had enough mana, the recipe showed as "craftable" (it had a green tick on it), but when I threw my glass into it, it didn't do anything.

I also tried it a couple times, but it refused to work.

**Comment by yrsegal** [comment]
This is intangible's fault. There's a config option. Emoniph refuses to fix
it.

**Comment by williewillus** [comment]
Yup, I should put that in the FAQ/EAQ :P
