### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by CJL48** [williewillus/Botania#125]
As of Beta 0.6.1, running on minecraft forge 1.8.9-11.15.1.1722, several blocks in botania display a pink and black texture rather than what they should look like. In order of severity:
- Lexica Botania's first person render when held in hand (barely noticeable, only affects 3d render).
- All four varieties of mana spreader's inventory renders are untextured - however, mana spreaders render with the correct texture in world.
- The mana pump, both in world and as shown in inventory.
- The Plains, Mountain, Swamp, and Tiaga petal apothecaries, again both in world and in inventory.

**Comment by williewillus** [comment]
I'm very aware of all of these :P

**Comment by seanamor** [comment]
Are most if not all the texture/models errors fixed? I was waiting for most issues to be fixed before adding this to our server. I am by no means being impatient, it is a wonderful thing you have done, taking on this port. Thanks!

**Comment by williewillus** [comment]
Yeah, only the spreaders' item forms and the lexicon first person model are out still.
Spreaders will probably be done within the next few builds, lexicon a bit longer (still got some stuff to figure out)
