### ISSUE TITLE
Development Builds

### ISSUE THREAD

**Issue by ThexXTURBOXx** [williewillus/Botania#126]
Hello, 
I am a Modder and I want to add integration for your mod (Yeah, I am 1.8/1.8.9, too and so I can't use Vazkii's one)... Is there a deobfuscated version of your mod somewhere to download?

**Comment by GirafiStudios** [comment]
Deobf version was only used for modders beeing able to run mods in a dev workspace. But as of recently you don't need this anymore, you can drop any mod in your run/mods folder and it should run :) For integration you woud simply just need the Botania API :)

**Comment by williewillus** [comment]
If you're using a recent enough version of FML/forge, you don't need deobf builds, you can just drop the mod into your mods folder and it should work automatically, that's why I stopped making them.
