### ISSUE TITLE
StackOverflowError on worldgen with Garden of Glass

### ISSUE THREAD

**Issue by LlubNek** [williewillus/Botania#127]
Not really sure this is your bug, but I got a StackOverflowError due to infinite recursion in worldgen when using Vazkii's Garden of Glass (from curseforge) with Botania.

Here's the crash report:
http://pastebin.com/Q3AEW0VL

**Comment by yrsegal** [comment]
looks more like thaumcraft's fault. Can you check if it fails without it?

**Comment by LlubNek** [comment]
Not Thaumcraft.  Turns out it was ShadowTweaks.

**Comment by williewillus** [comment]
Cool, thanks for tracking it down. Might wanna report if not already done so (though I already poked him on IRC about it)
