### ISSUE TITLE
Crash when visiting Botania creative tab

### ISSUE THREAD

**Issue by BBoldt** [williewillus/Botania#13]
https://gist.github.com/d7ae2871ddb0b86765ea

Using alpha 0.1, and the final release of forge 1.8.8.

**Comment by BBoldt** [comment]
Looks like it may have something to do with WAWLA or potentially BOP.

**Comment by williewillus** [comment]
does it happen in the full listing? (hit the search button, see a list of all creative tabs combined)

**Comment by BBoldt** [comment]
yes

**Comment by BBoldt** [comment]
to be honest, WAWLA probably hasn't updated it's compat for the new botania

**Comment by williewillus** [comment]
presumably closed for #16
