### ISSUE TITLE
Placing magic flower with Psi's "Place Block" or "Place Block Sequence" gives an error block

### ISSUE THREAD

**Issue by r-stronghammer** [williewillus/Botania#130]
This error block is named "Botania Flower" and has a description saying to report it.

**Comment by williewillus** [comment]
~~that shouldn't be happening, the two blocks have different ID's entirely 0.o~~
Can you give me detailed steps to reproduce? (or the exact spell text)

**Comment by williewillus** [comment]
Ah, confirmed. Psi bug, see https://github.com/Vazkii/Psi/issues/94

**Comment by williewillus** [comment]
Fixed in next Psi
