### ISSUE TITLE
Sojourner's Sash step assist not working

### ISSUE THREAD

**Issue by BBoldt** [williewillus/Botania#132]
https://github.com/BBoldt/ThePioneers/issues/26

Botania.r1.8-248-MC1.8-0.6.1
Forge 1761

**Comment by TheWhiteWolves** [comment]
Step assist has been working fine for me so far, I can check again tonight but the code in that section hasn't changed since 1.7, though I did notice on dires video the other day they were on about something breaking step assist by making blocks a slight bit bigger than normal, so it may not be botania causing it, it's just getting affected by whatever is breaking step assist.

**Comment by williewillus** [comment]
I can't reproduce either

Maybe the user didn't have mana?

**Comment by BBoldt** [comment]
User has mana. It must be something else in my pack triggering the bug, as the guy above said.

**Comment by williewillus** [comment]
I'll update my copy of the pack and check it out when I have time

**Comment by Atoru** [comment]
The Pioneers modpack (Release 4) - Botania.r1.8-248-unofficial-0.6.2
I crafted up a soujourner's sash and have a +50% filled ring of mana

Not working:
- fall resistance
- step assist

Working:
- jump boost
- speed

**Comment by williewillus** [comment]
Step assist works for me.
Fall resistance also works, it's not a big reduction for the sojourner and only is applied when you jump (it was like that in 1.7)

**Comment by Atoru** [comment]
hmmm

I have now a 100% filled mana ring and step assist still does not work for me...
a buddy of my just confirmed the same (step assist not working) - same modpack/server

**Comment by williewillus** [comment]
Do you have other mods/items that give step assist?

**Comment by Atoru** [comment]
prob thaumcraft but we don't have the research for that yet :S

**Comment by Atoru** [comment]
Thaumcrafts Boots of the traveller step assist works - soujourner's and globetrotter's step assist does not work...

(Botania.r1.8-unofficial-0.6.4.2)

**Comment by yrsegal** [comment]
This doesn't appear to be an issue as of 1.9.

**Comment by williewillus** [comment]
cool
