### ISSUE TITLE
Managlass recipe not quite working

### ISSUE THREAD

**Issue by oitsjustjose** [williewillus/Botania#133]
![2016-02-24_22 35 04](https://cloud.githubusercontent.com/assets/3887324/13309082/5eba89a8-db47-11e5-973f-132bf4259a1f.png)

Haven't found any other recipes that this happens with. I'll also note that I'm on 0.6.1, so my apologies if it's been fixed, but I took a look and didn't see anything that indicated such in-between versions :)

**Comment by yrsegal** [comment]
It's intangible's fault. Emoniph refuses to fix it. Config option in intangible's config. That's time 5 this has been posted... dammit Emoniph

**Comment by oitsjustjose** [comment]
Crud, sorry!!! I had no idea >:(

**Comment by yrsegal** [comment]
not your fault. It's Emoniph's for being stubborn, and replacing glass with his own entity.

**Comment by oitsjustjose** [comment]
Oh duh, I did see where he has a config for replacing the dropped Glass entityitem >_> **I should've put two and two together**
