### ISSUE TITLE
Crash on Server Connect 1.8 

### ISSUE THREAD

**Issue by ZL1LAC** [williewillus/Botania#134]
Crashing on server connect.

`http://pastebin.com/iw75NGkg`

**Comment by yrsegal** [comment]
JEI, why are you checking a null brew? jei pls.

**Comment by mezz** [comment]
Don't be hasty, I'm only asking the creative tab for its items :p

**Comment by yrsegal** [comment]
creative pls

**Comment by yrsegal** [comment]
wait, how are you pinging creative on the server? isn't that a clientside method?

**Comment by mezz** [comment]
JEI is 99% clientside

**Comment by yrsegal** [comment]
No, this is the server's fault. but how

**Comment by mezz** [comment]
In the latest JEI I catch the crash and log it as an error. Probably means that some of the items will be missing from JEI until the crash is fixed though.

**Comment by williewillus** [comment]
Can you reproduce this with a certain mod + botania or botania alone?

**Comment by williewillus** [comment]
bump

**Comment by mezz** [comment]
@dh47 ^

**Comment by ZL1LAC** [comment]
@williewillus yes it works without JEI installed.

**Comment by williewillus** [comment]
does it work without thaumcraft and with JEI?

**Comment by ZL1LAC** [comment]
Yes.  I think Mezz put in some debugging here's my console output.
https://dl.dropboxusercontent.com/u/5392483/fml-client-latest.log

**Comment by williewillus** [comment]
that log doesn't say anything about botania 0.o

**Comment by ZL1LAC** [comment]
Weird he said he added debugging.
^ @mezz

**Comment by williewillus** [comment]
It's probably a thaumcraft Botania crash judging what you said but I thought I fixed those already...

**Comment by williewillus** [comment]
Should be fixed with #147 and #148 in next build
