### ISSUE TITLE
lexica botania texture/model problem

### ISSUE THREAD

**Issue by reinder-s** [williewillus/Botania#135]
java 8
windows 10
forge 1.8.9-11.15.1.1761

so i was playing in my world
and when i made the lexica i noticed that i instead of the lexica was holding a purple stripe
and in f5 mode it was flat and about 1 block in height and width
![2016-02-25_10 27 51](https://cloud.githubusercontent.com/assets/11552821/13315411/d511feca-dbaa-11e5-8574-e0cd3c75b6fb.png)
![2016-02-25 2](https://cloud.githubusercontent.com/assets/11552821/13315410/d5069512-dbaa-11e5-8e4e-a72715a368ef.png)

**Comment by williewillus** [comment]
I know
It's being worked on
