### ISSUE TITLE
Let pure daisy recipes registered through the API provide the recipe time

### ISSUE THREAD

**Issue by williewillus** [williewillus/Botania#137]
from irc

**Comment by yrsegal** [comment]
This requires an api change, so it should leave the old version intact and add a new version that the daisy checks for.

**Comment by yrsegal** [comment]
wait, what? NO! You changed the API, breaking all mods which add pure daisy recipes.

**Comment by yrsegal** [comment]
at least there should be a secondary constructor...

**Comment by williewillus** [comment]
look closer...the BotaniaAPI method is still there...

**Comment by yrsegal** [comment]
I extend RecipePureDaisy... please just have a default constructor which is like the old one >.>

**Comment by yrsegal** [comment]
it's not good form to remove without deprecation an old method from an API

**Comment by williewillus** [comment]
the api can shift whatever at this time and I didn't think changing a constructor was so much work, but fine

**Comment by yrsegal** [comment]
the api should always add to it, never remove. That way, you won't break old addons.

**Comment by williewillus** [comment]
It's not like you wouldn't have had to change it anyway (the constructor changed to use IBlockState in 1.8)

Anyways, readded.
