### ISSUE TITLE
Rod of the Terra Firma client crash

### ISSUE THREAD

**Issue by Ryahn** [williewillus/Botania#138]
When using the Rod of the Terra Firma, the earth beneath you is shaped according to the Y-level you are standing on

Crash Log: http://paste.resonant-rise.com:7777/agaculewid.coffee

Unfortunately do not have the FML log

**Comment by williewillus** [comment]
Your build is a month+ old, update and try to reproduce on the latest version

**Comment by williewillus** [comment]
actually yes this is a dupe of #90 and #100, update and it should be fixed
