### ISSUE TITLE
Planestrider's sash doesn't do anything 

### ISSUE THREAD

**Issue by Hyxaru** [williewillus/Botania#139]
I lied, it is stil taking a slot when equiped and gives the player a yellow belt :S
Speed up does not occur though.

**Comment by williewillus** [comment]
Do you have mana? What version? Modlist?

**Comment by Hyxaru** [comment]
Biomes O' Plenty, latest botania version ofc, mantle, tconstruct and thaumcraft.
I had the creative mana tablet on me.
