### ISSUE TITLE
game crashing on destruction mana spreader

### ISSUE THREAD

**Issue by Noobfortress** [williewillus/Botania#146]
Minecraft crashed because a creeper blew up my mana spreader :/
I don't have much info because I don't quite know what happened eactly, but here's the crash report: http://pastebin.com/xKvWtRZ0

**Comment by blacksmithgu** [comment]
This seems to be a very similar issue to the recently fixed #142. A test is in order to see if this is a seperate issue...

**Comment by williewillus** [comment]
fix for #142 is not in a public build yet

**Comment by blacksmithgu** [comment]
Right, which is why your patch for #142 may/probably also have fixed this (as the stack trace is exactly the same). A test is in order to check, of course.

**Comment by Noobfortress** [comment]
Ah.I didn't see #142 because it was closed :/ 
It does seem to be the same issue: the game still searching for a state of a no longer present block

**Comment by blacksmithgu** [comment]
Ha, no worries. It's possible this is another edge case of the same problem, so eventually I'll get around to actually testing it.

**Comment by williewillus** [comment]
Should be fixed in next build
