### ISSUE TITLE
Bore Warp Lens destroys relay endpoint

### ISSUE THREAD

**Issue by CJL48** [williewillus/Botania#149]
When firing a bore warp lens through a force relay, the mana burst leaves the relay intact but breaks the block that it is linked to. This also prevents the relay endpoint from being moved until a block is placed in that spot.
MC 1.8.9
Forge 11.15.1.1763
Botania.r1.8-248-unofficial-0.6.2

**Comment by yrsegal** [comment]
are you using Bore Warp or Warp Bore? only one should do this.

**Comment by CJL48** [comment]
Bore Warp, not Warp Bore

**Comment by yrsegal** [comment]
have you tried both?

**Comment by williewillus** [comment]
Got a screenshot of the build? And a description of how it works in 1.7 vs 1.8

**Comment by Azutte** [comment]
http://imgur.com/a/xDOYF

**Comment by Azutte** [comment]
That's "bore warp" lens on the spreader, and the relay is bound to the wool block. In 1.7.10. It destroys a bunch of the blocks AFTER it. They're saying it would destroy the wool also.

**Comment by yrsegal** [comment]
Ohhh, i was misunderstanding. :P

**Comment by CJL48** [comment]
Thanks, this makes it possible to build a botania quarry in the 1.8 port.
