### ISSUE TITLE
Initial Serversiding: Make Sparkle/WispFX use a packet

### ISSUE THREAD

**Issue by blacksmithgu** [williewillus/Botania#150]
This is largely a duplicate from Vazkii/Botania#1767 which I'm also placing into this repository for reference, but a packet should definitely be made for Sparkle and WispFX (it could just be created and sent in the CommonProxy's sparkleFX and wispFX methods). This should allow for a lot of clientside code to be eliminated and completely serversided.

Furthermore, the code which generates the FX may also benefit from being centralized and placed into functions, so there aren't random blocks of code in items and so forth which are purely rendering and FX related.

If you have something in mind already, great; otherwise, this will be on my bucket list of things to do in the next few days.

**Comment by williewillus** [comment]
https://github.com/williewillus/Botania/tree/residing

**Comment by blacksmithgu** [comment]
Excellent!
