### ISSUE TITLE
Mana spreader and mana pool appearing reset/empty, circumstances unknown.

### ISSUE THREAD

**Issue by gl0x** [williewillus/Botania#152]
Not consistently reproducable, but regularly happens in multiplayer. Updating with the wand shows accurate values. My guess is the client and server not syncing correctly.

http://imgur.com/a/hdxve

First image is the error where the spreaders default to facing east(?) and the pool appears empty.

**Comment by williewillus** [comment]
Hm does this only happen when coming back to an area, or just randomly when you're standing? There?

**Comment by gl0x** [comment]
I've never noticed it while I just stand around, it's always when I come back to the area. I'm never going  too far (it never unloads), but I do leave the chunk.

**Comment by chaosMoth** [comment]
This has been happening to me too. Sometimes even right when I'm looking at it. It always seems to accompany a nearby tree growing, for me.

**Comment by williewillus** [comment]
huh, this seems to be closely related to #71, which happened to me on a test server in the proximity of nearby trees.

Not sure what trees are doing to mana pools, but will investigate

**Comment by gl0x** [comment]
It would appear to be trees. My tree farm right next door seems to be the culprit. 

http://imgur.com/a/FDqyk

**Comment by williewillus** [comment]
Yup.

The reason is that when a large amount of blocks changes, mc sends a different packet to the client. Due to a quirk and the TE being eager to refresh, it wipes on the client until the server resyncs.

Trivial cause for one of the biggest headaches of this port (#71) lol
