### ISSUE TITLE
Crash when searching index

### ISSUE THREAD

**Issue by jrpoints** [williewillus/Botania#153]
http://pastebin.com/9sW5WvCi

In v0.6.3 when I try to search the index page of the lexicon I get this crash.

**Comment by williewillus** [comment]
I can't reproduce, can you try narrowing it down to a certain set of mods?

**Comment by williewillus** [comment]
bump

**Comment by jrpoints** [comment]
Sorry for taking so long to respond.

I removed all my mods and was still getting the crash, so i decided to delete the config and to have it make a new one and now I can search no problem.

Edit: I found out that if I copy paste my servers botania config over to my client I get the crash again, but If i delete the config from the client to get a new one I can search the index again, also I didn't mention but I can search all other categories fine, it is just the index that would crash. Weird.

**Comment by williewillus** [comment]
Can you link the config that crashes?

**Comment by jrpoints** [comment]
http://pastebin.com/QGZeN60z

Ok, so after much trial and error and restarts i narrowed it down to the couple changes I made to the config, these lines specifically

```
# Configuration of Shedding for Chicken
S:Chicken.item=minecraft:
I:Chicken.lexiconDisplaySize=20
I:Chicken.metadata=0
I:Chicken.rate=26000

# Configuration of Shedding for Cow
S:Cow.item=leather
I:Cow.lexiconDisplaySize=40
I:Cow.metadata=0
I:Cow.rate=20000
```

and it turns out I didn't set the chicken.rate to -1, and for whatever reason that was causing the crash. So as long as I make sure to set the rates correctly there is no crash.

**Comment by yrsegal** [comment]
minecraft: isn't an item id, could that be it?

**Comment by williewillus** [comment]
that's porbably it, the checks in place don't check if the item is invalid, just if its empty or null.
