### ISSUE TITLE
Minecart with manapool doesn't make riding sounds

### ISSUE THREAD

**Issue by Hyxaru** [williewillus/Botania#154]
Unlike vanilla minecarts, it does not make the loud metalic noice when riding on rails. Might also not be present in the official Botania.

**Comment by williewillus** [comment]
Can't reproduce

**Comment by williewillus** [comment]
Bump? make sure you have your sounds up, my pool carts make soudns just fine.
Let me know of a surefire way to reproduce and I'l reopen

**Comment by Hyxaru** [comment]
Cant reproduce anymore after I dropped Tinkers. Perhaps mantle did some weirdness but issue closed.
