### ISSUE TITLE
Crash when hovering over certain Botania brew in JEI

### ISSUE THREAD

**Issue by actos** [williewillus/Botania#156]
Not sure if you're looking for these types of reports atm since technically it involves another mod, but I thought I'd toss it here anyway.  I ran into a game crash when mousing over what looks like the Flask of Crossed Souls in JEI.

I'm running a watered down version of FTB Unstable 1.8 (3.0.36 with most of the tech mods disabled)

http://pastebin.com/0NzY8dmh

**Comment by TheWhiteWolves** [comment]
Try updating Botania first and see if its still happening

**Comment by williewillus** [comment]
This _should_ be fixed in 0.6.3, which I don't think unstable has updated to yet. Closing for now, if it happens in 0.6.3 comment here and I'll reopen
