### ISSUE TITLE
Nether

### ISSUE THREAD

**Issue by 3DCircle** [williewillus/Botania#157]
I think that it would be more appropriate for the nether in this mod pack to be void because the overworld is, and players could just move into the nether without any negative effects from that. Making the void in the overworld not needed or not used.

**Comment by yrsegal** [comment]
if that was true, a lot of progression would be impossible.

**Comment by 3DCircle** [comment]
No you can use Ex Nihilo to create soulsand to get netherwart and netherquartz. You can just build a platform to spawn Ghasts and Zombie Pigman.

**Comment by yrsegal** [comment]
Ex Nihilo isn't in Garden of Glass. Botania only balances around itself.

**Comment by 3DCircle** [comment]
I'm talking about the new Botanical Ascension 2 pack.

**Comment by yrsegal** [comment]
That has nothing to do with this repo.

**Comment by 3DCircle** [comment]
Oh, the world link led me here

**Comment by yrsegal** [comment]
the... world link?

**Comment by 3DCircle** [comment]
the chat link was https://github.com/williewillus/Botania/issues

**Comment by yrsegal** [comment]
yeah, if you have any BUGS...

**Comment by williewillus** [comment]
Talk pack balance to your pack dev not me lol
The balance as it is is okay, changes of that suze probably won't happen
