### ISSUE TITLE
Fighting Gaia 2

### ISSUE THREAD

**Issue by Inpingo** [williewillus/Botania#158]
Firstly, thanks for porting Botania to 1.8.9!

I just killed Gaia 2 and my client crashed to desktop, it now crashes repeatedly. When logging in.

Crash report attached. 

[crash-2016-03-05_15.04.41-client.txt](https://github.com/williewillus/Botania/files/159853/crash-2016-03-05_15.04.41-client.txt)

**Comment by williewillus** [comment]
Try updating to 0.6.2 or 0.6.3

**Comment by Inpingo** [comment]
Link a newb please

**Comment by yrsegal** [comment]
... it's literally in the releases tab...
https://github.com/williewillus/Botania/releases/tag/v0.6.3-beta

**Comment by Inpingo** [comment]
Appreciated!

**Comment by williewillus** [comment]
Let me know if it keeps happening
