### ISSUE TITLE
[rolling] Lang updates

### ISSUE THREAD

**Issue by williewillus** [williewillus/Botania#159]
Just a constant reminder to myself and translators to propagate changes I've made to the lang in 1.8.x to the other lang files
- ADDITIONS:
  - botania.page.pool15=Creating &1Prismarine Shards&0 (copy from botania.page.prismarine2)
- CHANGED (new values shown):
  - botania.page.stoneAlchemy2=Brickage
  - botania.page.stoneAlchemy3=Chiseling
  - botania.page.corporeaFunnel1= The &1Corporea Funnel&0 may only pull items that match its filter, similarly to a &1Hopperhock&0, the filter is designated by items contained on &1Item Frames&0 placed on it. The item pulled is one of the various items in the frames at random.<br>Rotating the item changes how many will be requested at once, starting at 1, rotating will pull 2, 4, 8, 16, 32, 48, and finally 64 items, respectively.
  - botania.page.banners0= &1Botania&0 adds &415&0 new icons to banners, which can be mixed and matched with the original patterns and icons.<br>The following items can be used alongside a dye in the crafting grid to add an icon to a &1Banner&0: &1All Iron Tools&0, &1Spark Augments&0, &1Raw Fish&0, &1Livingwood and Dreamwood Twigs&0, &1Lexica Botania&0, &1Terrasteel&0 and the &1Tiny Potato&0.
  - botania.page.stoneAlchemy0=Using an &1Alchemy Catalyst&0 proves to be a decently functional method of generating new types of &1Stone&0. Simple deal, tossing a piece of &1Stone&0 into the catalized pool will transform it into another in a cycle.<br> Stairs and slabs can be made from the rough and brick variants of these.
- REMOVED:
  - botania.page.stoneAlchemy4=Chiseling
  - botania.entry.prismarine=Prismarine
  - botania.tagline.prismarine=UFO Commander, we are the future
  - botania.page.prismarine0=&1Prismarine&0 is an interesting component and building block. Some scholars even go as far as to say it comes from &4the future&0.<br>To create it, one requires an &1Alchemy Catalyst&0. Simply tossing some &1Nether Quartz&0 into a &1Mana Pool&0 with the catalyst attached to it will get some of this material.
  - botania.page.prismarine1=There's various building blocks that can be created using the &1Prismarine Shards&0, to which all but the &1Sea Lantern&0 can be turned into their &1Stair&0 and &1Slab&0 variants.
  - botania.page.prismarine2=Creating &1Prismarine Shards&0
  - botania.page.prismarine3=Crafting &1Prismarine&0
  - botania.page.prismarine4=Crafting &1Prismarine Bricks&0
  - botania.page.prismarine5=Crafting &1Dark Prismarine&0
  - botania.page.prismarine6=Crafting the &1Sea Lantern&0

**Comment by vladfrangu** [comment]
Wait.. Can I translate it into my countrys language? Probably worthless but still

My language is Romanian btw

**Comment by williewillus** [comment]
Yes, always! Take a look at the comments on the top of the en_US.lang and have at it. Thanks for your contribution!

**Comment by williewillus** [comment]
This ticket isn't updated anymore so I'm closing it

**Comment by vladfrangu** [comment]
Question.. Do you support custom characters like ș, ț, ă, î ,â? Cause I need those

**Comment by yrsegal** [comment]
It should, standard lang format allows unicode and expanded ascii

**Comment by vladfrangu** [comment]
Nifty.. Will try, thanks!
