### ISSUE TITLE
Enchantment Power from Inventory

### ISSUE THREAD

**Issue by Darkhax** [williewillus/Botania#16]
Hello, 

I am the dev of Wawla, and a bug report about a crash that happens when you look at a pylon in the inventory. Wawla adds the enchantment power of a block to the tooltip in the inventory. The method used takes a world instance and a BlockPos, however there is no BlockPos when you are in the player's inventory. To get around this, I pass the ORIGIN position which is 0, 0, 0 as a sort of null. The crash comes from Botania not checking to see if the BlockPos passed is linked to a valid Pylon block. I am not sure how I could solve this issue on my end, without adding a special case for the pylon block, or by removing the feature entirely. Would it be possible to get a fix implemented on Botania's end, to check if the block at the position is actually a pylon, and if not, return 0?

**Comment by williewillus** [comment]
Made the behavior match upstream (not our block or mana variant -> 8, else 15)

**Comment by Darkhax** [comment]
Thank you for fixing this <3
