### ISSUE TITLE
after some time botania power making flowers disepire after some time?!?!

### ISSUE THREAD

**Issue by RespectMathias** [williewillus/Botania#160]
the title says everything i dont know what more to say please help me figerit aut

![2016-03-06_22 30 19](https://cloud.githubusercontent.com/assets/17691448/13557202/3d0476f0-e3eb-11e5-807d-890f114aebc9.png)

**Comment by RespectMathias** [comment]
and only when the flower is placed and this is a picture of my water flower power thing

**Comment by yrsegal** [comment]
This is intended behavior. Please RTFM.

**Comment by RespectMathias** [comment]
are you kiding me?!?!

**Comment by yrsegal** [comment]
no...

**Comment by RespectMathias** [comment]
il be removing this report

**Comment by yrsegal** [comment]
thank you.

**Comment by RespectMathias** [comment]
how do i remove it i forgot?

**Comment by yrsegal** [comment]
`Close issue`.
