### ISSUE TITLE
Crash on respawn

### ISSUE THREAD

**Issue by DrManganese** [williewillus/Botania#161]
The game crashes when I respawn after death, afterwards when rejoining the world there is no crash. 

Mod Version: Botania r1.8- 0.6.4

Crash Report: http://pastebin.com/EgQBdeqk

Modpack: http://minecraft.curseforge.com/projects/the-ryrypatpatpackpack-1-8-9

**Comment by williewillus** [comment]
can you try without optifine?

**Comment by DrManganese** [comment]
Without any other mods: http://pastebin.com/MUfKC30t

It also crashes when I a walk away (I presume when the chunk unloads).
