### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by Xilef11** [williewillus/Botania#162]
I've been getting frequent random crashes with version 0.6.4 (in the FTB Unstable pack). According to the [crash report](http://pastebin.com/zMJ0Z7pU), it has something to do with the spreaders, but it happens when I'm out in the wild.

**Comment by williewillus** [comment]
try without optifine. I'm starting to notice a pattern with it appearing in every crash report of this kind

**Comment by yrsegal** [comment]
@williewillus you should also probably just check that the alfportal isn't air. (inbetween [here](https://github.com/williewillus/Botania/blob/MC18/src/main/java/vazkii/botania/common/block/tile/TileAlfPortal.java#L112-L113))

**Comment by yrsegal** [comment]
and such for all similar crashes.

if it's possible to fix it without alienating people whose computers only run modded with OF, it probably makes sense to do so.

**Comment by mconwa01** [comment]
I'm getting the same traceback without Optifine. It seems to be happening when I get around 10-12 chunks (Manhattan distance) from my Botania stuff (a few spreaders, mana pools, petal apothecary, runic altar, early flowers, and an inactive Alfheim portal). Crashes on client side only; server is fine.

```
    UCHIJA  mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJA  FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1764.jar) 
    UCHIJA  Forge{11.15.1.1764} [Minecraft Forge] (forge-1.8.9-11.15.1.1764.jar) 
    UCHIJA  OpenComputers|Core{1.5.22.6} [OpenComputers (Core)] (minecraft.jar) 
    UCHIJA  Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
    UCHIJA  Botania{r1.8-250} [Botania] (Botania.r1.8-unofficial-0.6.4.jar) 
    UCHIJA  chiselsandbits{mc1.8.9-v1.8.11} [Chisels & Bits] (chiselsandbits-mc1.8.9-v1.8.11.jar) 
    UCHIJA  inventorytweaks{1.60-beta-39-eae6253} [Inventory Tweaks] (InventoryTweaks-1.60-beta-39.jar) 
    UCHIJA  IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
    UCHIJA  JEI{2.28.6.173} [Just Enough Items] (jei_1.8.9-2.28.6.173.jar) 
    UCHIJA  journeymap{1.8.9-5.1.5} [JourneyMap] (journeymap-1.8.9-5.1.5-unlimited.jar) 
    UCHIJA  OpenComputers{1.5.22.6} [OpenComputers] (OpenComputers-MC1.8.9-1.5.22.6.jar) 
    UCHIJA  Psi{beta-19} [Psi] (Psi-beta-19.jar) 
    Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.60-beta-39.jar)
  invtweaks.forge.asm.ContainerTransformer
TransformerLoader (OpenComputers-MC1.8.9-1.5.22.6.jar)
  li.cil.oc.common.asm.ClassTransformer
```

**Comment by yrsegal** [comment]
that seems like a relatively innocent list. This seems like a chunkloading issue, such as we've had in the past.

**Comment by ArMoReDfUrY** [comment]
I'm also getting "Ticking Block Entity" Crashes when i leave my Botania area.
this has been both on Mana Spreaders & Mana pools
I don't have Optifine installed (too many glitches in the render)
I'm also not using any chunkloaders.

1st report -
[crash-2016-03-07_12.12.46-client.txt](https://github.com/williewillus/Botania/files/161107/crash-2016-03-07_12.12.46-client.txt)

2nd report - 
[crash-2016-03-07_12.24.34-client.txt](https://github.com/williewillus/Botania/files/161108/crash-2016-03-07_12.24.34-client.txt)

I can post a pic of my setup if needed.

Edit: just to note Air blocks seems to be involved in all these.

**Comment by yrsegal** [comment]
it's probably less that its air and more that the chunks are unloaded.
