### ISSUE TITLE
Corporea Sparks and associated blocks

### ISSUE THREAD

**Issue by actos** [williewillus/Botania#164]
Hey, thanks for all the work you are doing porting botania to 1.8.9, it's one of my favorite mods by far.

I just updated to 0.6.4.1 (from 0.6.3) and it popped all the corporea sparks off my corporea crystal cubes and corporea funnels and I can't seem to place them back on.  I tried removing and replacing the blocks without success.

Any other info you need I'll be happy to provide.

**Comment by williewillus** [comment]
Should work in latest build now (0.6.4.2)
