### ISSUE TITLE
Mana prism with lens has no effect on mana bursts

### ISSUE THREAD

**Issue by mconwa01** [williewillus/Botania#167]
Placed a prism a few blocks in front of a Pulse Mana Spreader (with no lens) attached to a filled Mana Pool, and tried firing the spreader through the prism with a lens attached to the prism. The mana burst was not affected by any lens I tried (basic tinted, potency, velocity, phantom, gravity, entropic, bounce). Each of these lenses worked when attached directly to the spreader instead.

Tested with v0.6.4.2, Forge 11.15.1.1764, Baubles v1.1.3.0.

**Comment by williewillus** [comment]
I accidentally inverted the redstone power check and no one told me til now xP
For now, power the prism with redstone and it should work.
It'll be corrected in the next build
