### ISSUE TITLE
If have been drinking potions can get a lot of bottles

### ISSUE THREAD

**Issue by bunSakurAing** [williewillus/Botania#168]
If I took a bottle of potions right click long, I will get a lot of empty bottles……
The picture:http://tu.etang.info/uploads/2016/03/QQ图片20160309205417.png

**Comment by williewillus** [comment]
Can't reproduce, drinking all kinds of brews and vanilla potions work fine.

Can I have more detailed steps to make it happen again? As well as your version and modlist

**Comment by bunSakurAing** [comment]
I took out a full bottle of potions, then drank three times, right click long, he will keep the generation of the empty bottles, process as shown in figure.
1.http://tu.etang.info/uploads/2016/03/QQ截图20160309233919.png
2.http://tu.etang.info/uploads/2016/03/QQ图片20160309233948.png
modlist:http://tu.etang.info/uploads/2016/03/QQ图片20160309234529.png
This happened in the server, in a single game without the situation.(Server is running the sponge)

**Comment by williewillus** [comment]
I think this is a sponge issue, I just tried doing it in my own server (no Sponge) and it doesn't happen.

Are the bottles fake? Do they disappear when you try to pick them up?

**Comment by bunSakurAing** [comment]
They can be picked up.

**Comment by williewillus** [comment]
does it happen without sponge?

**Comment by bunSakurAing** [comment]
it happen with sponge.;o So what should I do?

**Comment by yrsegal** [comment]
that's not the question. Does it happen if you load the modpack without sponge?

**Comment by bunSakurAing** [comment]
@yrsegal It will occur in the sponge

**Comment by yrsegal** [comment]
that's not what I asked. I understand it happens with sponge. Can you tell us if it happens without it?

**Comment by bunSakurAing** [comment]
@yrsegal When I unload a sponge, he will get an empty bottle,doesn't increase

**Comment by yrsegal** [comment]
so, this is only a sponge problem. Thank you, that's what I was asking.

**Comment by williewillus** [comment]
Yup, sponge problem. We just use normal vanilla methods to add the bottle to the inv after drinking, report it to them
