### ISSUE TITLE
Runic Altar recipes are listed in JEI under Petal Apothecary instead

### ISSUE THREAD

**Issue by mconwa01** [williewillus/Botania#172]
Botania v0.6.4.2, Forge 11.15.1.1764, JEI 2.28.6.173, Baubles v1.1.3.0.

**Comment by williewillus** [comment]
uh any other mods?

**Comment by williewillus** [comment]
perfectly fine for me in dev

**Comment by williewillus** [comment]
try downgrading JEI to 2.25.7.145 really quick and seeing if it's wrong there, that's the version that I build on.

**Comment by mconwa01** [comment]
OK, it works fine with JEI 2.25.7.145.

Those were the only mods I was testing with (other than MCP and FML). I'm seeing the problem with the latest JEI (2.28.7.174) as well. The Petal Apothecary section lists both its own recipes and those for the Runic Altar--90 recipes total. There is no Runic Altar section that I can find.

**Comment by williewillus** [comment]
Must be a JEI bug then.

https://github.com/mezz/JustEnoughItems/issues/205

**Comment by williewillus** [comment]
_should_ be fixed next build, let me know then if it keeps happening
