### ISSUE TITLE
Tossing items in mana pool on server.

### ISSUE THREAD

**Issue by GirafiStudios** [williewillus/Botania#18]
Still using same custom build as I mentioned yesterday. Don't looks like any of your many recent commits have fixed it tho (Good job btw.!)
Just simply tossed a piece of redstone in a mana pool with mana in.

Crashlog: https://gist.github.com/GirafiStudios/88bf7114a1ab4122ba66

**Comment by williewillus** [comment]
wtf, it says the method Item.getAge (something from vanilla) is not there.
Are there any coremods modifying that method that you know of?

**Comment by williewillus** [comment]
Ah, nvm it's a client only method and I didn't see that. Know the solution
