### ISSUE TITLE
terra shatterer x-ray effect

### ISSUE THREAD

**Issue by Atoru** [williewillus/Botania#184]
If I hover over my terra shatterer in my inventory I get a somewhat x-ray effect in the background

> http://puu.sh/nIjEq/20b4cf45cd.jpg

Botania.r1.8-unofficial-0.6.4.2

**Comment by williewillus** [comment]
uh oh 0.o
I can't reproduce this in dev

try some things for me
1. update to 299
2. Hide JEI (ctrl o). If it's fixed after hiding JEI try to hunt down the item that needs to be on screen the same time as the pick to cause the issue.
3. alternatively / additionally, try it with botania alone

thanks!

**Comment by Atoru** [comment]
hmm in current version that the pioneers pack uses I get the x-ray effect even if I remove JEI from the mods list (server and sp)... will try again once botania gets updated in this pack,...

**Comment by yrsegal** [comment]
This one absolutely does not occur with the new override system.

**Comment by williewillus** [comment]
taking your word for it :P 
@Atoru if it happens in 1.9 let me know
