### ISSUE TITLE
[1.8.9] Bookmark Crash

### ISSUE THREAD

**Issue by SunnyTD** [williewillus/Botania#187]
Description: Crash on startup
Version: 1.8-299

Logs: 
Minecraft:https://gist.github.com/SunnyTD/7ee797a02cc161101b88
ModLoader:https://gist.github.com/SunnyTD/7c47375b721d5a07c5a6

**Comment by SunnyTD** [comment]
Found a hotfix if this happens to anyone else.
1. Navigate to your minecraft instance folder. (should have folders such as your save, mods, etc.)
2. Delete BotaniaVars.dat
3. Re-run the game.

**Comment by williewillus** [comment]
can't reproduce, but the bookmarks certainly don't seem to be working

**Comment by williewillus** [comment]
I can't find a cause why this would ever happen, so closing for now - lemme know if it happens again in 1.9
