### ISSUE TITLE
Mule with chest > Skeleton horse crash upon giving skeleton horse items

### ISSUE THREAD

**Issue by Hyxaru** [williewillus/Botania#189]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 22-3-16 9:13
Description: Updating screen events

java.lang.ArrayIndexOutOfBoundsException: 2
    at net.minecraft.inventory.InventoryBasic.func_70299_a(SourceFile:115)
    at net.minecraft.inventory.Slot.func_75215_d(Slot.java:70)
    at net.minecraft.inventory.Container.func_75144_a(Container.java:292)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:488)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:629)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:595)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:564)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.inventory.InventoryBasic.func_70299_a(SourceFile:115)
    at net.minecraft.inventory.Slot.func_75215_d(Slot.java:70)
    at net.minecraft.inventory.Container.func_75144_a(Container.java:292)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:488)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:629)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:595)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:564)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)

-- Affected screen --
Details:
    Screen name: net.minecraft.client.gui.inventory.GuiScreenHorseInventory

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['Hyxaru'/230, l='MpServer', x=-2436,50, y=69,85, z=-1379,19]]
    Chunk stats: MultiplayerChunkCache: 289, 289
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: -28,00,64,00,-192,00 - World: (-28,64,-192), Chunk: (at 4,4,0 in -2,-12; contains blocks -32,0,-192 to -17,255,-177), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
    Level time: 3159453 game time, 4362988 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 100 total; [EntityXPOrb['Experience Orb'/27136, l='MpServer', x=-2496,09, y=70,00, z=-1395,78], EntitySkeleton['Skeleton'/33537, l='MpServer', x=-2515,50, y=96,00, z=-1340,91], EntityXPOrb['Experience Orb'/15883, l='MpServer', x=-2532,41, y=75,00, z=-1387,88], EntitySkeleton['Skeleton'/33547, l='MpServer', x=-2388,50, y=63,00, z=-1450,50], EntityXPOrb['Experience Orb'/15884, l='MpServer', x=-2533,50, y=75,00, z=-1389,81], EntityXPOrb['Experience Orb'/15885, l='MpServer', x=-2534,38, y=75,00, z=-1387,91], EntityAuraNode['Aura Node'/272, l='MpServer', x=-2530,50, y=70,50, z=-1342,50], EntityArrow['Arrow'/37907, l='MpServer', x=-2419,06, y=66,13, z=-1383,81], EntityAuraNode['Aura Node'/11028, l='MpServer', x=-2453,50, y=84,50, z=-1474,50], EntityAuraNode['Aura Node'/29975, l='MpServer', x=-2484,50, y=85,50, z=-1242,50], EntityAuraNode['Aura Node'/24856, l='MpServer', x=-2502,50, y=78,50, z=-1294,50], EntitySpider['Spider'/38436, l='MpServer', x=-2512,50, y=69,00, z=-1367,50], EntityAuraNode['Aura Node'/294, l='MpServer', x=-2538,50, y=83,50, z=-1375,50], EntitySpider['Spider'/38438, l='MpServer', x=-2513,50, y=69,00, z=-1364,50], EntityAuraNode['Aura Node'/296, l='MpServer', x=-2541,50, y=81,50, z=-1299,50], EntityCreeper['Creeper'/38443, l='MpServer', x=-2461,03, y=64,00, z=-1316,66], EntitySkeleton['Skeleton'/38444, l='MpServer', x=-2445,50, y=64,00, z=-1321,50], EntitySpider['Spider'/38445, l='MpServer', x=-2449,50, y=64,00, z=-1320,50], EntityCreeper['Creeper'/29485, l='MpServer', x=-2509,50, y=90,00, z=-1333,50], EntityAuraNode['Aura Node'/27187, l='MpServer', x=-2365,50, y=50,50, z=-1269,50], EntityRabbit['Rabbit'/314, l='MpServer', x=-2515,31, y=78,00, z=-1364,56], EntityRabbit['Rabbit'/315, l='MpServer', x=-2512,66, y=81,00, z=-1366,66], EntityZombie['Zombie'/37949, l='MpServer', x=-2360,50, y=19,00, z=-1417,50], EntityZombie['Zombie'/38461, l='MpServer', x=-2434,50, y=66,00, z=-1451,50], EntityZombie['Zombie'/38462, l='MpServer', x=-2433,50, y=66,00, z=-1450,50], EntityZombie['Zombie'/38463, l='MpServer', x=-2434,50, y=66,00, z=-1454,50], EntitySkeleton['Skeleton'/37952, l='MpServer', x=-2360,50, y=19,00, z=-1416,50], EntitySkeleton['Skeleton'/37953, l='MpServer', x=-2358,50, y=19,00, z=-1416,50], EntityRabbit['Rabbit'/13122, l='MpServer', x=-2437,69, y=70,00, z=-1368,44], EntitySkeleton['Skeleton'/37954, l='MpServer', x=-2366,50, y=69,00, z=-1350,50], EntitySkeleton['Skeleton'/38467, l='MpServer', x=-2432,50, y=66,00, z=-1447,50], EntityCreeper['Creeper'/37957, l='MpServer', x=-2359,00, y=69,00, z=-1347,50], EntityCreeper['Creeper'/37959, l='MpServer', x=-2364,50, y=69,00, z=-1349,50], EntityCreeper['Creeper'/37960, l='MpServer', x=-2367,50, y=69,00, z=-1348,50], EntitySkeleton['Skeleton'/38472, l='MpServer', x=-2479,50, y=72,00, z=-1368,50], EntityXPOrb['Experience Orb'/26953, l='MpServer', x=-2529,72, y=72,00, z=-1370,22], EntityCreeper['Creeper'/37961, l='MpServer', x=-2365,50, y=69,00, z=-1349,50], EntityXPOrb['Experience Orb'/26954, l='MpServer', x=-2529,50, y=72,00, z=-1369,66], EntityCreeper['Creeper'/37962, l='MpServer', x=-2365,50, y=69,00, z=-1346,50], EntityZombie['Zombie'/32337, l='MpServer', x=-2505,50, y=22,00, z=-1357,50], EntitySkeleton['Skeleton'/32340, l='MpServer', x=-2402,50, y=68,00, z=-1358,50], EntityAuraNode['Aura Node'/26454, l='MpServer', x=-2484,50, y=67,50, z=-1288,50], EntityRabbit['Rabbit'/351, l='MpServer', x=-2505,34, y=66,00, z=-1350,91], EntityRabbit['Rabbit'/352, l='MpServer', x=-2505,66, y=66,00, z=-1346,44], EntityAuraNode['Aura Node'/38503, l='MpServer', x=-2572,50, y=77,50, z=-1361,50], EntityRabbit['Rabbit'/364, l='MpServer', x=-2510,06, y=68,00, z=-1363,03], EntityXPOrb['Experience Orb'/16237, l='MpServer', x=-2546,22, y=76,00, z=-1385,88], EntityItem['item.tile.sapling.oak'/12653, l='MpServer', x=-2407,88, y=82,00, z=-1341,44], EntityXPOrb['Experience Orb'/16238, l='MpServer', x=-2548,38, y=76,00, z=-1385,03], EntityItem['item.tile.sapling.oak'/12654, l='MpServer', x=-2408,84, y=83,00, z=-1338,63], EntityXPOrb['Experience Orb'/16239, l='MpServer', x=-2545,47, y=76,00, z=-1385,38], EntityXPOrb['Experience Orb'/16240, l='MpServer', x=-2548,53, y=76,00, z=-1386,06], EntityAuraNode['Aura Node'/13170, l='MpServer', x=-2448,50, y=68,50, z=-1324,50], EntityCow['Cow'/13180, l='MpServer', x=-2451,50, y=79,00, z=-1368,47], EntityCow['Cow'/13181, l='MpServer', x=-2451,50, y=79,00, z=-1369,56], EntityRabbit['Rabbit'/13182, l='MpServer', x=-2454,50, y=80,00, z=-1374,50], EntityRabbit['Rabbit'/13183, l='MpServer', x=-2450,66, y=81,00, z=-1371,66], EntityRabbit['Rabbit'/13184, l='MpServer', x=-2451,66, y=83,00, z=-1374,66], EntityCow['Cow'/13185, l='MpServer', x=-2452,50, y=82,00, z=-1371,50], EntityAuraNode['Aura Node'/13186, l='MpServer', x=-2452,50, y=72,50, z=-1383,50], EntityItem['item.tile.sapling.oak'/21124, l='MpServer', x=-2440,16, y=76,00, z=-1325,19], EntityRabbit['Rabbit'/407, l='MpServer', x=-2498,34, y=66,00, z=-1348,69], EntityAuraNode['Aura Node'/26519, l='MpServer', x=-2422,50, y=73,50, z=-1278,50], EntityBat['Bat'/36010, l='MpServer', x=-2473,75, y=35,94, z=-1305,25], EntityBat['Bat'/36012, l='MpServer', x=-2470,03, y=31,00, z=-1308,42], EntityBat['Bat'/36013, l='MpServer', x=-2467,49, y=35,59, z=-1304,54], EntityBat['Bat'/36014, l='MpServer', x=-2474,96, y=31,42, z=-1309,23], EntityItem['item.tile.sapling.oak'/13746, l='MpServer', x=-2463,69, y=64,00, z=-1322,22], EntityRabbit['Rabbit'/13240, l='MpServer', x=-2421,44, y=67,00, z=-1372,41], EntityCow['Cow'/13244, l='MpServer', x=-2446,47, y=65,15, z=-1352,59], EntityItem['item.item.arrow'/27324, l='MpServer', x=-2467,78, y=69,00, z=-1405,88], EntityRabbit['Rabbit'/13245, l='MpServer', x=-2436,13, y=71,00, z=-1343,03], EntityRabbit['Rabbit'/13246, l='MpServer', x=-2436,72, y=71,00, z=-1343,78], EntityRabbit['Rabbit'/13247, l='MpServer', x=-2435,57, y=64,63, z=-1349,47], EntityItem['item.item.arrow'/32708, l='MpServer', x=-2411,91, y=67,00, z=-1386,22], EntityItem['item.item.bow'/32709, l='MpServer', x=-2412,75, y=66,00, z=-1387,75], EntityXPOrb['Experience Orb'/16074, l='MpServer', x=-2547,66, y=78,00, z=-1393,50], EntityXPOrb['Experience Orb'/26826, l='MpServer', x=-2531,75, y=74,00, z=-1374,78], EntityXPOrb['Experience Orb'/16075, l='MpServer', x=-2548,84, y=78,00, z=-1393,69], EntityXPOrb['Experience Orb'/16076, l='MpServer', x=-2551,16, y=78,00, z=-1395,44], EntityXPOrb['Experience Orb'/16077, l='MpServer', x=-2548,47, y=78,00, z=-1393,31], EntityXPOrb['Experience Orb'/27351, l='MpServer', x=-2465,28, y=68,00, z=-1412,16], EntityXPOrb['Experience Orb'/27352, l='MpServer', x=-2463,97, y=68,00, z=-1411,56], EntityAuraNode['Aura Node'/26589, l='MpServer', x=-2457,50, y=72,50, z=-1258,50], EntityXPOrb['Experience Orb'/27358, l='MpServer', x=-2514,75, y=72,00, z=-1392,44], EntityXPOrb['Experience Orb'/27359, l='MpServer', x=-2514,75, y=72,00, z=-1388,25], EntitySkeleton['Skeleton'/33505, l='MpServer', x=-2372,50, y=69,00, z=-1359,50], EntityAuraNode['Aura Node'/13282, l='MpServer', x=-2418,50, y=70,50, z=-1432,50], EntityZombie['Zombie'/29922, l='MpServer', x=-2374,50, y=70,00, z=-1392,50], EntityPlayerSP['Hyxaru'/230, l='MpServer', x=-2436,50, y=69,85, z=-1379,19], EntityHorse['Skeleton Horse'/234, l='MpServer', x=-2436,50, y=69,00, z=-1379,19], EntityXPOrb['Experience Orb'/37868, l='MpServer', x=-2423,03, y=67,00, z=-1384,09], EntityXPOrb['Experience Orb'/37869, l='MpServer', x=-2424,31, y=68,00, z=-1384,78], EntityZombie['Zombie'/33518, l='MpServer', x=-2455,50, y=65,00, z=-1316,50], EntityXPOrb['Experience Orb'/37870, l='MpServer', x=-2422,06, y=67,00, z=-1383,19], EntitySkeleton['Skeleton'/33519, l='MpServer', x=-2449,50, y=65,00, z=-1310,50], EntityItem['item.tile.sapling.oak'/20474, l='MpServer', x=-2441,34, y=62,00, z=-1325,13], EntityXPOrb['Experience Orb'/32765, l='MpServer', x=-2414,13, y=66,00, z=-1390,19], EntityXPOrb['Experience Orb'/32766, l='MpServer', x=-2412,16, y=67,00, z=-1386,97], EntityXPOrb['Experience Orb'/27135, l='MpServer', x=-2495,91, y=70,00, z=-1392,09]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 268199520 bytes (255 MB) / 1021571072 bytes (974 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP 9.19 Powered by Forge 11.15.1.1764 6 mods loaded, 6 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.1.1764.jar) 
    UCHIJAAAA   Forge{11.15.1.1764} [Minecraft Forge](forge-1.8.9-11.15.1.1764.jar) 
    UCHIJAAAA   Baubles{1.1.3.0} [Baubles](Baubles-1.8.9-1.1.3.0.jar) 
    UCHIJAAAA   Thaumcraft{5.2.4} [Thaumcraft](Thaumcraft-1.8.9-5.2.4.jar) 
    UCHIJAAAA   Botania{r1.8-299} [Botania](Botania-unofficial.r1.8-299.jar) 
    Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)

```
GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4229' Renderer: 'Intel(R) HD Graphics 3000'
Launched Version: 1.8.9-forge1.8.9-11.15.1.1764
LWJGL: 2.9.4
OpenGL: Intel(R) HD Graphics 3000 GL version 3.1.0 - Build 9.17.10.4229, Intel
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: alternate_textures_futureazoo.zip
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 4x Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz
```

**Comment by TheWhiteWolves** [comment]
In future, can you pastebin the log so it's not such a long post

**Comment by williewillus** [comment]
Can I have detailed step by step reproduction please?

**Comment by williewillus** [comment]
I don't see anything about botania in the log so I need detailed steps of what happened and how to reproduce before I can fix it :p

**Comment by Lashriel** [comment]
Seems to be a vanilla bug that's only exposed due to Botania being able to change Donkeys and Mules into Skeleton/Zombie Horses which can't have Chests attached to them.

If I'm right, I suggest just making the Viruses not work on Donkeys and Mules.

As for reproducible steps, this is what OP must have done:
1. Tame a Donkey and a Horse. Breed them to create a Mule.
2. Give the Mule a chest when it grows up.
3. Turn the Mule into a Skeleton Horse with the Nullodermal Virus.
4. Attempt to put an item into the Skeleton Horse's Chest inventory.

The game crashes because you're putting an item in a Chest inventory that internally can't exist (Horses can't have Chests attached to them, and there's no Donkey equivalent to the Skeleton Horse).

**Comment by yrsegal** [comment]
I haven't been able to get the Nullodermal or Necrodermal virus'd donkeys to make the mule inventory show up.

**Comment by Lashriel** [comment]
> I haven't been able to get the Nullodermal or Necrodermal virus'd donkeys to make the mule inventory show up.

And if you try a Mule (cross-breed a Donkey and a regular Horse)? OP seems to talk about a Mule that already had a chest prior to getting Nullodermal'd.

**Comment by williewillus** [comment]
Horses will now drop and remove their chest inventory on being virused
