### ISSUE TITLE
Rod of the Terra Firma doesn't work

### ISSUE THREAD

**Issue by liftoff** [williewillus/Botania#191]
Running FTB Unstable with this port of Botania 249 it appears that the Rod of the Terra Firma doesn't work.  Holding right click, it doesn't do it's usual thing of flattening out the vicinity with dirt.

I poked around to see if there was some mod conflict or config causing it but I can't find anything.

**Comment by williewillus** [comment]
What is the file name of the mod jar?

**Comment by liftoff** [comment]
The mods dir has it as: Botania.r1.8-248-unofficial-0.6.2.jar

...which is strange because in-game the Lexica Botania shows up as "249th edition" (I just opened up the instance to confirm).  I'll manually update the mod by hand and see if that fixes it.

**Comment by folyfy** [comment]
I'm having the same problem with a plain install of just botania 299 and baubles

**Comment by liftoff** [comment]
I just built the latest Baubles (1.8.9-1.1.3.0) and Botania (Botania-unofficial.r1.8-300.jar) from source and tried the Rod of the Terra Firma again.  It doesn't work.

Wish I knew more about how to debug it so I could give you more info other than, "it doesn't do anything."

**Comment by williewillus** [comment]
nah, that's enough information - thanks!
will be fixed sometime in the future (next week?) spring break just ended and I'm busy with school again =.=
