### ISSUE TITLE
Crash when opening the lexica botania (1.9)

### ISSUE THREAD

**Issue by luxor-g** [williewillus/Botania#192]
I was able to do the tutorial part, but after that it crashed and I cannot open it now.

http://pastebin.com/LTFZBHw2

**Comment by williewillus** [comment]
5ceceec

**Comment by yrsegal** [comment]
IT's BACK AND I DON'T KNOW WHY

**Comment by yrsegal** [comment]
willie, i don't think this is gone

**Comment by williewillus** [comment]
Exact steps to reproduce, you know that

**Comment by yrsegal** [comment]
same ones as before

open lexica/shift-hover tooltip on non-dev env, get the same crash

**Comment by williewillus** [comment]
fb0a414
