### ISSUE TITLE
Terrasteel helmet have too many attributes (1.9)

### ISSUE THREAD

**Issue by luxor-g** [williewillus/Botania#194]
This also happens with the revealing version.

![2016-03-31_22 03 32](https://cloud.githubusercontent.com/assets/7762387/14189530/16266d84-f78e-11e5-9710-4d36be0bf242.png)

**Comment by williewillus** [comment]
lol

**Comment by luxor-g** [comment]
Also I just noticed it happens with all terrasteel armor parts.

**Comment by williewillus** [comment]
5ceceec

**Comment by yrsegal** [comment]
oh wow my rebasing ANNIHILATED the logs on this issue

**Comment by williewillus** [comment]
heh I used the "Squash and merge" gh feature so that might've caused it

**Comment by yrsegal** [comment]
no, that was me. I rebased a lot.
