### ISSUE TITLE
Taking damage causes crashes

### ISSUE THREAD

**Issue by Melakion** [williewillus/Botania#196]
Botania 300 - Forge 1816

http://pastebin.com/sKB2zpCM

Wearing armor from ArmorPlus-1.7.4 https://github.com/sokratis12GR/ArmorPlus

**Comment by Melakion** [comment]
Creeper Explosions too. 

http://pastebin.com/EBXHZ2zQ

**Comment by williewillus** [comment]
It's all damage

**Comment by williewillus** [comment]
5ceceec
