### ISSUE TITLE
Mana Bursts are extremely rainbow

### ISSUE THREAD

**Issue by yrsegal** [williewillus/Botania#198]
![2016-04-02_13 25 57](https://cloud.githubusercontent.com/assets/6596492/14227968/8860452a-f8d6-11e5-81b5-18e5525a35a6.png)

that's a white lens. The color assignment system is weird, and doesn't quite work with the flashes either. It just colorizes the rainbow more.

**Comment by yrsegal** [comment]
update: this does NOT occur with all wisp particles.

**Comment by williewillus** [comment]
so just those made by bursts?

**Comment by yrsegal** [comment]
i've only looked at bursts and flashes.

**Comment by yrsegal** [comment]
Update: flare lens doesn't have this problem.
![2016-04-02_13 32 38](https://cloud.githubusercontent.com/assets/6596492/14227998/66629a94-f8d7-11e5-9467-c3bae897c618.png)

**Comment by yrsegal** [comment]
neither does the Signal Flare. 
![2016-04-02_13 39 42](https://cloud.githubusercontent.com/assets/6596492/14228038/6dcb4bf4-f8d8-11e5-9bc9-ef1bf073ccf2.png)

**Comment by yrsegal** [comment]
https://github.com/williewillus/Botania/blob/MC18/src/main/java/vazkii/botania/common/entity/EntityManaBurst.java#L545-L547
https://github.com/williewillus/Botania/blob/MC18/src/main/java/vazkii/botania/common/block/tile/TileManaFlame.java#L40-L42

cause of the problem?

**Comment by yrsegal** [comment]
suggested solution: have a single random value used, so that it gets darker/lighter and looks nice. Not so it is random colors.

**Comment by williewillus** [comment]
does it happen in 1.8 or just in 1.9?

**Comment by yrsegal** [comment]
let me check. I'll also check 1.7, for comparison. I don't actually have any instances with botania 1.8 at the moment .-.

**Comment by yrsegal** [comment]
in 1.7 it does not happen.

**Comment by yrsegal** [comment]
hm... https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/entity/EntityManaBurst.java#L550-L552

**Comment by yrsegal** [comment]
well I murdered the logs here too
