### ISSUE TITLE
JEI relic duplication

### ISSUE THREAD

**Issue by TheWhiteWolves** [williewillus/Botania#20]
First of all, good work on the porting, just got round to taking a look at it myself but so far looking good. :thumbsup:

Now onto the first thing i found, which may be caused by something on JEI's side but may be because of how we do stuff with the relics.

I'll also start with an apology for the long report.

If you give yourself one of the relics through JEI (looks to be any of them) it will give you one and throw one out onto the floor which can not be picked up but does fall if you remove the blocks from under it.

If you look at the screenshots below, the first shows it happening with the Key of Kings Law (notice one in my hotbar and one on the ground.
The second and third show the Apple of Grisaia and that I also have a brew which did not duplicate.
The forth shows the Key of Kings Law having fallen a block when I remove the grass blocks below it.
The fifth is the same actions replicated in Creative mode (to ensure it is not bound to a single gamemode)
The sixth shows that it is not to do with the achievement triggering as it happens to the same item being given multiple times.

Also to note between screens 3, 4 and 5 I closed the game and restarted it to check it wasn't just a visual glitch.

![2016-01-08_00 20 57](https://cloud.githubusercontent.com/assets/1471503/12186783/e4fae6e0-b59d-11e5-918d-d728e7b88cd8.png)
![2016-01-08_00 21 31](https://cloud.githubusercontent.com/assets/1471503/12186785/e4fcc6c2-b59d-11e5-890e-66b13a150b7d.png)
![2016-01-08_00 21 37](https://cloud.githubusercontent.com/assets/1471503/12186784/e4fbd820-b59d-11e5-9334-8948d3435702.png)
![2016-01-08_00 22 54](https://cloud.githubusercontent.com/assets/1471503/12186876/a1bc6bf0-b59e-11e5-8030-fbfe958b9b8c.png)
![2016-01-08_00 38 30](https://cloud.githubusercontent.com/assets/1471503/12187046/369ca22a-b5a0-11e5-8908-734da809662d.png)
![2016-01-08_00 40 56_2](https://cloud.githubusercontent.com/assets/1471503/12187076/8d601aa6-b5a0-11e5-85e4-e587c9f6960b.png)

---

Instance:
minecraft-1.8.9
forge-11.15.0.1688

Mods:
Baubles-1.8.9-1.1.3.0
Botania-r1.8-247-MC1.8-2ddf71d
jei_1.8.9-2.14.0.67

Steps to Replicate:
1. Create a new world
2. Ensure JEI has Item Cheating set to true.
3. Give yourself a relic through JEI. (this will give you one and throw one on the ground infront of you)

**Comment by williewillus** [comment]
Yup, this is actually a forge + vanilla bug  with the /give command that JEI uses, mezz is gonna pr a patch to forge to fix it.

I'll leave this open in the meantime until it gets merged

**Comment by TheWhiteWolves** [comment]
ahh kl, next thing I was gonna check when I got home from work tonight was whether it happened with the standard /give command.
Threw the report together at about half past midnight before i headed to bed so didn't get a chance to check that.

**Comment by williewillus** [comment]
should be fixed in forge build 1690 or above
