### ISSUE TITLE
Tiara Particles spawn at incorrect position

### ISSUE THREAD

**Issue by TheWhiteWolves** [williewillus/Botania#21]
Number 2, here we go :stuck_out_tongue_closed_eyes:

The particle spawned by the tiaras are off by what looks to be about 2 blocks.

In the screenshots my character is positioned at the height where he would be stood on the top block of the tree and the particles are 2 blocks below that when they should be spawning at the players feet.

Looking [here](https://github.com/williewillus/Botania/blob/MC18/src/main/java/vazkii/botania/common/item/equipment/bauble/ItemFlightTiara.java#L226) my initial guess would be that 1.8 has switched the entityLiving.posY to be the players feet position and not the head position, thus offsetting the Y position.

![2016-01-08_22 01 04](https://cloud.githubusercontent.com/assets/1471503/12210680/adae1f02-b653-11e5-81bb-4e9f6dd0df4e.png)
![2016-01-08_22 03 09](https://cloud.githubusercontent.com/assets/1471503/12210679/adac3e30-b653-11e5-864f-1f0299f697ae.png)

---

Instance:
minecraft-1.8.9
forge-11.15.0.1688

Mods:
Baubles-1.8.9-1.1.3.0
Botania.r1.8-248-MC1.8-a1aa50b
jei_1.8.9-2.14.0.67

Steps to Replicate:
1. Create a new world
2. Ensure JEI has Item Cheating set to true.
3. Give yourself a tiara (any is fine, I used Sylph and Ice Fairy).
4. Move around in third person view.

**Comment by williewillus** [comment]
You'd be correct!
