### ISSUE TITLE
EntityTippedArrow interaction with PixieHandler (1.9)

### ISSUE THREAD

**Issue by pjfranke** [williewillus/Botania#214]
I'm confused by this, I had only started into Botania progression, and at this point had only some Botania flowers in my inventory...no baubles, Botania armor, tools, etc.

I went to kill a skeleton, and something about the arrow he shot at me seems to be interacting with the PixieHandler?  Which is strange, as I'm nowhere near Elementium armor to spawn Pixies from.

This was the second crash after re-launching and re-entering the save, and either the initial arrow moving again, or a second arrow being shot.

http://pastebin.com/Xg2hdLyW

**Comment by yrsegal** [comment]
I fixed this, fix hasn't been released yet.

**Comment by williewillus** [comment]
yup, new build probably coming out tomorrow
