### ISSUE TITLE
Dyes from vanilla flowers, that are not from poppies and dandelions, don't count for a flower origened dye to make floral fertilizer

### ISSUE THREAD

**Issue by Hyxaru** [williewillus/Botania#215]

**Comment by yrsegal** [comment]
They can't be distinguished from the artificial ones.

**Comment by williewillus** [comment]
@yrsegal can you reword the bug report so I can understand it xD

**Comment by yrsegal** [comment]
@williewillus haha, sure.

The dyes produced by vanilla flowers such as the Azure Bluet (crafts to Light Gray dye) cannot be used to create Floral Fertilizer (an artefact from Botania's 1.6 origins). 

Adding Light Gray and similar to the recipe is problematic flavor-wise, as these dyes can be manufactured from means that don't necessarily include flowers (bone meal \* 2 + ink sac -> light gray dye).

A possible solution is allowing the crushing of flowers that can be crafted into dye into that much Floral Powder of their color. (I can write the recipe handler for that if you want.)
