### ISSUE TITLE
Mana Pool and Terrasteel Plate despawn items within 5 seconds

### ISSUE THREAD

**Issue by remyxomatosis** [williewillus/Botania#217]
I am playing Infinity Evolved (latest version), without any modifications. Also using faithfull 32 texture pack.

Trying to advance through botania I set up a Terrasteel plate in the required pattern. I have a spark on a mana pool and the plate, and if I toss the required three items on the plate, they will despawn after about 5 seconds. The weird part is that the blueish halo starts to form, like it is working, and then the items are gone.
A similar behavior can be found with mana pools and tablets. Upon tossing a tablet into a full pool to transfer mana, the charging animation (blue lightning) starts, and again, five seconds later the tablet despawns.

I used to be able to charge tablets in the same world before I tried to make Terrasteel...

**Comment by yrsegal** [comment]
Do you have a hopperhock nearby?

**Comment by remyxomatosis** [comment]
no, there is a Jaded Amaranthus close by, however that is the only functional flower I have. Also no hoppers, or other importing mechanisms near by. The items are despawning from the world. 
In close proximity there is also a 3x3 field with Endoflames and two manna spreaders.

**Comment by yrsegal** [comment]
sure you don't have a hopperhock within 16 blocks or so? because that's the only thing that could cause this effect in botania. If that's not the case, it's not botania's fault. if it is the case, it's your fault.

**Comment by yrsegal** [comment]
What's the status on this issue @williewillus?

**Comment by williewillus** [comment]
Not enough info

**Comment by williewillus** [comment]
Cannot reproduce at all, check that
1. You don't have a hopperhock nearby
2. You don't have an endoflame nearby
3. If you're on a server, that there isn't some plugin clearing dropped items
