### ISSUE TITLE
Mana bar renderers don't respect latest forge tooltip resizer

### ISSUE THREAD

**Issue by yrsegal** [williewillus/Botania#219]
Namely, the Terra shatterer / mana storage bars above items.

<img width="1233" alt="screen shot 2016-04-06 at 1 24 56 pm" src="https://cloud.githubusercontent.com/assets/6596492/14327070/c55b0174-fbfe-11e5-8564-87e96a5cbf48.png">

**Comment by yrsegal** [comment]
Same with lexica botania inv-lookup, by the way.

**Comment by williewillus** [comment]
I'm not really sure how to solve this without reimplementing half of the tooltip resizer

**Comment by GirafiStudios** [comment]
Talking to Mezz about it might be a good idea, since he's the one which made the resizer :)

**Comment by williewillus** [comment]
Yeah I know where it's done (in GuiUtils) but trying to find a way that wouldn't involve copying half that class (ping @mezz?)

**Comment by mezz** [comment]
Not sure. How were you doing it before?

**Comment by mezz** [comment]
The tooltips aren't written with this in mind at all. You're probably best off copying the logic. Keep in mind that guis can override `drawHoveringText` with their own. Also many mods have their own tooltip render methods (Logistics Pipes comes to mind) but hopefully everyone can unify under the `GuiUtils` one now that it's accessible to everything.
