### ISSUE TITLE
[1.9] Harvesting endoflame causes crash

### ISSUE THREAD

**Issue by ThuCommix** [williewillus/Botania#221]
Stacktrace here you go:

vazkii.botania.common.block.tile.mana.TileSpreader cannot be cast to vazkii.botania.common.block.tile.TileSpecialFlower
    at vazkii.botania.common.block.BlockSpecialFlower.getLightValue(BlockSpecialFlower.java:175)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.getLightValue(BlockStateContainer.java:450)

**Comment by yrsegal** [comment]
can't reproduce.

**Comment by ThuCommix** [comment]
Directly behind is a mana spreader, could this be an potential issue? I'll supply screenshots later today.

**Comment by williewillus** [comment]
this is possible a forge bug, need to investigate

**Comment by yrsegal** [comment]
This isn't a botania issue, i can say that definitively after placing and breaking endoflames near spreaders about 25 times.

**Comment by williewillus** [comment]
it only happens in survival

**Comment by yrsegal** [comment]
allow me to try in that AND adventure, then

**Comment by yrsegal** [comment]
welp, you're right!

**Comment by williewillus** [comment]
Forge bug ticket: https://github.com/MinecraftForge/MinecraftForge/issues/2773
