### ISSUE TITLE
craft band of mana uncomfortable

### ISSUE THREAD

**Issue by TaKaQod** [williewillus/Botania#225]
I'm running botania on r1.8-238 and i'm knowing this is not the latest version but i'm on a modpack and i don't want to update.
It seems that this was not be change since this issue #691.
So i was trying to craft the band of mana with a mana tablet slightly fill-up and i had to empty it to get working the crafting recipe.
it would be handy if stored items could be craftable without this trick and with the maintain of mana of course ;).
Thanks for this great mod!

**Comment by yrsegal** [comment]
this is closed by https://github.com/williewillus/Botania/pull/218

**Comment by TaKaQod** [comment]
I did not re check on this repo before posting but it's the same issue yep.

**Comment by yrsegal** [comment]
i mean, that PR was designed to fix this issue :P

**Comment by yrsegal** [comment]
Any update on #218's status re this? @williewillus
