### ISSUE TITLE
{1.8} Rod of the Terra firma, does it work or is it broken?

### ISSUE THREAD

**Issue by Hyxaru** [williewillus/Botania#226]
I for instance, cannot seem to get this rod to work. 
I am above see level
Stand next to a dirt hill
Have mana, hold right click with the rod for a while
Sometimes I hear the rod make the right sound and particles, but no actual dirt is moved. Can anyone else replicate this or am I doing something wrong/unlucky?

**Comment by yrsegal** [comment]
it'l work once my PR is pushed into master. Please close this issue, as it's identical to #191
