### ISSUE TITLE
Forced mana state doesn't work

### ISSUE THREAD

**Issue by yrsegal** [williewillus/Botania#228]
For RenderTilePool

In the lexicon, the pool looks empty, and a pool near you looks filled with mana.

**Comment by williewillus** [comment]
That's unneeded now and will be removed, vanilla's rendering methods and models work just fine

**Comment by yrsegal** [comment]
But what about rendering the mana pool in the lexicon?

**Comment by williewillus** [comment]
It uses the standard itemstack render

**Comment by yrsegal** [comment]
but it's supposed to look filled...

**Comment by yrsegal** [comment]
A possible solution, add an NBT tag to the Mana Pool item that makes the liquid mana render inside the item.

**Comment by williewillus** [comment]
Which entries?

**Comment by yrsegal** [comment]
Any lexicon entry/jei entry for a mana pool should look filled. That was 1.7 behavior. (this issue should be reopened, due to this)

**Comment by williewillus** [comment]
Okay, but I recall their being no usages for that variable. Will investigate

**Comment by yrsegal** [comment]
it's used in the lexicon page only, at the moment. It used to be used in the NEI recipe handler.

**Comment by yrsegal** [comment]
all this would require is a model override based on an NBT tag, right?

**Comment by yrsegal** [comment]
Are you doing this? If not, I can work on getting the override to work

**Comment by williewillus** [comment]
I will, yes.

**Comment by yrsegal** [comment]
What about the JEI recipe handler?

**Comment by williewillus** [comment]
woops, done
