### ISSUE TITLE
Headpiece rendering awkwardly

### ISSUE THREAD

**Issue by Darkhax** [williewillus/Botania#23]
The armor models for the custom armor render a bit awkwardly when placed on things like armor stands. In all of my tests, this only effected the helmets. All helmets regardless of armor stand direction seem to point south. 

![2016-01-08_18 21 17](https://cloud.githubusercontent.com/assets/2250798/12213441/4b3a2000-b635-11e5-8aa7-a782fb12b8c2.png)

**Comment by williewillus** [comment]
I have no idea about this one 0.o

It renders fine on players, and on zombies and skeletons that can pick up loot, so not sure why armor stands act weird.

**Comment by Darkhax** [comment]
Yeah, it's definitely a weird issue. I noticed it in one of my test mods, and found that the issue also exists here. I am not sure how to fix it myself ':p

**Comment by williewillus** [comment]
wait, I think this is a vanilla thing.
Activate F3+b and a blue line should come out of the armor stand showing where it's pointing

**Comment by Darkhax** [comment]
You're right, they do seem to be looking south. The rendering for vanilla armor sets must have some special code for them to correct the rendering, because they work as one might expect.

**Comment by TheWhiteWolves** [comment]
looks like all entities initially point south, if you put down some sparks they are facing south aswell

**Comment by Darkhax** [comment]
South is the default rotation for almost everything in the game, so it's not that surprising that it would point south unless it is told otherwise by some internal logic.

**Comment by williewillus** [comment]
but I wonder why vanilla helmets don't have this issue (or do they?) maybe it's updated when a player puts a helmet on them

**Comment by TheWhiteWolves** [comment]
Most likely they change the rotation when the helmet is placed onto the armour stand

**Comment by Darkhax** [comment]
I have compared it against vanilla helms, they don't have this issue.

**Comment by williewillus** [comment]
This is probably a forge "new feature in vanilla" issue if it happens to your armors too, vanilla has all sorts of specialcasing around the armor stands (-.-)

**Comment by Darkhax** [comment]
I just did a test of my armor without the special model and other rendering changes, it seems this happens with default armor as well. That is unfortunate.

**Comment by TheWhiteWolves** [comment]
Looks like vanilla definitely does some rotation on the render.

![2016-01-09_12 05 40](https://cloud.githubusercontent.com/assets/1471503/12215940/6f3f91b2-b6c9-11e5-8455-6575aa2edb7c.png)

**Comment by Darkhax** [comment]
I did some tests with Thaumcraft and found that the thaumcraft armor is not affected by this issue.

**Comment by Darkhax** [comment]
I might have a look at this later on, and create a PR. I have some ideas after looking through Thaumcraft.

**Comment by Hyxaru** [comment]
The chestplate armor has its arms wiggling slightly as if it was equiped by a player instead of an motionless armorstand

**Comment by williewillus** [comment]
Pinging this to let everyone know I found a workaround, check the forge ticket above (MinecraftForge/MinecraftForge#2508) for more info
