### ISSUE TITLE
No petite dreadthorne

### ISSUE THREAD

**Issue by tsurezuregusa** [williewillus/Botania#230]
I'm running build 299 on 1.8.9, and I can't find a petite version of the dreadthorne. Dropping it in a mana pool does nothing. It seems there was one in 1.7, was it removed on purpose?

In JEI there are agricarnation, bellethorne, bubbell, clayconia, hopperhock, marimorphosis, rannuncarpus and solegnolia, but no dreadthorne.

**Comment by TheWhiteWolves** [comment]
its because it doesn't have a mini version declared, never did.

willie would need to add this, its relevant other declaration pieces and a texture to create one.

``` Java
public static class Mini extends SubTileDreadthorn {
    @Override public int getRange() { return RANGE_MINI; }
}
```
