### ISSUE TITLE
Move mana into capabilities

### ISSUE THREAD

**Issue by SoniEx2** [williewillus/Botania#231]
This makes it sided. Which I need. It's better than the "retrieve burst entity and do math on it" hack.

**Comment by williewillus** [comment]
This will be done eventually, yes

**Comment by SoniEx2** [comment]
Will this still be done even with the current @Vazkii? The current @Vazkii seems to hate the idea of sided mana receivers...

Can you upgrade/fix the current @Vazkii?

**Comment by williewillus** [comment]
This probably won't get done as there is little benefit to do so
