### ISSUE TITLE
IC2 Blocks with Weight Lens

### ISSUE THREAD

**Issue by murapix** [williewillus/Botania#233]
I tried to make a Orechid setup that would drops ores using the Weight lens onto torches so that all ores would be processed correctly, and found that the IC2 ores (and from further testing, the normal blocks too) all changed their metadata to 0 when they hit the torches. Testing this interaction with Vanilla blocks and blocks from other mods revealed that it seems to just be IC2 with this problem. I have already sent a bug report to the IC2 team, but maybe something can be done on Botania's side too.

Tested using IC2 2.3.173-ex18 and Botania r1.8-299

**Comment by yrsegal** [comment]
Are IC2 ores TileEntities?

**Comment by williewillus** [comment]
it might be a problem with how falling sand entity converts itself into an item, lemme see

**Comment by williewillus** [comment]
update: it uses damageDropped to get the meta, so idk how IC2 distinguishes its ores but this might be a vanilla limitation and/or on ic2's end

**Comment by yrsegal** [comment]
if IC2 ores are TEs then the fallingsand method won't work for them.

**Comment by murapix** [comment]
Took a quick look through IC2's code, and the ores are instances of BlockMultiID, which uses the enum ResourceBlock to determine the type, and extends BlockBase extends Block. I'm assuming its the way they set the variants (using ResourceBlock instead of just plain metadata) that's causing the issue.

**Comment by williewillus** [comment]
do they implement damagedroped?

**Comment by murapix** [comment]
Doesn't look like it, just getDrops.

**Comment by williewillus** [comment]
Yeah vanilla's falling sand uses damageDropped and weight lens just turns it into a falling sand  entity, so it's on ic2's side

**Comment by murapix** [comment]
Yeah I already sent in a bug report to the IC2 people, but who knows how long it'll be before that gets any attention.
