### ISSUE TITLE
Livingwood bow won't shoot in survival. Botania version 1.8-301

### ISSUE THREAD

**Issue by calebm02** [williewillus/Botania#238]
Tried to make a livingwood bow & enchanted it with some good enchants, turns out it won't load the arrow. I tried both the enchanted and the unenchanted, they didn't work in survival, however they both worked in creative. FML Log https://gist.github.com/calebm02/1171100cf1ba5332f4c044904357368e

**Comment by TheIcyOne** [comment]
Can't remember offhand, but I think it requires mana in your inventory to fire.

**Comment by williewillus** [comment]
Crystal bow needs mana wood one doesn't.
