### ISSUE TITLE
Tall flowers only give item when top block sheared

### ISSUE THREAD

**Issue by TheWhiteWolves** [williewillus/Botania#24]
When shearing a tall mystical flower it will only return an item when the top block is sheared (see the gif below)

![tall mystical flowers bug](https://cloud.githubusercontent.com/assets/1471503/12213756/36ecebaa-b676-11e5-971e-644cc8085303.gif)

---

Instance:
minecraft-1.8.9
forge-11.15.0.1688

Mods:
Baubles-1.8.9-1.1.3.0
Botania.r1.8-248-MC1.8-a1aa50b
jei_1.8.9-2.14.0.67
modnametooltip_1.8.8-1.0.0

**Comment by GirafiStudios** [comment]
Can you reproduce this in 1.7.10? :)

**Comment by TheWhiteWolves** [comment]
No, because we already tested it when we were coding 1.7 and just to ensure we didn't introduce it in a recent version i just double checked that its not an existing bug

**Comment by GirafiStudios** [comment]
Okay ^^ Shouldn't be too hard to fix tho :p
