### ISSUE TITLE
Gaia items aren't colorized

### ISSUE THREAD

**Issue by yrsegal** [williewillus/Botania#240]

**Comment by williewillus** [comment]
You mean the tooltips? Deets pls :P

**Comment by yrsegal** [comment]
no, I mean the items. They're... uh... just white.

**Comment by yrsegal** [comment]
they aren't the soft rainbow that they normally are.

**Comment by williewillus** [comment]
Ah those, missed them when redoing colors, noted.

**Comment by williewillus** [comment]
This is just the spirit and spirit ingot right?

**Comment by yrsegal** [comment]
yeah.

**Comment by yrsegal** [comment]
and, in theory, anything else that's colorized in the manaResource, but i can't think of any examples.
