### ISSUE TITLE
Some cosmetic baubles extremely out of correct location

### ISSUE THREAD

**Issue by yrsegal** [williewillus/Botania#243]
![2016-04-18_00 36 48](https://cloud.githubusercontent.com/assets/6596492/14593864/d449fd0e-04fd-11e6-94ac-f45bc7382177.png)

**Comment by yrsegal** [comment]
most of them, actually

**Comment by williewillus** [comment]
Aware
It's just an extreme, extreme, extreme pain in the ass to redo them again (after I just redid them all for 1.8 >.>) so I've been putting it off
I'll get to it sometime, or maybe someone will before me :p

**Comment by yrsegal** [comment]
it looks like it should just be a rotation, right?

**Comment by williewillus** [comment]
they all have their own positioning so even if I did math it and calculate the new values for everything (the matrix switched from XYZ to YXZ or something) I'd still have to replace them all manually
Fun :P it'll happen somewhat soon

**Comment by williewillus** [comment]
#49
