### ISSUE TITLE
Potions don't have a backing in the HUD

### ISSUE THREAD

**Issue by yrsegal** [williewillus/Botania#245]
![untitled-1](https://cloud.githubusercontent.com/assets/6596492/14610187/d40b6e56-055a-11e6-91fc-6b95efd649a0.png)

**Comment by yrsegal** [comment]
This is easy to fix, by the way. Just copy the part between the potions and survival inventory in the vanilla texture into Botania's potions at the same location.

**Comment by williewillus** [comment]
yeah but that's the short term solution
It's a forge issue so I opened a ticket for it

**Comment by yrsegal** [comment]
i kind of like it... you can give your potions custom backings.
