### ISSUE TITLE
(1.9) Crash upon opening inventory, creative. Baubles inventory works fine.

### ISSUE THREAD

**Issue by Hyxaru** [williewillus/Botania#246]
I know someone said to me last time I shouldn't post an entire crash log here. Excuse me for that, I don't know how to hide it a bit more (on mc forums there are spoiler tags but I cannot find something alike on github)

Anyway, latest botania, baubles and forge 1.9-forge1.9-12.16.0.1865-1.9

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 18-4-16 20:02
Description: Unexpected error

java.lang.IllegalAccessError: tried to access field net.minecraft.client.gui.inventory.GuiContainer.field_147003_i from class baubles.client.gui.GuiEvents
    at baubles.client.gui.GuiEvents.guiPostInit(GuiEvents.java:22)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_58_GuiEvents_guiPostInit_Post.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:489)
    at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:958)
    at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2097)
    at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1955)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1743)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at baubles.client.gui.GuiEvents.guiPostInit(GuiEvents.java:22)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_58_GuiEvents_guiPostInit_Post.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:489)
    at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:958)
    at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2097)
    at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1955)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['Hyxaru'/415, l='MpServer', x=-15,52, y=80,38, z=201,50]]
    Chunk stats: MultiplayerChunkCache: 371, 371
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (64,64,252), Chunk: (at 0,4,12 in 4,15; contains blocks 64,0,240 to 79,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 1486 game time, 1486 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 132 total; [EntityZombie['Zombie'/263, l='MpServer', x=52,49, y=21,07, z=123,09], EntityBat['Bat'/265, l='MpServer', x=46,03, y=60,23, z=131,79], EntityChicken['Chicken'/266, l='MpServer', x=50,50, y=76,00, z=161,50], EntitySkeleton['Skeleton'/267, l='MpServer', x=57,50, y=32,00, z=181,50], EntityChicken['Chicken'/269, l='MpServer', x=51,48, y=73,00, z=230,85], EntityChicken['Chicken'/270, l='MpServer', x=50,13, y=72,00, z=232,48], EntityChicken['Chicken'/271, l='MpServer', x=48,39, y=69,00, z=231,79], EntityChicken['Chicken'/272, l='MpServer', x=51,16, y=69,00, z=243,52], EntityZombie['Zombie'/273, l='MpServer', x=63,50, y=30,00, z=272,50], EntityCreeper['Creeper'/274, l='MpServer', x=60,50, y=30,00, z=272,50], EntitySkeleton['Skeleton'/25, l='MpServer', x=-88,50, y=26,00, z=184,50], EntityCreeper['Creeper'/26, l='MpServer', x=-91,50, y=22,00, z=181,50], EntityZombie['Zombie'/27, l='MpServer', x=-89,15, y=26,00, z=193,50], EntityCreeper['Creeper'/28, l='MpServer', x=-82,54, y=47,95, z=206,34], EntityZombie['Zombie'/29, l='MpServer', x=-83,50, y=48,00, z=207,50], EntityZombie['Zombie'/30, l='MpServer', x=-92,50, y=46,00, z=211,50], EntitySkeleton['Skeleton'/31, l='MpServer', x=-93,50, y=39,00, z=275,50], EntityChicken['Chicken'/46, l='MpServer', x=-72,18, y=70,00, z=154,91], EntityEnderman['Enderman'/47, l='MpServer', x=-72,51, y=20,00, z=166,63], EntityChicken['Chicken'/48, l='MpServer', x=-66,50, y=69,00, z=164,50], EntityChicken['Chicken'/49, l='MpServer', x=-64,20, y=69,00, z=161,20], EntityZombie['Zombie'/50, l='MpServer', x=-75,50, y=24,00, z=207,50], EntityChicken['Chicken'/51, l='MpServer', x=-72,50, y=70,00, z=204,50], EntityChicken['Chicken'/52, l='MpServer', x=-74,50, y=71,00, z=204,50], EntityChicken['Chicken'/53, l='MpServer', x=-75,50, y=71,00, z=203,50], EntityChicken['Chicken'/54, l='MpServer', x=-75,50, y=71,00, z=204,50], EntityItem['item.item.feather'/566, l='MpServer', x=47,83, y=69,00, z=232,23], EntityItem['item.item.feather'/55, l='MpServer', x=-72,88, y=70,00, z=204,13], EntitySkeleton['Skeleton'/56, l='MpServer', x=-69,27, y=26,00, z=214,50], EntityChicken['Chicken'/70, l='MpServer', x=-58,76, y=70,00, z=164,50], EntityItem['item.item.seeds'/71, l='MpServer', x=-58,53, y=70,00, z=161,41], EntityCreeper['Creeper'/82, l='MpServer', x=-32,50, y=39,00, z=126,50], EntityChicken['Chicken'/83, l='MpServer', x=-36,17, y=67,00, z=125,50], EntityBat['Bat'/84, l='MpServer', x=-41,02, y=42,09, z=133,61], EntityZombie['Zombie'/85, l='MpServer', x=-37,25, y=16,00, z=156,52], EntityItem['item.tile.gravel'/86, l='MpServer', x=-43,81, y=15,00, z=165,88], EntityItem['item.tile.gravel'/87, l='MpServer', x=-42,85, y=15,00, z=165,74], EntityCreeper['Creeper'/88, l='MpServer', x=-46,68, y=14,00, z=170,45], EntitySkeleton['Skeleton'/89, l='MpServer', x=-35,50, y=21,00, z=227,50], EntityChicken['Chicken'/90, l='MpServer', x=-34,50, y=63,00, z=268,50], EntityChicken['Chicken'/91, l='MpServer', x=-36,50, y=64,00, z=267,50], EntityWolf['Wolf'/92, l='MpServer', x=-33,50, y=64,00, z=276,50], EntityWolf['Wolf'/93, l='MpServer', x=-33,50, y=64,00, z=276,50], EntityWolf['Wolf'/94, l='MpServer', x=-43,31, y=64,00, z=277,36], EntityWolf['Wolf'/95, l='MpServer', x=-35,50, y=64,00, z=273,50], EntityChicken['Chicken'/96, l='MpServer', x=-35,83, y=65,00, z=279,79], EntityChicken['Chicken'/97, l='MpServer', x=-33,50, y=64,00, z=279,50], EntityChicken['Chicken'/99, l='MpServer', x=-42,18, y=64,00, z=277,73], EntityChicken['Chicken'/116, l='MpServer', x=-22,63, y=65,00, z=127,13], EntityChicken['Chicken'/117, l='MpServer', x=-29,50, y=66,00, z=123,50], EntityChicken['Chicken'/118, l='MpServer', x=-28,50, y=66,00, z=126,50], EntitySkeleton['Skeleton'/119, l='MpServer', x=-27,50, y=20,00, z=162,50], EntitySkeleton['Skeleton'/120, l='MpServer', x=-23,50, y=60,00, z=182,50], EntityCreeper['Creeper'/121, l='MpServer', x=-20,50, y=29,00, z=203,50], EntityCreeper['Creeper'/122, l='MpServer', x=-18,50, y=32,00, z=199,50], EntitySkeleton['Skeleton'/123, l='MpServer', x=-22,50, y=32,00, z=204,50], EntityChicken['Chicken'/124, l='MpServer', x=-27,77, y=65,00, z=206,52], EntityChicken['Chicken'/125, l='MpServer', x=-25,71, y=67,00, z=212,57], EntityChicken['Chicken'/126, l='MpServer', x=-22,87, y=67,00, z=254,51], EntityChicken['Chicken'/127, l='MpServer', x=-24,69, y=71,00, z=252,37], EntityChicken['Chicken'/128, l='MpServer', x=-25,16, y=71,00, z=252,67], EntityChicken['Chicken'/129, l='MpServer', x=-25,78, y=63,00, z=260,90], EntityChicken['Chicken'/130, l='MpServer', x=-27,71, y=63,00, z=269,11], EntityChicken['Chicken'/131, l='MpServer', x=-18,43, y=68,00, z=257,80], EntitySkeleton['Skeleton'/132, l='MpServer', x=-21,50, y=39,00, z=277,50], EntityChicken['Chicken'/142, l='MpServer', x=-10,83, y=69,01, z=207,72], EntityChicken['Chicken'/143, l='MpServer', x=-0,85, y=65,00, z=209,50], EntityCreeper['Creeper'/144, l='MpServer', x=-10,50, y=27,00, z=239,50], EntitySkeleton['Skeleton'/145, l='MpServer', x=-14,50, y=29,00, z=245,50], EntityCreeper['Creeper'/146, l='MpServer', x=-9,50, y=34,00, z=253,50], EntityCreeper['Creeper'/154, l='MpServer', x=14,50, y=56,00, z=164,50], EntityItem['item.tile.mushroom1'/155, l='MpServer', x=6,60, y=15,00, z=192,19], EntityItem['item.tile.mushroom4'/156, l='MpServer', x=11,77, y=14,00, z=253,88], EntityItem['item.tile.mushroom4'/157, l='MpServer', x=15,88, y=14,00, z=251,88], EntitySkeleton['Skeleton'/158, l='MpServer', x=11,50, y=25,00, z=248,50], EntityBat['Bat'/159, l='MpServer', x=12,57, y=18,25, z=246,82], EntityChicken['Chicken'/160, l='MpServer', x=11,82, y=70,00, z=244,47], EntityBat['Bat'/161, l='MpServer', x=11,88, y=23,35, z=259,10], EntityBat['Bat'/162, l='MpServer', x=13,40, y=14,92, z=272,42], EntityBat['Bat'/163, l='MpServer', x=11,33, y=53,22, z=266,95], EntitySkeleton['Skeleton'/164, l='MpServer', x=12,50, y=36,00, z=281,50], EntityPlayerSP['Hyxaru'/415, l='MpServer', x=-15,52, y=80,38, z=201,50], EntityChicken['Chicken'/182, l='MpServer', x=26,50, y=63,00, z=135,50], EntityChicken['Chicken'/183, l='MpServer', x=21,99, y=64,01, z=135,49], EntityChicken['Chicken'/184, l='MpServer', x=31,15, y=63,00, z=132,46], EntitySkeleton['Skeleton'/185, l='MpServer', x=25,50, y=57,00, z=137,50], EntitySkeleton['Skeleton'/442, l='MpServer', x=-90,50, y=45,00, z=207,50], EntityChicken['Chicken'/186, l='MpServer', x=30,17, y=64,00, z=141,50], EntityCow['Cow'/187, l='MpServer', x=26,50, y=75,00, z=150,79], EntityCow['Cow'/188, l='MpServer', x=24,50, y=71,00, z=156,50], EntityCow['Cow'/189, l='MpServer', x=25,50, y=75,00, z=149,79], EntityCow['Cow'/190, l='MpServer', x=25,31, y=73,00, z=157,30], EntityZombie['Zombie'/191, l='MpServer', x=26,35, y=64,00, z=153,35], EntityChicken['Chicken'/192, l='MpServer', x=25,54, y=72,00, z=173,83], EntitySpider['Spider'/193, l='MpServer', x=21,78, y=19,00, z=181,33], EntitySkeleton['Skeleton'/194, l='MpServer', x=30,50, y=18,00, z=185,50], EntityZombie['Zombie'/195, l='MpServer', x=18,50, y=18,00, z=193,50], EntityChicken['Chicken'/196, l='MpServer', x=30,45, y=63,00, z=210,87], EntityChicken['Chicken'/197, l='MpServer', x=29,50, y=63,00, z=220,50], EntityChicken['Chicken'/198, l='MpServer', x=18,91, y=64,00, z=218,70], EntitySkeleton['Skeleton'/199, l='MpServer', x=18,50, y=25,00, z=234,50], EntityBat['Bat'/200, l='MpServer', x=15,90, y=21,14, z=242,56], EntityCreeper['Creeper'/201, l='MpServer', x=21,83, y=46,00, z=224,50], EntityChicken['Chicken'/202, l='MpServer', x=19,78, y=67,00, z=225,51], EntitySkeleton['Skeleton'/203, l='MpServer', x=17,48, y=25,00, z=247,03], EntityChicken['Chicken'/204, l='MpServer', x=27,12, y=71,00, z=253,73], EntityWitch['Witch'/205, l='MpServer', x=16,25, y=15,00, z=257,48], EntityZombie['Zombie'/206, l='MpServer', x=21,47, y=41,00, z=257,50], EntityEnderman['Enderman'/207, l='MpServer', x=19,50, y=40,00, z=259,50], EntityChicken['Chicken'/208, l='MpServer', x=20,87, y=71,00, z=259,10], EntityBat['Bat'/211, l='MpServer', x=14,25, y=15,64, z=270,49], EntityEnderman['Enderman'/212, l='MpServer', x=23,50, y=32,00, z=278,50], EntityChicken['Chicken'/214, l='MpServer', x=31,50, y=70,00, z=279,77], EntityChicken['Chicken'/215, l='MpServer', x=24,53, y=71,44, z=280,94], EntityCreeper['Creeper'/236, l='MpServer', x=46,50, y=20,00, z=128,50], EntityZombie['Zombie'/237, l='MpServer', x=38,50, y=58,00, z=134,50], EntityChicken['Chicken'/238, l='MpServer', x=42,83, y=76,00, z=157,86], EntityChicken['Chicken'/239, l='MpServer', x=45,50, y=76,00, z=156,50], EntityChicken['Chicken'/240, l='MpServer', x=46,50, y=76,00, z=157,50], EntityChicken['Chicken'/241, l='MpServer', x=34,50, y=76,00, z=176,50], EntityChicken['Chicken'/242, l='MpServer', x=37,62, y=80,89, z=176,55], EntityChicken['Chicken'/243, l='MpServer', x=42,13, y=81,00, z=180,65], EntityBat['Bat'/244, l='MpServer', x=34,42, y=49,83, z=238,57], EntityBat['Bat'/245, l='MpServer', x=34,81, y=48,60, z=235,23], EntityHorse['Horse'/246, l='MpServer', x=37,87, y=70,00, z=232,89], EntityHorse['Horse'/247, l='MpServer', x=40,21, y=71,00, z=231,32], EntityHorse['Horse'/248, l='MpServer', x=40,65, y=70,00, z=233,97], EntityHorse['Horse'/249, l='MpServer', x=41,43, y=71,00, z=225,17], EntityHorse['Horse'/250, l='MpServer', x=32,10, y=70,00, z=226,98], EntityHorse['Horse'/251, l='MpServer', x=41,11, y=71,00, z=228,01], EntityChicken['Chicken'/252, l='MpServer', x=35,20, y=71,00, z=243,58], EntityChicken['Chicken'/253, l='MpServer', x=39,98, y=71,00, z=276,59]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:409)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2647)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:395)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1559258384 bytes (1487 MB) / 2640134144 bytes (2517 MB) up to 3006529536 bytes (2867 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn2G
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP 9.23 Powered by Forge 12.16.0.1865 5 mods loaded, 5 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.9-12.16.0.1865-1.9.jar) 
    UCHIJAAAA   Forge{12.16.0.1865} [Minecraft Forge](forge-1.9-12.16.0.1865-1.9.jar) 
    UCHIJAAAA   Baubles{1.2.0.1} [Baubles](Baubles-1.9-1.2.0.1.jar) 
    UCHIJAAAA   Botania{r1.8-301} [Botania](Botania-unofficial.r1.8-301.jar) 
    Loaded coremods (and transformers): 
    GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4229' Renderer: 'Intel(R) HD Graphics 3000'
    Launched Version: 1.9-forge1.9-12.16.0.1865-1.9
    LWJGL: 2.9.4
    OpenGL: Intel(R) HD Graphics 3000 GL version 3.1.0 - Build 9.17.10.4229, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: alternate_textures_futureazoo.zip
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 4x Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz
```

**Comment by Nincodedo** [comment]
Use http://pastebin.com

**Comment by williewillus** [comment]
This is a baubles crash, please report to azanor
