### ISSUE TITLE
Implement new Mana Blaster model

### ISSUE THREAD

**Issue by williewillus** [williewillus/Botania#247]
- [x] Basic model shows up in game with proper colors
- [x] Equipped lens shows up on glass
- [x] Clip should disappear if not present
- [ ] Clip should show other lenses

**Comment by ghost** [comment]
You gonna make it ressemble the psi CADs :P ?

**Comment by williewillus** [comment]
Wiiv did

**Comment by yrsegal** [comment]
https://twitter.com/wiliv75/status/721106406913548292

**Comment by williewillus** [comment]
* [ ] Basic show up in game
* [ ] Equipped lens shows up on glass
* [ ] Clip should disappear if not present
* [ ] Clip should show other lenses

**Comment by williewillus** [comment]
https://github.com/Vazkii/BotaniaV2/issues/4
