### ISSUE TITLE
[1.9] Cross-mod Duplication Bug with Psi

### ISSUE THREAD

**Issue by novasolarius** [williewillus/Botania#250]
I am running the most recent versions of Psi and Botania 1.9. When I break any sort of non-worldgen flower with a basic 'break block' spell I am given back two flowers instead of one. This only occurs with non-worldgen flowers, all other blocks drop the expected number of items. When broken by hand the affected flowers drop the expected number of items.

I have posted this issue on the Psi Github as well.

This is the spell I have used:

{spellName:"Demolish",uuidMost:-6237090200277201185L,validSpell:1b,spellList:[0:{data:{params:{_target:2},key:"operatorEntityPosition"},x:4,y:3},1:{data:{key:"selectorCaster"},x:4,y:4},2:{data:{params:{_ray:2,_max:0,_position:3},key:"operatorVectorRaycast"},x:5,y:3},3:{data:{params:{_target:3},key:"operatorEntityLook"},x:5,y:4},4:{data:{params:{_position:3},key:"trickBreakBlock"},x:6,y:3}],uuidLeast:-8605094596199879615L}

**Comment by MaPePeR** [comment]
Did you run the recent forge? i think there was a bug that caused every TE to double drop

**Comment by williewillus** [comment]
update forge

**Comment by novasolarius** [comment]
I am. I'm running 12.16.0.1865, the most recent version on the Forge website.

**Comment by novasolarius** [comment]
Thank you very much for fixing this issue.
