### ISSUE TITLE
Mana pump crash between two pools

### ISSUE THREAD

**Issue by jrdroney** [williewillus/Botania#251]
Not really sure what could have caused this in version 299. I placed a mana pump between two pools (both probably had at least a little mana in them - a lot in one of them). Pool <-> Pool

I'm attaching a crash report instead of copy/pasting for readability.

[crash-2016-04-23_17.03.53-server.txt](https://github.com/williewillus/Botania/files/233170/crash-2016-04-23_17.03.53-server.txt)

**Comment by williewillus** [comment]
I can't reproduce this, do you have more detailed steps to make it happen?

**Comment by jrdroney** [comment]
Truthfully I'm not sure. I was playing around with transporting mana across multiple areas. I had to MCedit the pump away for the server to stop rebooting. What I remember is that I was playing with sparks too, and both pools had a spark on them. Potentially a recessive spark on the receiving pool. Maybe an infinite loop of some type?
