### ISSUE TITLE
[Balance] Terra blade outclasses any other weapon by a long shot

### ISSUE THREAD

**Issue by yrsegal** [williewillus/Botania#256]
Range, sort of not caring about cooldown... The Terra Blade should have a cooldown (cooldown handler?) for its bursts.

**Comment by escman1999** [comment]
isnt the terrablade supposed to be an endgame item?

**Comment by yrsegal** [comment]
Still, it shouldn't make the user unparalleled in PvP. If you're skilled, someone unarmored can kill someone in full diamond with 1.9 mechanics.

**Comment by ghost** [comment]
This is really two sided , since it is extremely good to clear mobs which makes 10x less painful. But i must admit without other mods like neotech, tinker , slash blade , matter overdrive or even geko lasers it is extremely effective againts other players.

**Comment by yrsegal** [comment]
The Thundercaller can be used to clear mobs, and it's not OP at all with
1.9 mechanics.

**Comment by ghost** [comment]
it also effective to repell players away from your base trying to be a thief.

**Comment by yrsegal** [comment]
I'm not saying remove the long range, I'm saying remove the spammability

**Comment by ghost** [comment]
Its the spam that helps lol. Maybe the beam should deal less damage if its spammed, following the weapons rule.

**Comment by novasolarius** [comment]
I really don't see the issue. Yes, the Terra Blade is a significant increase in power that makes PvP utterly unbalanced. But how exactly is that different from literally everything else? I don't see people with a stick trying to beat someone with a bow and a diamond sword, yet nobody complains about that. It's a power gap, yes, but that's only an issue if it's impossible for other players to reach the same power level. And it isn't.

**Comment by yrsegal** [comment]
No, but it makes it so there's NO alternative that's better. Axes and hoes have their place: i've even seen people using Elytras with Axes in pvp as an evasive attacker. Bows are useful too, because they allow you to do ranged damage.

But the terra blade is one of the top tier weapons at the SAME TIME as a ranged weapon. It simply outclasses everything else.

**Comment by novasolarius** [comment]
And? It's not that I don't agree with you that fighting a player with a Terra Blade is hard without one, but there's really no good reason why somebody wouldn't be able to make one for themselves and fight back. Keep up with the competition or get left behind.

**Comment by yrsegal** [comment]
What you're describing is called Power Creep, and it's the biggest problem with the modded community. Botania has always actively worked to mitigate it.

**Comment by novasolarius** [comment]
How is this power creep exactly?

**Comment by yrsegal** [comment]
"Keep up with the competition or get left behind" is the very essence of power creep.

**Comment by novasolarius** [comment]
Really? I thought "surpass the competition" was power creep. Keeping up would seem like common sense to me, which is why everybody fights wars with guns instead of clubs.

**Comment by yrsegal** [comment]
Real life is prone to power creep, certainly. If it was balanced well, we would all be using swords, or maybe even clubs.

**Comment by novasolarius** [comment]
Ah. But still, using what's there to make sure you don't get murdered in seconds doesn't seem like anything short of common sense. Besides, it doesn't scale either, so everybody at the same tech level should be at the same power level as well. And if that power level means slightly better than average weaponry, so be it.

Speaking of which, whatever happened to invisibility potions, poison and a bucket or two of lava?

**Comment by yrsegal** [comment]
Not everyone wants to go down the Botanist's path. Not everyone wants to get the hilariously powerful ranged weapon, because of all the infrastructure you need.

Hell, even the Key of the King's law is pretty fair. Not the worst thing to dodge the weapons at distance, and at short range it hurts you too.

**Comment by novasolarius** [comment]
Not everyone wants to go down the Botanist's path? Odd, but I can respect that. However, that probably means that there are other mods involved, each with their own methods of fighting back. And if not I'll just repeat myself: Invisibility potions, poison, lava buckets.

**Comment by yrsegal** [comment]
That still dies to terraspam. EVERYTHING dies to a player with a tiara (and a highlands rod) and a terra blade. That's the core issue here.

**Comment by williewillus** [comment]
Keep the conversation on track and specific to this item instead of a "zomg power creep no its not yes it is"

**Comment by williewillus** [comment]
What do you guys propose to (not) change?

**Comment by yrsegal** [comment]
I propose to add a cooldown to the swing effect of the Terra Blade (this time you will use .hasCooldown :P)

**Comment by novasolarius** [comment]
I'm curious. Is the cooldown of the Terra Blade bound to the item or the player?

**Comment by yrsegal** [comment]
player, and for all instances of the item.

**Comment by novasolarius** [comment]
Can the beam pierce through enemies? If not, can that be added? To at least maintain some level of mob-clearing potential.

**Comment by yrsegal** [comment]
It does, I believe. It's just a regular Damaging lens, effectively, right?

**Comment by novasolarius** [comment]
I honestly don't know. I generally just use it for early mid-game PvP. I barely ever fight mobs myself, actually. But if it's a carbon copy of the Terra Blade from Terraria, it does have some mild\* piercing.

*: what I consider 'mild piercing' may not be the same as what others consider it. In this context, 'mild piercing' means 'pierces through two targets'.

**Comment by yrsegal** [comment]
oh, this pierces through maybe three or four.

**Comment by yrsegal** [comment]
bc0ca77960d0cca0a72fab496d813de7d0e815ee
