### ISSUE TITLE
Horn blowing sounds like someone's farting

### ISSUE THREAD

**Issue by yrsegal** [williewillus/Botania#257]
I'm not just being immature, that's literally what it sounds like.

1.9, build 302

**Comment by williewillus** [comment]
u w0t m8

**Comment by yrsegal** [comment]
it's this prolonged 'brrrraaaaaaaaaaap' sound, it's really quite disgusting

**Comment by williewillus** [comment]
Oh the timer is off
It's playing every tick

**Comment by yrsegal** [comment]
Didn't it do that in 1.7?

**Comment by williewillus** [comment]
It should be more like 2-3x a second

**Comment by yrsegal** [comment]
yep
wonder why it didn't fart then

**Comment by yrsegal** [comment]
2-3 is kind of irregular, it sounds like someone just hitting drums repeatedly

**Comment by williewillus** [comment]
Oh i misremembered, it is once per tick in 1.7
The pitch is off

**Comment by yrsegal** [comment]
I think the problem is the sounds aren't overlapping

**Comment by williewillus** [comment]
I just had the wrong one
