### ISSUE TITLE
Black hole talisman deletes items when trying to place blocks above world limit

### ISSUE THREAD

**Issue by Hyxaru** [williewillus/Botania#258]
You cannot place blocks above the world limit, but the black hole talisman believes it can.

**Comment by yrsegal** [comment]
It's been clicking on too many tiny potatos, it believes in itself too much

**Comment by howtonotwin** [comment]
Not currently in a position where I can edit the code but I can still suggest something.

<s>[Here](http://github.com/williewillus/Botania/blob/6c52c4f5f90ce7e4020e3721e08d3aa688d8c303/src/main/java/vazkii/botania/common/item/ItemBlackHoleTalisman.java#L120-L126), an item is popped from the talisman and placed into its own stack. Then `Item.onItemUse(stack, ...)` is called, and `stack` itself is promptly **_discarded_**. I propose that `stack` is checked to see if it's empty, and if it isn't, it's either pushed into the black hole or placed into the inventory (if `stack` is non-empty but no longer has the same item). (Or we use the return value of `onItemUse()`, but I'm not quite sure about anything right now.)</s> Blargh, that won't work.

&lt;grammarnazi correcting="yrsegal"&gt;potatos-&amp;gt;*potatoes &amp;amp; ,-&amp;gt;*;&lt;/grammarnazi&gt;
<sub><sup>Ewwww, XMLCeption. <sub><sup>bwaaa...</sup></sub></sup></sub>
