### ISSUE TITLE
EntityDoppleganger (Gaia Guardian) doesn't set isNonBoss to false

### ISSUE THREAD

**Issue by yrsegal** [williewillus/Botania#259]

**Comment by yrsegal** [comment]
also, wtf mojang
isNonBoss
why not... isBoss

**Comment by MaPePeR** [comment]
That's probably a mapping fault not caused by Mojang. Maybe the original name is "isNormalEntity"  or something like that.

**Comment by williewillus** [comment]
What does this actually affect?

**Comment by yrsegal** [comment]
Tangleberrie and other mods

**Comment by yrsegal** [comment]
Psi, for one.

**Comment by williewillus** [comment]
I'm pretty convinced the mcp name shouldn't be isNonBoss, it's more like "shouldPassThroughPortals"
but that's irrelevant I'll add it
