### ISSUE TITLE
Ring of Far Reach has no effect when equipped via Right Click while holding

### ISSUE THREAD

**Issue by TheWhiteWolves** [williewillus/Botania#26]
When you Right-Click the Ring of Far Reach while holding it to equip the ring it will not extend the players reach, if you manually go into the bauble inventory and place the ring in a ring slot or shift click it in from your inventory it will work as intended.

The screen shot show the reach distances between normal and far reach (white is player position, orange without ring, magenta with ring)

You only reach the orange wool when equipping via this method.

![2016-01-09_03 15 16](https://cloud.githubusercontent.com/assets/1471503/12214100/773e0870-b67f-11e5-966c-17bff00739d3.png)

---

Instance:
minecraft-1.8.9
forge-11.15.0.1688

Mods:
Baubles-1.8.9-1.1.3.0
Botania.r1.8-248-MC1.8-a1aa50b
jei_1.8.9-2.14.0.67
modnametooltip_1.8.8-1.0.0

**Comment by williewillus** [comment]
Actually an upstream issue, onEquipped is not called in the right click method, and even when I made it do so, the client needs to know about the reach extension, and the right click code block only executes serverside

Not sure what to do besides adding custom packets, of which botania has none

**Comment by TheWhiteWolves** [comment]
Your right, never even realised we had this problem in 1.7
