### ISSUE TITLE
[1.9] [Enhancement?] Mana Enchanter Mending Enchantment.

### ISSUE THREAD

**Issue by G-Stav** [williewillus/Botania#260]
Unable to add the Enchantment "Mending" to armor/tools through using the Mana Enchanter.

**Comment by williewillus** [comment]
Cannot reproduce

**Comment by G-Stav** [comment]
Okay, never mind, I messed up big time. I missed the part about if a book has more than one enchantment it only uses the first one. Very sorry for the hassle.
