### ISSUE TITLE
Mana Blaster and Rod of the Bifrost, etc, use durability instead of modern cooldown handler

### ISSUE THREAD

**Issue by yrsegal** [williewillus/Botania#261]
this is technically a nerf, but still modernity is nice

**Comment by williewillus** [comment]
this breaks dual wielding mana blasters :(
because the cooldown applies to all stacks of that item type

I'll probably do it for everything except blasters

**Comment by yrsegal** [comment]
Fair enough, dual mana blasters are srs bsns
