### ISSUE TITLE
1.9-Crash clicking on Daybloom with wand

### ISSUE THREAD

**Issue by RealGrep** [williewillus/Botania#262]
So I was setting up dayblooms and had forgotten the mana spreader. So they were not bound. I placed the mana spreader, bound it to the mana pool. Bound one daybloom to the spreader. Trying to bind the second one, client crashed and I got this output on the client side:

http://pastebin.com/UvYGHTsV

Server didn't crash, but I see this output there:

http://pastebin.com/LJvJQrxJ

Let me know if you need anything else. Thanks, and good luck with your exams!

EDIT: Forgot the version info. This is with Botania-unofficial.r1.8-302.jar and Forge version 1867.

**Comment by williewillus** [comment]
Rolling this into #221, caused by Forge bug https://github.com/MinecraftForge/MinecraftForge/issues/2773
