### ISSUE TITLE
Floating flower model mappings break with F3 + T

### ISSUE THREAD

**Issue by yrsegal** [williewillus/Botania#264]

**Comment by williewillus** [comment]
screenshots..?

**Comment by yrsegal** [comment]
<img width="403" alt="screen shot 2016-05-04 at 6 25 06 pm" src="https://cloud.githubusercontent.com/assets/6596492/15031294/929b399c-1225-11e6-92af-5497c7edb243.png">

**Comment by williewillus** [comment]
conditions to reproduce? I've never ever had this and I f3+t in dev a million times a day

**Comment by yrsegal** [comment]
In a dev env (intelliJ) I run "reload changed classes" with a changed model, f3+t, and this happens.

**Comment by williewillus** [comment]
?shrug idk why that happens, maybe investigate if I can ever get it to happen

**Comment by williewillus** [comment]
i have a suspicion
If you run without JEI does this happen?
