### ISSUE TITLE
[Minor] Assembly halo can't be used with JEI [+] button

### ISSUE THREAD

**Issue by yrsegal** [williewillus/Botania#267]

**Comment by williewillus** [comment]
I'm assuming you mean the main crafting gui, idk how to add support for that. @mezz?

**Comment by mezz** [comment]
Here's the line to implement it for the vanilla crafting table. YMMV, that item looks pretty crazy. As long as it opens a GuiContainer it should be able to work. The javadoc should be clear.

https://github.com/mezz/JustEnoughItems/blob/1.9/src/main/java/mezz/jei/plugins/vanilla/VanillaPlugin.java#L84

**Comment by yrsegal** [comment]
`recipeTransferRegistry.addRecipeTransferHandler(ContainerCraftingHalo.class, VanillaRecipeCategoryUid.CRAFTING, 1, 9, 10, 36)` should work?

**Comment by mezz** [comment]
You should also register the Assembly Halo item as being able to craft stuff, so people can look it up and find things that way.

https://github.com/mezz/JustEnoughItems/blob/1.9/src/main/java/mezz/jei/plugins/vanilla/VanillaPlugin.java#L89

**Comment by yrsegal** [comment]
Don't forget the Manufactory Halo.
