### ISSUE TITLE
[1.8.9] Red Stringed Comparators doesn't work

### ISSUE THREAD

**Issue by Eufranio** [williewillus/Botania#270]
The comparator doesn't dettect anything.
Botania 1.8.9 r1.8-299
![Bug](https://cloud.githubusercontent.com/assets/17598280/15094274/e1d97770-1474-11e6-8d0f-93afce93db4b.png)

**Comment by Eufranio** [comment]
Sorry, i had not seen the latest release.

**Comment by Eufranio** [comment]
No, the fix is only for 1.9 :/
@williewillus

**Comment by williewillus** [comment]
Not sure if I'm going to make any more releases for 1.8.9
If I have time I will soon.

**Comment by Eufranio** [comment]
Okay, try pleeeease! :/
