### ISSUE TITLE
No worldgen when using Realistic Terrain Generation Mod

### ISSUE THREAD

**Issue by MJRamon** [williewillus/Botania#273]
With http://minecraft.curseforge.com/projects/realistic-terrain-generation there is no world gen from Botania.
Things like ores, structures etc from other mods (as well as flowers from Biomes'O'Plenty) spawn normally.

**Comment by williewillus** [comment]
Not sure why this is, we generate flowers normally like any other mod

Our event handler is on low priority though

**Comment by MaPePeR** [comment]
Wasn't the flower generation changed at once point from all over the place to bigger pockets?

**Comment by aldun** [comment]
I just added Botania to my existing world and the flowers seem to be generating in new chunks just fine for me.

Botania version 1.8-304
Realistic Terrain Generator version 2.0.0 alpha 1

**Comment by MJRamon** [comment]
Well, I have a lot of mods that generate on surface.

@williewillus What parameter should I crank up in config? I don't want to make big chunks of flowers all over the place, just 1-2 every 8-10 chunks.

**Comment by williewillus** [comment]
So that seems to be the answer then :P 

@MJRamon decrease worldgen.flower.patchChance to your liking
