### ISSUE TITLE
Bug when trying to burry a petal

### ISSUE THREAD

**Issue by Myknakryu** [williewillus/Botania#274]
Minecraft version: 1.9
Forge version: 1900
Botania build: r1.8-304
JEI version: 3.3.3.200
Baubles version: 1.9 1.2.0.2

When i was trying to burry petal to make flower. But game crashes. I've tried it on a single player but this same happens it crashes client but not server. It even crashes when right click when petal is in main hand. I've tried with light gray only but it also seems others are broken too...

Crash logs:
When single player
http://pastebin.com/aMffYg7Q

When on server
http://pastebin.com/fZKdfgf5

**Comment by Myknakryu** [comment]
So i've tried it without other mods and other petals, it still crashes.

Crash log when used purple mystical petal with only Botania, Baubles and JEI installed
http://pastebin.com/knfeyPrg

**Comment by yrsegal** [comment]
You're using the old system for placing, Willie. It requires the block to have an item form. If you look at [this](https://github.com/yrsegal/NaturalPledge/blob/master/src/main/java/shadowfox/botanicaladdons/common/items/colored/ItemLightPlacer.kt#L63-L98) it gives an alternate solving method (most of the code there is copypasta from ItemBlock.)
