### ISSUE TITLE
[1.7.10]Lan Servers do not seem to work with Botania(no mana usage for other players)

### ISSUE THREAD

**Issue by Lodugh** [williewillus/Botania#275]
I use the "open to lan" function to play with my friends and they cant use mana items. However I can use them still... I saw in some forums that other people had the same issue, but I guess there are not that many people who use open to lan. I wouldnt use it either but my computer cant handle a dedicated server alongside the client. I am using the latest version "Botania r1.8-249" for Minecraft 1.7.10.
I hope you are still working on the 1.7.10 version if bugs come up..
Greetings,
Lodugh

**Comment by williewillus** [comment]
I am not working on 1.7 (in fact, I'm not allowed to under the mutual agreement I made with vaz haha)
Though, I will investigate this for 1.9+
Thanks!
