### ISSUE TITLE
NullPointerException when trying to bury petal

### ISSUE THREAD

**Issue by Roxforbraynz** [williewillus/Botania#276]
[Crash log](http://pastebin.com/G40ihHAb)

[Offending line of code](https://github.com/williewillus/Botania/blob/MC19/src/main/java/vazkii/botania/common/item/material/ItemPetal.java#L35)

Forge 1.9-12.16.1.1901
Botania Unoffical r1.8-304
Baubles 1.9-1.2.0.2

**Comment by mindforger** [comment]
https://github.com/williewillus/Botania/issues/274

**Comment by williewillus** [comment]
Dupe, thanks for the report though
