### ISSUE TITLE
[1.8.9] Mana Spreaders are not sending mana.

### ISSUE THREAD

**Issue by milano1110** [williewillus/Botania#277]
I am playing in a singleplayer world with Botania and a handful of other mods. And as of recently my mana spreaders have stopped working. At the time I added a new mod to my pack: Custom NPC, and I noticed that the spreaders would fill up and not send mana burst anymore. It would not send to the mana pool or the runic altar when I tried to make a rune. I then removed Custom NPC from my pack, but my mana spreaders still didn't work.

I am using:
forge-1.8.9-11.15.1.1855-installer
Botania-unofficial.r1.8-299

These are the rest of my mods:

Biomes O Plenty
Blood Magic
Chameleon
Chisel
Chisel and Bits
Dense Ores
Extra Utilities 2
Fast Leaf Decay
Flat Colored Blocks
Intangible
Inventory Tweaks
Iron Chest
JEI
JEI Addon
Journey Map
Just Enough Resources
Mantle
MC Multipart
MmmMmmMmmMmm
Modular Powersuits
Numina
Project E
Psi
SAO UI
Storage Drawers
Tinkers Construct
Waila
World Edit

This is what is happening:
![2016-05-13_21 32 12](https://cloud.githubusercontent.com/assets/19352193/15259567/4739f964-1952-11e6-9eb3-442c7763189a.png)

**Comment by williewillus** [comment]
Send me your world (preferably with signs indicating what spreaders don't work)

if your modlist came from a pack that would be helpful to have too

**Comment by milano1110** [comment]
I have found the problem, ProjectE adds the Swiftwolfs Rending Gale, if you activate it, it pushes all entities away, so mana bursts aswell.

**Comment by williewillus** [comment]
Ah. I should probably implement a blacklist for that in be xD
