### ISSUE TITLE
Few bugs

### ISSUE THREAD

**Issue by Myknakryu** [williewillus/Botania#279]
Minecraft version: 1.9
Forge version: 1900
Botania build: r1.8-304
JEI version: 3.3.3.200
Baubles version: 1.9 1.2.0.2

So first bug is bug with trodden dirt. You sink in it when you walk in it. It gives you speed, but you cannot walk on it unless it's a slab.

Screenshots to confirm that:
http://imgur.com/a/uDJM3

Second bug is with spreaders. When you try to bind them with blocks, everything works fine. It complicates when i've accidently tried bind it to grass or flower crashes the game. It does not crash server, only crashes client.

When i've found out it i was playing on server. To recreate that i've installed only JEI, Baubles and Botania to confirm these bugs.

Screenshots of mana spreader bug:
http://imgur.com/a/f4KKS

Logs:
http://pastebin.com/tBmrs1c7

**Comment by yrsegal** [comment]
Shouldn't trodden dirt not exist anymore, because of Grass Path?

**Comment by Myknakryu** [comment]
It may be named in code dirtPath but in game it's still Trodden Dirt.

Screenshot:
http://imgur.com/8TG6r9T

**Comment by yrsegal** [comment]
I'm saying that it should be removed because vanilla has an equivalent.
