### ISSUE TITLE
Gaia Guardian's Head rendering incorrectly

### ISSUE THREAD

**Issue by Bitmarim** [williewillus/Botania#28]
I simply created a new world, got the head from the Creative Tab, and it is displaying the head incorrectly. The Gaia Guardian itself seems unaffected by this issue, although it only renders with a Steve skin.

http://i.imgur.com/yNEsrOH.jpg
- The heads with my skin

http://imgur.com/sX0Trjt
- Gaia Guardian with Steve skin without this issue.

**Comment by yrsegal** [comment]
what do you mean by displaying it incorrectly? because the glitchy appearance is intended.

**Comment by williewillus** [comment]
works as intended (checked with 1.7)
the shader gives it the wobbly distortion
