### ISSUE TITLE
Living Root Block has a missing texture when held

### ISSUE THREAD

**Issue by DrasticDemise** [williewillus/Botania#282]
Garden of glass block

1.9

**Comment by williewillus** [comment]
uhh what. screenshot? how did you get it?

**Comment by williewillus** [comment]
for me it looks exactly like the actual livingroot item (which is wrong, but it's not missing)

**Comment by DrasticDemise** [comment]
http://i.imgur.com/40c0mHQ.png
Obtained using MB3 on the block in creative. Right clicking places the correct block on the ground.
