### ISSUE TITLE
Stellar Sky and GoG cause the game to freeze when using /timeset

### ISSUE THREAD

**Issue by DrasticDemise** [williewillus/Botania#283]
They probably shouldn't be used together anyway, however I found this interesting bug that causes the game to entirely freeze when using a timeset command. Not 100% positive which mod is causing the issue, but I figured reporting it here is better than not reporting it at all.

**Comment by yrsegal** [comment]
Can you give the log?

**Comment by williewillus** [comment]
Cannot reproduce

**Comment by williewillus** [comment]
Started a new GOG with latest botania code, latest stellar sky release.
GoG's auroras don't show up but it doesn't freeze

**Comment by DrasticDemise** [comment]
Hmm. I have included BetterFPS however that is the only thing I can think of that would cause this issue in a pack-specific way.

**Comment by jriwanek** [comment]
Attempting /time set day with Stellar Sky and no botania sometimes causes a crash too, pretty sure this is nothing to do with botania.

**Comment by vladfrangu** [comment]
Garden of Glass (as far as I got it) is just a code that tells Boania to load the GoG code. (Not the mod itself doing anything, thus the requirement for Botania)

So, there might be a issue in Botania.. But always, try removing things like Optifine, BetterFPS (FastCraft might affect this too, but I dont know), and then try the same issue. And a log would probably help more than a message

**Comment by williewillus** [comment]
can't reproduce so report it at the new repo if you get it to happen again
