### ISSUE TITLE
Exception firing events on dedicated servers - not single player (GoG)

### ISSUE THREAD

**Issue by DrasticDemise** [williewillus/Botania#285]
This bug may extend past this mod entirely, however it is a bit too strange. Attempting to use the right-click event for obtaining pebbles in Garden of Glass on a dedicated server throws the following logs:
http://pastebin.com/aCdHu8M2
http://pastebin.com/zSsHVXvS
These are the only logs that the server gives. The game does not crash, the event simply fails and nothing happens. Note that it references ASM errors occuring with Quark, Botania, and Soul Shards, however I was only able to reproduce the ASM error with Botania and pebble harvesting in GoG. Single player worlds do not throw these errors which is what makes this exceedingly strange.

The client is running forge build 1906 and the server is running forge-1.9-12.16.1.1906-universal.jar

I half expect this error to be due to the cutting edge forge version, but I have no way to confirm this nor test it other than downloading a few dozen forge folders.

**Comment by williewillus** [comment]
Can you get logs with just Botania? (I know you repro-ed but just want to see and make sure)

**Comment by DrasticDemise** [comment]
Just attempted to reproduce it with ONLY botania and GoG
http://pastebin.com/xNzu3BpQ

**Comment by DrasticDemise** [comment]
@williewillus Does this also fix the ability to gather pebbles?

**Comment by williewillus** [comment]
yes
