### ISSUE TITLE
Chat Spam [Enhancement]

### ISSUE THREAD

**Issue by SethWilliamson** [williewillus/Botania#290]
We've all been there. Remember having 1.7.10 collections with so many mods sending chat messages when a player joins a world that they blow past the scroll-back buffer? With actionable messages buried in lines of messages players have seen time and time again, they simply learn to ignore the stream of login messages. I'm asking if you could do your part to remove non-actionable messages and stop spamming notice messages after a few logins.

I.e. Notice type messages like the unofficial warning and the quark warning could display the first three times a player joins a world. This could reset whenever a new version of the mod is installed. Optional extra, add a config to control verbosity of in-game chat messages. 

On that note, there is already a config option for new version notifications. Rather than on-off, I'd like to see an available middle ground with notification the first X [3] times I join a world and no further notifications until I either install a different version, or yet another new version posts.

**Comment by vladfrangu** [comment]
You can always just do F3 + D to clear the chat

**Comment by yrsegal** [comment]
But doing it every time would get annoying.

**Comment by williewillus** [comment]
invalid now
