### ISSUE TITLE
API users cannot add alchemy or conjuration recipes if an infusion recipe exists for that item.

### ISSUE THREAD

**Issue by CplPibald** [williewillus/Botania#291]
This issue affects mods using the Botania API, under the following conditions:  
1) The mod wants to add an infusion recipe using either the alchemy or conjuration catalysts.  
2) Botania already defines a mana infusion recipe for that item.  

The issue is that the new recipe will never be called, even when a pool has the correct type of catalyst.

**Detailed Explanation**

When an item is thrown into a mana pool, the pool iterates over the list of recipes and stops when the following conditions are met.

```
if(recipe.matches(stack) && (recipe.getCatalyst() == null || worldObj.getBlockState(pos.down()) == recipe.getCatalyst()))
```

In particular, if a recipe that doesn't need a catalyst is encountered for that item, the search will stop and that recipe will be used.  Botania gets around this problem by adding all alchemy and conjuration recipes first, and infusion (no catalyst) recipes last, guaranteeing that the more specific recipe will be found first when appropriate.

The design intent seems to be that when a catalyst is present, that catalyst's recipes should take precedence.  (For example, redstone dust which has all three recipes).  Unfortunately, when a mod calls `registerManaAlchemyRecipe` or `registerManaConjurationRecipe`, the new recipe is added to the end of the `BotaniaAPI.manaInfusionRecipes` list, meaning its recipes are always searched last.

**Possible solutions:**

1) When adding recipes via the API, add to the front of the `manaInfusionRecipes` list if the recipe requires a catalyst, and add to the back if it doesn't.

2) Change the logic to always iterate the whole list searching for catalyst-specific recipes before settling on a non-catalyst recipe.  The logic above is in both _TilePool.java_ and _HUDHandler.java_

3) Split `BotaniaAPI.manaInfusionRecipes` into multiple lists, and iterate them separately in order when finding recipes.

**Workarounds**

1) A mod can ensure its `preInit()` gets called before Botania's so its recipes are added earlier.

2) A mod can directly manipulate the `manaInfusionRecipes` ArrayList instead of calling the API functions.

**Comment by yrsegal** [comment]
1) sounds like a good solution (the API one)

**Comment by yrsegal** [comment]
Also, damn, how did I miss that ._.

**Comment by williewillus** [comment]
Will probably go with #2
Thanks for the super detailed report!

**Comment by CplPibald** [comment]
> Also, damn, how did I miss that ._.

Because it's a really obscure bug and I'm possibly the first person ever to be affected by it.  No worries, you're not a dev until you've shipped a few bugs.  :-)

**Comment by yrsegal** [comment]
No, i mean I tested with all kinds of things that the new system worked but somehow missed glow/redstone

**Comment by CplPibald** [comment]
You won't see this problem with glowstone/redstone because Botania adds all of its own alchemy/conjuration recipes first before any infusion recipes.  See [CommonProxy::init()](https://github.com/williewillus/Botania/blob/995c19c04ab24ec5f6a65da850bc9050c49e47c7/src/main/java/vazkii/botania/common/core/proxy/CommonProxy.java#L126-L128).  This only happens with addons that call the API after Botania has initialized.

**Comment by yrsegal** [comment]
Ah. Fair enough, my tests in that regard were not exhaustive
