### ISSUE TITLE
Botania flowers randomly lose their models/textures

### ISSUE THREAD

**Issue by Roxforbraynz** [williewillus/Botania#293]
After being placed down for a while, the Pure Daisy will lose it's model and texture, becoming the pink and black checkered cube. Breaking it and placing it again temporarily fixes the issue. I'll update this if I find any consistent way to recreate this problem.

**Update:** This seems to affect all Botania flowers at once and they seem to still function.

Forge 1.9.4-12.17.0.1909
Baubles 1.9.4-1.2.1.0
Botania Unofficial r1.8-306
Garden of Glass
Optifine 1.9.4 HD_U_B4

**Comment by williewillus** [comment]
I can't reproduce this accoding to what @yrsegal said.
Placed hopperhock far from spawn chunks, set chunk dist to 2
Fly far away, fly back / reload world a bunch of times, it's still a hopperhock.

@Roxforbraynz is this randomly while you're just standing there?

**Comment by Roxforbraynz** [comment]
The times I noticed when it happens is when the world loads when loading the save or returning from the nether. It also happens occasionally when a large tree grows nearby. Those are the only events where I'm seeing it almost consistently happen. In addition to replacing them, sometimes an update to the NBT data or blockstate seems to fix it, like when the mana stored in the Orechid changes, or the Endoflame consumes fuel and begins to work.

Additionally, mana spreaders graphically reset their rotation when this event occurs as well. Everything still _functions_ properly however.

It might also be worth noting that the flowers are in spawn chunks.

**Update:** Some pictures.
[Before growing a jungle tree](http://i.imgur.com/x7XWRxO.png)
[After growing a jungle tree](http://i.imgur.com/fmEC6IO.png) (Note the pure daisy lost it's model.)
[Size of the jungle tree](http://i.imgur.com/Ln4a2L1.png)
[Screenshot of mods folder](http://i.imgur.com/r14ScjP.png)

**Comment by williewillus** [comment]
Interesting, solved this bug in late 1.8 (I think), and it's reappeared. Probably due to 1.9.4 te syncing changes.

**Comment by Morpheus1101** [comment]
I've just enterd a biome an its only the oxeye_daisy thats showing untextured, i killed myself, tp'd 10k blocks away, waited 10min tp'd back to that location an those flowers were still untextured

**Comment by Roxforbraynz** [comment]
[Another jungle tree grew. The effects were more severe this time.](http://i.imgur.com/V9RliWZ.png)
[I then fed the Endoflames some charcoal to keep the Orechid going](http://i.imgur.com/L46lgGB.png) and the endoflames fixed themselves when they started generating mana, and then the Orechid fixed itself when it got some more mana into it's internal storage. That's the best demonstration of this bug that I can give.

**Update:** Only the flowers in the chunk that the tree grows are affected. [The big tree grew into the chunks of the endoflames and orechid, but not the pure daisy and the pure daisy is fine.](http://i.imgur.com/y423fNU.png)

**Comment by williewillus** [comment]
I actually fixed this in dev, and forgot that I did .-.
Will be fine in next build
