### ISSUE TITLE
Visual bug with unstable blocks and "Neat" Mod

### ISSUE THREAD

**Issue by Myknakryu** [williewillus/Botania#294]
Botania version: r1.8 306 1.9.4
Baubles version: 1.2.1.0
JEI version: 3.4.0.204

While i was testing botania on 1.9.4 i installed Neat. The lightning effect of all unstable blocks and even mana pool lightning effect changed collor to gray.

Neat version: 1.2-7

Screenshots:
http://imgur.com/a/UfAHp

**Comment by yrsegal** [comment]
This sounds like a leaked state from neat.

**Comment by williewillus** [comment]
report to neat
