### ISSUE TITLE
[1.9] Massive amount of server console spam 

### ISSUE THREAD

**Issue by b0bst3r** [williewillus/Botania#296]
java.lang.IllegalArgumentException: Integer is too big for 3 bytes

http://pastebin.ubuntu.com/16570657/

Starts on line 12871 and only stops when server is shut down, not 100% sure what's causing it but crash seems to point to hoppehock.

forge 1907
Botania-unofficial.r1.8-305.jar

**Comment by b0bst3r** [comment]
Oh I just read the 306 changelog is that "Fix some log spam" related to this?

**Comment by williewillus** [comment]
That's a separate issue, thanks for the report
Sorry about the spam >_<
