### ISSUE TITLE
Allow manual additions to the botania config for the Orechid Spawns

### ISSUE THREAD

**Issue by DrasticDemise** [williewillus/Botania#298]
Some ores are not automatically supported, would be nice to be able to go through and edit the weights or add additional ores to the list through the config

**Comment by yrsegal** [comment]
That's a minetweaker feature.

**Comment by DrasticDemise** [comment]
Modtweaker is currently not supported for the latest versions, and installing two additional mods to just change the weights of even vanilla ores internally is not very intuitive

**Comment by mindforger** [comment]
@DrasticDemise MineTweaker and Modtweaker are very widely supported from many mods, you can call them almost core mods, IMHO they have a special role and should always be present if you are going to mix more than one mod or start adjusting a single mod to your own demands. Establishing a parallel adjustment in the mod configs besides Minetwekaer would ruin the support and making the Modpack-World a mess of configs again

**Comment by williewillus** [comment]
~~might even make this a loot table :P~~

actually it uses oredict so not very feasible

**Comment by yrsegal** [comment]
what happens if it runs into an item in a loot table, then?

**Comment by yrsegal** [comment]
maybe have the Orechid break the block and drop the item, if it runs into an item?

**Comment by yrsegal** [comment]
@williewillus if it uses oredict, why not make a function to generate a pool from oredict?

**Comment by williewillus** [comment]
that requires adding to the loot table specification, which only forge can do (just opened an issue)

**Comment by yrsegal** [comment]
grand. PR time? :P

**Comment by williewillus** [comment]
idea rejected :P

**Comment by williewillus** [comment]
also I think this was specifically left to minetweaker to do

**Comment by williewillus** [comment]
There's API functions to do this so I assume that it was intentionally left to *-tweaker and/or addons to do
