### ISSUE TITLE
Mana spreaders should implement Block.rotateBlock

### ISSUE THREAD

**Issue by SoniEx2** [williewillus/Botania#3]
Mana spreaders should implement Block.rotateBlock, for native compatibility with [Framez 2](http://minecraft.curseforge.com/projects/framez)/[Trajectory](http://minecraft.curseforge.com/projects/trajectory), wrenches and turntables (which have existed since BetterThanWolves (yes, back when it was still a Forge mod), but I don't know any current Forge mod which has them...)

(I'm banned from upstream :/)

Also (as of 1.8) this is a vanilla method so even more reason to implement it.

**Comment by williewillus** [comment]
how would it work if the spreader is not pointed on a strictly axis-aligned direction?

**Comment by SoniEx2** [comment]
It'll rotate exactly 90° and still not be pointed in a strictly axis-aligned direction, but still pointing on a different direction.

e.g. 

```
^ turns into >

 ^
/  turns into -_>
```

This also means, if it's on a perfect diagonal, it'll rotate and point to all 4 diagonal directions.

**Comment by williewillus** [comment]
Also then, the question arises on what axis does it rotate?
Should it rotate on the y axis always or should it rotate on the axis of the spreader's head pointing?
This gets a bit too close to changing actual design, and if Vaz wanted to he would've implemented it already.

**Comment by SoniEx2** [comment]
It should rotate on the clicked axis, just like vanilla. Not y axis, not positioning axis.

Looks like I'll have to make some visual explanations of how it'd work...

**Comment by williewillus** [comment]
I know what you want, but I'm saying you're better off requesitng this from upstream, it's something possible in 1.7 already and it gets awfully close to changing design since it allows new mechanics and interactions to occur.

**Comment by SoniEx2** [comment]
I can't do it upstream and Trajectory is gonna add it whether you and @Vazkii like it or not. The only issue I see is that rotateBlock is abused by wrenches, but that's not your or @Vazkii's fault.

**Comment by williewillus** [comment]
"whether I like it or not" then why are you asking me in the first place if you have no intent of respecting my decision?
yeah no I can see why you're banned upstream with that attitude.
bye.
