### ISSUE TITLE
Livingwood Bow doesn't respect ItemArrow.isInfinite

### ISSUE THREAD

**Issue by yrsegal** [williewillus/Botania#300]
Also, this secondary part might not be considered a bug, but you can't fire arrows under any circumstances with the crystal bow. So, having arrows in the offhand might fire them with the crystal bow?

**Comment by williewillus** [comment]
crystal bow does not ammo check at all, it only searches for mana and fires normal arrows.

**Comment by yrsegal** [comment]
It should be able to fire normal arrows too, though, since it is a bow.

**Comment by williewillus** [comment]
it intentionally did not check for arrows before and I believe that's by design so it's not changing

**Comment by yrsegal** [comment]
That's because arrows didn't matter before.

**Comment by williewillus** [comment]
they still don't, the crystal bow fires mana bolts basically

**Comment by yrsegal** [comment]
for any bow, I mean.

**Comment by williewillus** [comment]
not sure what you're getting at then :P

**Comment by yrsegal** [comment]
Even just checking the offhand first would be good since it allows you to load arrows manually, but otherwise fire mana-arrows.

**Comment by yrsegal** [comment]
When the crystal bow didn't check, there were no arrows, at all, that mattered, for any bow. So no reason to check.

**Comment by yrsegal** [comment]
Now, arrows matter a lot, so there _is_ a reason to implement a minor check.

**Comment by williewillus** [comment]
wat are you even saying?

I'm saying that the crystal bow **cannot** fire normal arrows, and never could :P 
It's not a normal bow, it doesn't even have a bowstring. 
It shoots "mana bolts" that just happen to look like arrows bc code reuse :P

**Comment by yrsegal** [comment]
definitely a bowstring. in the recipe, at least. https://github.com/williewillus/Botania/blob/MC19/src/main/java/vazkii/botania/common/crafting/ModCraftingRecipes.java#L1685-L1690

it can shoot mana bolts, but why not be able to fire other arrows if you 'load them manually' (have them in the offhand) into the bow?

**Comment by howtonotwin** [comment]
I think he's referring to potion arrows, where it would be rather inconvenient to have a crystal bow for normal arrows _and_ another secondary bow for potion arrows.

**Comment by yrsegal** [comment]
exactly. (Also natural pledge adds a custom arrow)

**Comment by williewillus** [comment]
The point of the crystal bow is to not carry ammunition around,
I do want to let it fire alternate arrows, but that's going to involve figuring out how to choose ammo type, and also appropriate mana prices for everything

**Comment by yrsegal** [comment]
Choosing ammo type could be as easy as putting the arrow into your offhand, since that's a thing in vanilla

**Comment by williewillus** [comment]
That still involves having ammo :P

**Comment by yrsegal** [comment]
yeah, but it's impossible to make appropriate mana costs for all contingencies.

**Comment by williewillus** [comment]
I'll probably let it fire actual arrows..

still would like a way to only need mana for other arrows though

**Comment by howtonotwin** [comment]
Perhaps craft the bow together with the potion/tipped arrow to set the type, and reset it with a water bottle or plain arrow.

Should probably move this somewhere else too.

**Comment by yrsegal** [comment]
or maybe... BREW ARROWS!
