### ISSUE TITLE
[1.9] Botania causing mineshaft chest loot to reroll every time chest is opened.

### ISSUE THREAD

**Issue by Melakion** [williewillus/Botania#302]
Unlimited random loot, fresh each time chest is opened.

Happening from at least 305 to 307, MC 1.9 and 1.9.4

guessing it's lootTest in https://github.com/williewillus/Botania/blob/MC19/src/main/java/vazkii/botania/common/core/loot/LootHandler.java

**Comment by williewillus** [comment]
I thought I removed that >_<
Thanks

**Comment by williewillus** [comment]
Use next build 308+
