### ISSUE TITLE
Gaia Guardian head dosn´t render correctly

### ISSUE THREAD

**Issue by Flashwar** [williewillus/Botania#303]
The Gaia Gardian head dosn´t render my skin correctly. I´m in the 1.9.4 version of tis mod. 
![2016-05-28_21 58 10](https://cloud.githubusercontent.com/assets/13320784/15629691/de2ec970-251f-11e6-84de-44837042dbd8.png)
![2016-05-28_21 58 07](https://cloud.githubusercontent.com/assets/13320784/15629695/e6afc9fa-251f-11e6-9c91-48bc207baa10.png)

**Comment by yrsegal** [comment]
looks correct to me.

**Comment by yrsegal** [comment]
the GG head doesn't render skins, just glitch.

**Comment by williewillus** [comment]
it's not supposed to, it's supposed to be the steve head with a shader applied, like how the actual guardian looks

**Comment by yrsegal** [comment]
that's not what the guardian itself looks like, @williewillus ._.

**Comment by yrsegal** [comment]
the guardian looks like the player, at least it did in the past

**Comment by williewillus** [comment]
it does, it's the steve model

**Comment by yrsegal** [comment]
yeah, so what you said is wrong... it notably _doesn't_ look like the actual guardian.

**Comment by williewillus** [comment]
whatever's on it is supposed to be obscured to the point you can't make it out

**Comment by williewillus** [comment]
and yeah I see now, the image was hard to look at

**Comment by yrsegal** [comment]
doesn't change the fact that it's **`EntityDoppleganger`** :P

**Comment by williewillus** [comment]
wat

**Comment by williewillus** [comment]
how is the entity relevant in any inkling of way to the issue :P

**Comment by yrsegal** [comment]
you said whatever on it is obscured, I responded by saying it's still there

**Comment by williewillus** [comment]
this is going nowhere, I will investigate rn

**Comment by williewillus** [comment]
Okay so to recap this fix was two things:
1. Bug, Steve skin was all stretched and weird on gaia head
2. Feature, gaia head and gaia guardian now look like you :o
