### ISSUE TITLE
Visual glitch in flowers crafting.

### ISSUE THREAD

**Issue by luxor-g** [williewillus/Botania#307]
![botania](https://cloud.githubusercontent.com/assets/7762387/15632906/3fee8562-25a0-11e6-8cf5-d055a414d09d.png)

**Comment by williewillus** [comment]
?

**Comment by luxor-g** [comment]
The outline is darker than it should. Here's a screenshot of the last 1.7 version.
![botania 2](https://cloud.githubusercontent.com/assets/7762387/15636294/31d0687e-25fa-11e6-902c-88336011a633.png)
