### ISSUE TITLE
NPE on breaking block

### ISSUE THREAD

**Issue by 0Navis0** [williewillus/Botania#309]
## IMPORTANT : THIS BUG IS GENERAL TO ALL THE MODS OF MINECRAFT 1.9 and 1.9.4

A strange bug happens when a tile entity is destroyed, Almost all the time an exception is thrown when the bug happens : Catched unhandled exception  [name of the tile entity] java.lang.NullPointerException 
For some particular blocks, Minecraft totally freezes and finished to crash with the error code -805306369 without any crash report. Here is the list of all the blocks wich are confirmed to provocate Minecraft to freeze and crashs with this error.
- Building Brick : all the glass, ice and packed ice blocks
- Deep Resonance : resonant crystal
- Biomes O Plenty : celestial crystal
- Botania : mana prism
- Blood Arsenal : blood stained glass block and pane
- Evilcraft : darktank
- EnderIO : killer joe, zombie generator, all the fused quartz glasses
- Random Things : lapis lamp, quartz lamp, rainbow lamp, biome glass, spectre block, fluid display

All these blocks follow the same error, only the name of the tile entity between the [ ] changes. Here is an example of how the error happens. The example is made with the resonant crystal of deep resonance. This is a full log and contains the launching of minecraft and the loading of a world, the moment where I brick the block and the bug happens is the moment where the exception [class com.hea3ven.buildingbricks.core.tileentity.TileMaterial] java.lang.NullPointerException is thrown : http://pastebin.com/KhwV1WKg

---

Moreover some tile entities wich has brokner provocates Minecraft to totally crash with a crash report. Here is the list of all the block concerned and their crash report
- EvilCraft : box of eternal closure http://pastebin.com/JzRYf5Ex
- Cooking for block heads : fridge and oven http://pastebin.com/vcmx49qn http://pastebin.com/6zd4qq5w
- Storage Drawers : framing table http://pastebin.com/3077W3Wz

---

I let you know that all the tests possible has already been made before I create this general issue and post it. I already tried to :
- Test the mod one by one only by installing them and forge without any other mods
- Change of Forge Version
- Change between the 1.9 and 1.9.4 version
- Change of mod version
- Play without optifine and any shaders
- Switch between the creative and survival mode
  Nothing of all that change anything, the bug still happens in the same way for the same blocks listed at the top. 

---

I precise that almost all the mods in Minecraft 1.9.4 and 1.9 are touched by this bug, because even if they don't provocate Minecraft to freeze or crash, almost always at each time a tile entity is broken, the exception Catched unhandled exception  [name of the tile entity] java.lang.NullPointerException is thrown.
I precise too that the list of all the tile entities listed at the top can be incomplete. I want you know that I tried to break block by block all the blocks of almost all the most popular mods on 1.9.4 and 1.9, so for summarizing something like 50 mods with more than 2000 blocks. So it's possible that I missed some blocks.
It's why I send this issue to all the mods even if no ones of their block are concerned by the bug.
I invite all the mod developpers to try by themselves to break all the tile entities of their mod for seeing they provocate the throwing of the exception, and maybe causes Minecraft to freeze.

**Comment by williewillus** [comment]
You bring a giant wall of text but I do not see a single line that tells me how to reproduce this

**Comment by williewillus** [comment]
And reproduce it _with Botania alone_

**Comment by williewillus** [comment]
Your log also indicates nothing wrong.
The only error I see is JEI complaining about null stacks which does not crash nor freeze the game

**Comment by GirafiStudios** [comment]
He have copy/pasted this EXACT issue to 4-5 other mods issue tracker too, wtf. o.O

**Comment by 0Navis0** [comment]
If you had readed what I wrote, I already told that I tried all the mods alone, including Botania.

**Comment by williewillus** [comment]
okay now give me steps to reproduce.
Exact steps.

**Comment by 0Navis0** [comment]
Place a mana prism and breaks it.

**Comment by williewillus** [comment]
Give me your log when you do it with botania alone

**Comment by 0Navis0** [comment]
OK wait.
I curruntly deal with an hatter attack because I sended this issue to more than 10 mods = spam.

**Comment by 0Navis0** [comment]
Like the first time I had tried, it doesn't change anything, here is the log with only botania installed when I break a mana prism. http://pastebin.com/s2XMbSFj
I'm sorry, I can't give you more informations, I don't get any crash reports.

**Comment by williewillus** [comment]
https://github.com/SleepyTrousers/EnderIO/issues/3342#issuecomment-222386389

**Comment by 0Navis0** [comment]
Like I said, it's impossible, I have 16 Go, I set my instance to 12 Go, and Minecraft only uses 6 to 8 Go. If you don't trust me, you can see it by yourself. 
![capture](https://cloud.githubusercontent.com/assets/17103411/15636472/2848feb4-2600-11e6-87dc-6ec90313d147.PNG)

**Comment by williewillus** [comment]
No longer a Botania issue.
