### ISSUE TITLE
Mana Spreader crash

### ISSUE THREAD

**Issue by Darkhax** [williewillus/Botania#31]
While playing on a server I encountered a crash when entering a certain chunk. This crash doesn't happen after restarting and logging in, however if you leave and re-enter the chunk the same crash will happen. You can read the full crash log [here](https://gist.github.com/darkhax/ee72e847d2229aa22bbd)

**Comment by williewillus** [comment]
Related? https://github.com/MinecraftForge/MinecraftForge/issues/2363

**Comment by williewillus** [comment]
f3cce3d
