### ISSUE TITLE
Water can flow into fakeAir

### ISSUE THREAD

**Issue by yrsegal** [williewillus/Botania#311]
this means that the bubell causes huge numbers of block updates.

**Comment by williewillus** [comment]
Not really a good solution for this (there's a reason vanilla sponges only work once when they're placed and don't repeatedly apply their effect)

**Comment by williewillus** [comment]
Trying to give them a material that prevents water flowing makes it behave really strange when the flower is broken and the water reappears (way too much water way too fast)

So this is going on the backburned for a bit until I can investigate more

**Comment by williewillus** [comment]
ddda9db
