### ISSUE TITLE
Platforms are not aware of each other for cullfaces

### ISSUE THREAD

**Issue by yrsegal** [williewillus/Botania#312]
For example, stained glass

**Comment by yrsegal** [comment]
they only need to be aware of the ones on all sides to them, probably (all 6 faces and all 12 blocks that connect two faces)

**Comment by williewillus** [comment]
not possible to fix, just tried. Just an unfortunate limitation of stealing other blocks' models without stealing all of their code as well.

**Comment by yrsegal** [comment]
ah well ¯\_(ツ)_/¯
