### ISSUE TITLE
JEI Integration Issue

### ISSUE THREAD

**Issue by Alaric323** [williewillus/Botania#32]
Hi Willie,

Using the latest version of forge (1694), the latest released version of your port (f3cce3d), and JEI 2.16.0.74, I can't get a world to load.  Upon double clicking or hitting play for the selected world, it begins the generation process, but fails when beginning to load JEI.  However, the game does not crash, and simply returns to the main menu.  I have tried generating other worlds as well, and still have the same issue.

While I am using other mods, I use MultiMC, so it's easy to disable them all.  This bug only occurs when JEI and botania are enabled, even if everything else is turned off.

Here is a "crash" log.
http://puu.sh/mrzSm/a0c09f3b14.log

Sorry if I'm missing something.

**Comment by MrGraphic** [comment]
For now turn "B:hideMissingModelsEnabled=true" to false in JEI config. This should allow you to load world.

**Comment by williewillus** [comment]
Can you post a log with just JEI and Botania alone?
It's just a lot to wade through with other mods there :p

Thanks!!

**Comment by williewillus** [comment]
Actually, this is a direct result of #33, redirecting there

**Comment by Alaric323** [comment]
Sorry for the late response.  On the contrary, it does load with hide missing models set to false.  However, I do have issue 33, cause the creative menu crashes.
