### ISSUE TITLE
[1.9.4] Crash on World Load

### ISSUE THREAD

**Issue by copyyy** [williewillus/Botania#322]
When trying to load a world, it gets stuck at 0%.
This only happens when there are also other mods installed.
I'm sorry not to be able to tell you which mod it is conflicting with but I've been trying to figure that out for 2 hours now and when I thought I found it, it decided to crash even without it. 
May look into reproducing that at the weekend but for now I'll just give you my log file and maybe that's already helping or other people with the same issue can compare their modlist to mine.
There is no crash report, it just doesn't load the world.
The log can be downloaded here [http://www.mediafire.com/download/81vttdf5k0v175n/fml-client-latest.log] (Pastebin doesn't like files with ~4.5k lines :( )
I think what you may be looking for starts at line 4216. If that doesn't help, I'll just have to try again finding the conflicting mod.

**Comment by copyyy** [comment]
OK, tried tracking the error down to one specific mod but it doesn't seem to work...
If I remove Botania, it loads the world properly. If I remove Chisels and Bits, it loads the world properly. If I have an instance with only Baubles, Botania and S&B running, it loads the world properly...

**Comment by williewillus** [comment]
@GirafiStudios has this problem as well. Maybe hit him up on irc (Girafi) so you guys can share testing results

**Comment by GirafiStudios** [comment]
Actually it was caused by my own mod now having a IRecipe registered in the RecipeSorter. So it's most likely some other mod not doing that either, would be my guess.

**Comment by GirafiStudios** [comment]
Try removing Bagginses and Extra Utilities 2, and see if that fixes your problem.
Because of:

```
[17:52:24] [Client thread/DEBUG] [FML/Forge]: Sorting recipes
[17:52:24] [Client thread/INFO] [FML/Forge]:   Unknown recipe class! nl.lang2619.bagginses.items.SoulBoundBagRecipe Modder please refer to net.minecraftforge.oredict.RecipeSorter
[17:52:24] [Client thread/DEBUG] [FML/Forge]:     Parent Found: 62 - net.minecraft.item.crafting.ShapedRecipes
[17:52:24] [Client thread/INFO] [FML/Forge]:   Unknown recipe class! com.rwtema.extrautils2.crafting.EnchantRecipe Modder please refer to net.minecraftforge.oredict.RecipeSorter
```

EDIT: I think you only need to remove Bagginses. Extra Utilities EnchantRecipe was erroring too, when I didn't have my IRecipe registered to the RecipeSorter.

**Comment by copyyy** [comment]
Yeah, I already saw that but the weird thing is that everything's working without certain mods, like C&B and Botania. I'll report that anyway to them in a minute, thanks for the info.

**Comment by GirafiStudios** [comment]
Yeah I was experiencing the exact same thing at first when I was getting the issue :)
Just tried to but Bagginses in my modpack and it's for sure causing this!

**Comment by AKTheKnight** [comment]
Ooh interesting. I'll get a fix out asap

**Comment by copyyy** [comment]
Still wondering why it was working when I either removed Botania or C&B oO
Anyway, not a Botania issue so I'll close that here. Thanks for your help.
