### ISSUE TITLE
at java.util.ArrayList.rangeCheck

### ISSUE THREAD

**Issue by whatthedrunk** [williewillus/Botania#323]
I get this crash when joining a server.
http://pastebin.com/HWazmkSQ

**Comment by yrsegal** [comment]
The TileEntityList is getting CME'd, but because MC iterates through its indices, it crashes with a strange error. Not entirely sure this is Botania?

**Comment by williewillus** [comment]
Reproduce with Botania alone

**Comment by whatthedrunk** [comment]
I'm going to close the issue. It doesn't seem to happen anymore and must of been another mod casing the issue.
