### ISSUE TITLE
Corpoea index auto completion doesn't work.

### ISSUE THREAD

**Issue by atakle** [williewillus/Botania#328]
From the Lexicon (Corporea Index, page 8): “[W]hile near a Corporea Index, writing part of an item's name and pressing TAB in the chat menu will autocomplete the item's name."

However, typing TAB doesn't actually have any effect at all.
Tested on latest forge (12.17.0.1954) with only Botania r1.8-308 and Baubles 1.2.1.0 installed.

**Comment by williewillus** [comment]
Vazkii/BotaniaV2#2
