### ISSUE TITLE
Client Crash BlockStateContainer

### ISSUE THREAD

**Issue by ArcheKnight** [williewillus/Botania#329]
I'm no mod dev and so a lot of these logs make little sense to me, especially ones based on this BlockStateContainer value. I was getting issues like this when I broke certain blocks with waila installed and those errors seemed related to waila since it was the common factor in all of the crash logs. But with it gone I can't reason out what is wrong here besides something to do with Botania itself.

A link to my log: [http://pastebin.com/kf15t5CW](http://pastebin.com/kf15t5CW)

**Comment by williewillus** [comment]
i don't think this has happened anymore

**Comment by vladfrangu** [comment]
I can try it if you want
