### ISSUE TITLE
[alpha 0.3.2] Item rendering crash - ItemTwigWand.

### ISSUE THREAD

**Issue by MrGraphic** [williewillus/Botania#33]
Crashing in creative menu and in JEI if item shows up.
https://gist.github.com/MrGraphic/bb1cd0dd128026356b5b

**Comment by williewillus** [comment]
Actually not fixed yet hold on

**Comment by Alaric323** [comment]
You work quick, Willie.

**Comment by williewillus** [comment]
64e3a96

**Comment by Alaric323** [comment]
Basic testing on the release shows that everything up to the Elven portal works.  Don't even need "Hide Models" to be disabled.

**Comment by MrGraphic** [comment]
I did excesive testing and same for me - no issues. Thanks
