### ISSUE TITLE
[1.9.4] Horn of the Wild doesn't break BoP grasses/flowers/etc

### ISSUE THREAD

**Issue by Melakion** [williewillus/Botania#333]
Forge 1954
Botania-unofficial.r1.8-308
BiomesOPlenty-1.9.4-4.1.0.2025-universal

**Comment by williewillus** [comment]
I think BoP doesn't extend the vanilla BlockBush class for their flowers, which means they have to add support for Botania themselves by implementing IHornHarvestable
