### ISSUE TITLE
Cosmetic baubles in strange positions/orientations

### ISSUE THREAD

**Issue by OhiraKyou** [williewillus/Botania#334]
Although not entirely unpleasant, my crotch was not the place I expected to see the puffy scarf. Now, if only it were flat vertically rather than being strangely erect. However, I was very distraught to find cat ears protruding from my eyes.

Minecraft 1.9.4
Forge 1.9.4-12.17.0.1954
Botania Unofficial r1.8-308 (also, the version still has the 1.8 prefix in 1.9)

**Comment by yrsegal** [comment]
Dupe of #49
