### ISSUE TITLE
[1.9.4] Floating flowers have no texture in inventory

### ISSUE THREAD

**Issue by kwpugh** [williewillus/Botania#335]
The Botania Flowting Flowers show the purple/black texture when in player inventory.

Forge: 1957
Mod: Botania-unofficial.r1.8-308.jar

![2016-06-10_11 06 02](https://cloud.githubusercontent.com/assets/8809210/15970749/cd66ebaa-2efb-11e6-9127-ff0ecc5df636.png)

**Comment by williewillus** [comment]
How did you get that?
The texture is fine that's just a corrupted flower (note how it just says the generic 'Floating Botania Flower'j

**Comment by kwpugh** [comment]
The player collected them in a cave, the flowers were floating in the air.   The players reported that their FPS went from 120 to 1 when they got close to them.

**Comment by williewillus** [comment]
Umm interesting. Those don't spawn naturally

**Comment by yrsegal** [comment]
Maybe an id conflict?

**Comment by kwpugh** [comment]
A player captured a pic in the wild

![pfyw0od](https://cloud.githubusercontent.com/assets/8809210/15974410/def819e0-2f0d-11e6-8487-9e541ac30d70.png)

**Comment by kwpugh** [comment]
I don't know the inner workings of forge/minecraft, but I that couldn't happen anymore.

Here is a screenshot with some of the item details.

![2016-06-10_13 21 17](https://cloud.githubusercontent.com/assets/8809210/15974495/5339d410-2f0e-11e6-908f-a6c5c1ccd312.png)

**Comment by williewillus** [comment]
Looks like an ID conflict but those shouldn't be happening anymore 0.o

**Comment by yrsegal** [comment]
Have you removed any mods recently, @kwpugh?

**Comment by kwpugh** [comment]
Actually yes, and it might be an item ID replacement problem.

http://www.technicpack.net/modpack/pughland-unus-novem-194.854226/changelog/300956

**Comment by williewillus** [comment]
yeah that specific flower is supposed to have a missing texture because it's the invalid flower (has no subtile)

I suspect it's an ID conflict so you might wanna check that out. It still bothers me though because those should not happen in 1.7+ anymore
