### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by The-Fireplace** [williewillus/Botania#338]
http://paste.ubuntu.com/17268044/

If you need any other information, let me know, and I will respond as soon as I can.

**Comment by williewillus** [comment]
Are you able to reproduce this?

I think I know what it is, but if there's precise steps then it could tell me something (if there isn't, it tells me something too :D)

**Comment by The-Fireplace** [comment]
No, it doesn't look like I can reproduce it. I loaded the same section of the same world again and it had no issues.

**Comment by hacatu** [comment]
I am getting
[the same error](https://github.com/williewillus/Botania/files/315455/crash-2016-06-15_01.15.29-client.txt) when loading, after the ui is drawn but before any of the world.  I was able to load my world by running Minecraft with the graphics card disabled, and then it worked on the graphics card again.
