### ISSUE TITLE
Solid vines are too solid when facing east or south

### ISSUE THREAD

**Issue by williewillus** [williewillus/Botania#34]
aka cannot be climbed and have a full bounding box

**Comment by kevsgrove** [comment]
Fixed  #123. ~~I don't think a PR is required for 4 lines of code.~~ In common.block.BlockSolidVines.java:

```
public AxisAlignedBB getCollisionBoundingBox(World w, BlockPos pos, IBlockState state) {

        setBlockBoundsBasedOnState(w, pos);

        if(state.getValue(EAST)) {
            return new AxisAlignedBB(pos.add(maxX, minY, minZ), pos.add(maxX, maxY, maxZ));
            //when facing east (so the vine is in the +X part of the BlockPos), omit the minX

        }

        if(state.getValue(SOUTH)) {
            return new AxisAlignedBB(pos.add(minX, minY, maxZ), pos.add(maxX, maxY, maxZ));
            //when facing south, omit the minZ
        }

        return new AxisAlignedBB(pos.add(minX, minY, minZ), pos.add(maxX, maxY, maxZ));
    }
```

Nice to see minecraft still has these silly directional bugs. I still don't know why North/West don't need their maxZ or minX omitted.

**Comment by MaPePeR** [comment]
@kevsgrove you underestimate the effort for: "finding the right file, finding the right place in the file, find out how much of the code needs to be replaced, replacing the code, creating a useful commit message, committing it" compared to pressing the merge button :wink: 

But that's just my opinion.

**Comment by kevsgrove** [comment]
@MaPePeR I was going off of this:

> If your pull request edits very small chunks of code and isn't flawless I'll close it as it'll probably take less time to fix it myself rather than pull yours and change the code.

although it looks like that's Vazkii's writing.

**Comment by williewillus** [comment]
Huh, I wonder why the vanilla vines don't need this

**Comment by williewillus** [comment]
#123

**Comment by kevsgrove** [comment]
Vanilla vines have no collision box, they rely on the player colliding with an adjacent block. For example, an unsupported vine facing north can be climbed if there are blocks to the east, by walking against those blocks.
