### ISSUE TITLE
Two Rings of Chordata compound strangely

### ISSUE THREAD

**Issue by yrsegal** [williewillus/Botania#340]
When you're at least one block above the water's floor, you go up quickly and with no way to stop it. When you enter the water, you fall down extremely fast.

**Comment by yrsegal** [comment]
More specifically, your y-motion is magnified uncontrollably.

**Comment by howtonotwin** [comment]
The reason for this (I think) is that the two rings are magnifying your motion constantly, so much that you don't actually have time to slow down. It doesn't only apply to Y-motion, but all 3 axes. Also, the code for the ring is a bit of a mess in general, and can do with a bit of simplifying.
