### ISSUE TITLE
[1.9.4] Randomly getting Sparks (getting duplicated)

### ISSUE THREAD

**Issue by Xiaminou** [williewillus/Botania#343]
I am randomly looting sparks from this setup, I don't know how to reproduce it, and I don't know what's causing it to happen, but somehow I keep finding sparks on the ground.
![2016-06-13_17 55 46](https://cloud.githubusercontent.com/assets/8670392/16054586/183a587c-326e-11e6-919c-a1f3fe7c2a0a.png)

It seems to be happening when I logout and then log back in, here is what I got today:
![2016-06-14_20 30 38](https://cloud.githubusercontent.com/assets/8670392/16054772/eee191d8-326e-11e6-9fad-15d1bf1cfafb.png)

**Comment by williewillus** [comment]
Can you upload your world for me (and modlist so I know what to run)

**Comment by williewillus** [comment]
Also, what version?

**Comment by GirafiStudios** [comment]
I had something similiar to this happen a couple of time in one of the 1.8.9 versions. Could not really figure out what was causing it though.

**Comment by Xiaminou** [comment]
[Here](https://drive.google.com/file/d/0BxQWn9jKBIAJR3ZUQ1dPMGhnWEU/view?usp=sharing) are the mods and [here](https://drive.google.com/file/d/0BxQWn9jKBIAJS2JGa0tHd2REUlU/view?usp=sharing) is the map,
Alternatively you can join me on my server just PM if you want the IP.

**Comment by G-Stav** [comment]
I'm having a similar issue and I think it's when the chunk unloads/reloads that it happens

**Comment by Xiaminou** [comment]
That would be my guess as well, however it doesn't happen every-time, so there's still some unknown.

**Comment by kingofrunes** [comment]
Just going to chime in and say it's happening for me as well on 1.10 minecraft server. Only when logging in. It's as the previous people here said. Appears to happen on chunk unload/reload. Latest release version (r1.8-312)

**Comment by williewillus** [comment]
Let me know if you still have this issue in the next build
