### ISSUE TITLE
Bauble Shift tooltip causes crash

### ISSUE THREAD

**Issue by nawg** [williewillus/Botania#344]
Holding shift while hovering over any botania bauble causes a crash.

http://pastebin.com/jmh1h8qz

**Comment by yrsegal** [comment]
What, incidentially, do you have as your baubles inventory keybind?

**Comment by nawg** [comment]
I had it set to backslash.  Now that you've brought that up, I tried changing it to other things and it no longer crashes.

**Comment by yrsegal** [comment]
This is still a bug, but that can be a temporary workaround for you.
