### ISSUE TITLE
[1.9.4] Particle Effects and Rendering randomly going white

### ISSUE THREAD

**Issue by Xiaminou** [williewillus/Botania#345]
Another bug which I do not know how to reproduce or why it happens.

![2016-06-14_21 48 33](https://cloud.githubusercontent.com/assets/8670392/16078903/a32c4f88-3301-11e6-8760-206a84a74140.png)
![2016-06-14_23 34 54](https://cloud.githubusercontent.com/assets/8670392/16078902/a32c0fe6-3301-11e6-82f8-dfff0a64108f.png)
![2016-06-14_23 46 28](https://cloud.githubusercontent.com/assets/8670392/16078901/a32b9624-3301-11e6-9850-c7d77eb0036f.png)

**Comment by williewillus** [comment]
do you have Neat installed?

**Comment by Xiaminou** [comment]
Yes I do, it would be my guess as well, I had a similar problem back in 1.8.9.

**Comment by williewillus** [comment]
If anyone wants to take a stab at who's corrupting the GL state go ahead. Can't spot anything in Neat that jumps out to me

**Comment by yrsegal** [comment]
have a debug print for the listeners on renderWorldLast?

**Comment by williewillus** [comment]
I'm saying I'm putting this way on the backburner since there's more things worth the time and it's probably not even our fault so people can look at it other than me :P

**Comment by williewillus** [comment]
https://github.com/Vazkii/BotaniaV2/issues/6
