### ISSUE TITLE
[1.9.4] Solegnolia not working

### ISSUE THREAD

**Issue by Xiaminou** [williewillus/Botania#346]
Solegnolia is having no effect on the ring of magnetization. It has mana, and I am within the radius, but nothing is happening.

![2016-06-15_14 48 07](https://cloud.githubusercontent.com/assets/8670392/16080359/b983e6a4-3308-11e6-9491-16832872af88.png)
![2016-06-15_14 47 17](https://cloud.githubusercontent.com/assets/8670392/16080556/a93b501a-3309-11e6-8a4c-b32e9b37cd94.png)

**Comment by williewillus** [comment]
Cannot reproduce. Solegnolia successfully stops items from being drawn

**Comment by yrsegal** [comment]
This is... 1.7. This is most definitely not a 1.8/1.9 screenshot.

**Comment by williewillus** [comment]
in that case this is invalid

**Comment by williewillus** [comment]
Though I did find a bug in the solegnolia detection algorithm in 1.9, so if this is 1.9.4 the bug's been fixed :P

**Comment by Xiaminou** [comment]
It is 1.9.4, and I don't mean to be rude, but I will anyway Yrsegal, if you don't know what you're talking about, don't talk!

**Comment by Xiaminou** [comment]
Updated to Botania-unofficial.r1.8-310 and it's still not working:

https://youtu.be/PCrvALlTP8M

**Comment by williewillus** [comment]
Still can't reproduce. Make sure a redstone signal isn't touching the flower which turns it off

**Comment by Xiaminou** [comment]
Well I guess I'm gonna have to look for mod interactions then.
there's no redstone signal, was my first though, it has mana, and I have tried in multiple places.

**Comment by Xiaminou** [comment]
Okay, I just tried in singleplayer, works fine. So it's a server side problem.

**Comment by mindforger** [comment]
just by chance, are you using cauldron or any "optimizing mods/plugins" (besides fastcraft, cofhtweaks and optifine which work fine for this) ?

**Comment by Xiaminou** [comment]
No, I tried using SpongeForge but it's not compatible with some of the mods.
Now that I've found out it's server side I'm fairly confident it'd be reproductible with botania alone.

**Comment by Xiaminou** [comment]
Any news on this? have you tried tracking it down? can you re-open the issue until it's fixed please.

**Comment by williewillus** [comment]
I can't track it down because I can't reproduce it. It works perfectly for me.

**Comment by Xiaminou** [comment]
Have you tried on a server like I suggested?

**Comment by williewillus** [comment]
No but I think I see the issue heh

Will fix tonight
