### ISSUE TITLE
Publish Maven Artifacts?

### ISSUE THREAD

**Issue by alexgeek** [williewillus/Botania#348]
Any chance of publishing artifacts to a maven repo? Would really help when using Botania as a dependency.

**Comment by PlasmaPower** [comment]
We could also ship artifacts with the GitHub releases (never messed with maven repos before, they might work better IDK).

**Comment by williewillus** [comment]
Yes, there's a chance - I haven't done maven stuff before but getting it on maven is definitely on the map

**Comment by alexgeek** [comment]
Keep me updated, currently have a solution for locally but it doesn't work on my Jenkins server.
Cheers :+1:

**Comment by williewillus** [comment]
I actually don't know if it's worth doing this because there's been rumblings of vaz picking this back up so I wouldn't want to go through a bunch of effort to do this then he'll have to resetup it all. Closing for now
