### ISSUE TITLE
Botania and BoP clash in latest update?

### ISSUE THREAD

**Issue by McJty** [williewillus/Botania#352]
I updated Botania unofficial and got this when opening a chest containing saplings:

https://bpaste.net/show/72fe5152f61e

**Comment by yrsegal** [comment]
BoP implements item metadata in a strange way. 

https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.9.4-4.1.x/src/main/java/biomesoplenty/common/item/ItemBOPBlock.java#L64-L68

**Comment by yrsegal** [comment]
Specifically the issue is that the stack's metadata is set to 32767. I think I can fix this, I was the one who caused it :P

**Comment by TehNut** [comment]
That isn't a strange implementation in the slightest.

**Comment by tterrag1098** [comment]
`ItemMultiTexture#getMetadata` goes as such:

``` java
    public int getMetadata(int damage)
    {
        return damage;
    }
```

Hard to say it's strange when vanilla does it :P
