### ISSUE TITLE
Botania tooltip causing crashes with several other mods

### ISSUE THREAD

**Issue by The-Fireplace** [williewillus/Botania#353]
Hey, the Botania tooltip seems to be causing crashes with some items from other mods when you mouse over their blocks in the inventory. Here are the reports:
http://paste.ubuntu.com/17424209/
http://paste.ubuntu.com/17424005/
I could probably make more reports with more blocks from more mods if needed. I suggest you use a try/catch setup in whatever code is triggering this.

**Comment by yrsegal** [comment]
bleh, this is my fault but also the mods have silly implementations of item metadata.
