### ISSUE TITLE
Modulating delay

### ISSUE THREAD

**Issue by PaisleyP** [williewillus/Botania#355]
According to the lexicon planting functional flowers on Podzol or Mycellium should add a small delay before picking items up, however this does not appear to be working. I've tested this with a hopperhock for both regular and floating varieties. Version r1.8-308

**Comment by yrsegal** [comment]
Isn't it only with the Boreal Seeds/Infestation Spores on a floating flower?

**Comment by PaisleyP** [comment]
I'm afraid I've tried all ways, unless I'm missing something... I've tried placing a block of podzol/mycellium then planted the hopperhock on top, I've converted dirt using the boreal/infestation seeds then plant on top, I've used the seeds on the floating varieties, I've then tried the regular floating variety placed above the podzol/mycellium and even using seeds on both floating plant and the ground underneath. :(

**Comment by williewillus** [comment]
Cannot reproduce.
A primitive hopperhock setup as follows was built: https://i.gyazo.com/ff74d6cc3f4869addc85a8c9006a8e06.png
In all cases, the grass hock took everything. Followed by the podzol, then the mycelium.

**Comment by PaisleyP** [comment]
Sorry, you're absolutely correct, a grass hock will always take the items first. 

I was trying to automate between a hopperhock and rannuncarpus, aiming to have the rannuncarpus picking the items up first, but with no success. I then moved over to a test world but rather then checking priority of hocks I was trying to see a noticable delay for the items sitting on the ground. My bad.

**Comment by williewillus** [comment]
no prob
