### ISSUE TITLE
Pam's Harvestcraft seeds can't be crafted

### ISSUE THREAD

**Issue by Nattehine** [williewillus/Botania#357]
So yeah, Harvestcraft crops can't be crafted into seeds. I tried crafting it in my inventory and in a vanilla bench with no success. I double checked the config and the croptoseedrecipe setting is set to true but I am still unable to craft them. I am going to check if there is an id conflict and come back to you.

I am currently running the 0.3.0 version of the modpack and forge version 12.17.0.1965. I have not changed any of the configs but I have removed the Spice Of Life mod.

**Comment by yrsegal** [comment]
This isn't a botania issue, is it? ._.

**Comment by Nattehine** [comment]
I checked before I posted this and couldn't find anything on this specific issue, so I assume that it's not.
Also, there is no id conflict that I can find. 
I found another bug: when you right click the harvestcraft gardens you can't pick them up. EnableEasyHarvest is set to true.

**Comment by williewillus** [comment]
You might want to check this repository. This is for Botania, which has not come up once in any of your comments.

If you'd like to report a harvestcraft bug please go to https://github.com/MatrexsVigil/harvestcraft
