### ISSUE TITLE
[Minor] Missing sections of mana bursts

### ISSUE THREAD

**Issue by yrsegal** [williewillus/Botania#358]
Mana bursts often just don't produce particles at small sections near the beginning.
![2016-06-18_14 25 14](https://cloud.githubusercontent.com/assets/6596492/16172912/829c7ec6-3560-11e6-9aed-abbcd76af78c.png)
.

**Comment by williewillus** [comment]
This is because it resyncs to the server position after a certain time is elapsed (observable with snowballs) and doesn't generate intermediary particles when it does so (you'll see it happen more when you're lagging for example)

**Comment by williewillus** [comment]
this is just the resyncing being weird, nothing big and nothing that I know what to do about it :P
