### ISSUE TITLE
No flowers anywhere in the wild

### ISSUE THREAD

**Issue by ellyama** [williewillus/Botania#359]
I'm using Minecraft 1.9.4 with Forge and liteloader and several other mods. 
I've crafted the Lexicon and the pestle and mortar but there isn't one flower to be seen anywhere.
I also have Quark which I downloaded because I was getting a message ingame saying to migrate to vanilla or quark. 
I have no idea why there are no flowers. 
Forgot to mention that I have the very latest Botania download v310

**Comment by williewillus** [comment]
the spawn rate got lowered in one of the final 1.7 versions. It seems to be fine for me and everyone else. Do you have any worldgen mods?

**Comment by ellyama** [comment]
No other world gen. 
However,  I found out that if I started a new world everything was great,  but my interest was in my current world,  and at one point I was exploring and found out that when I went to unexplored parts of my world the flowers started showing up.  So I have nothing by my area but at least I can go further afield to get them

**Comment by MaPePeR** [comment]
Did you add Botania after starting the World?

**Comment by williewillus** [comment]
Yes, the flowers do not retrogenerate.

So this is resolved
