### ISSUE TITLE
[In Progress] Botania-Tinkers integration

### ISSUE THREAD

**Issue by yrsegal** [williewillus/Botania#360]
Current Outline

Manasteel
- Grants _mending_ (not mana repair) that's way way less efficient than the actual enchantment (**Arcane**)
- about iron stats

Terrasteel
- Cool properties with every type of tool
- Mining tools - Axe of the Stream effect (**Worldforged**)
- Weapons - Chance to force the hit entity to the ground and slow for a short time, costs mana (**Worldforged**)
- Other - 50% chance to not take the final 5 durability points but it's weaker during them (**Unyielding**)
- Upwards of iron, but not amazing stats

Elementium
- Weapons - Chance of pixies which go in a line from the player to where they hit, no homing, requires mana (**Elsetouched**)
- Mining tools - void trashy things / do lines of gravel (**Elsetouched**)
- Other - Every time it's repaired from fully broken, its durability increases slightly. (**Alfwrought**)
- Same stats as Manasteel

Livingwood
- About wood stats, provides less durability
- Wood's modifiers, except it selfrepairs faster

Dreamwood
- Same stats as livingwood
- Weapons - More damage the more health the hit entity has (**Idealistic**)
- Mining tools - takes less time to mine the harder the block is to break, more time the easier (**Idealistic**)
- Other - Slightly better stats under the stars (**Stargazer**)

Livingrock
- About stone's stats, worse durability
- Main part - stats change based on the environment. Higher up is higher knockback, lower down is faster for mining. Hotter environments are more damage, and colder environments are slowing to anything hit. (**Elemental**)
- Additional parts - Takes less damage the lower the durability is, to a maximum unbreaking chance of 3 (**Enduring**)

**Comment by williewillus** [comment]
Manasteel
- not sure about this one..why would manasteel now entail mending? :P

Terrasteel
- what do you mean by no gravity?

Elementium
- everything except the tools needs to cost mana 

livingwood
- fine

Dreamwood
- what use does healing instead of harming give you other than a REALLY cheap bypass to potions for healing other things
- what's the point of the mining speed

Livingrock
- Purification: no, you know someone's going to set up one of these to autobash stuff instead of automating a pure daisy properly

**Comment by yrsegal** [comment]
Manasteel -> Mending because it's magic. I feel like it makes enough sense to work.

Terrasteel, no gravity as in the items will float.

Elementium, sure, that was the plan

Dreamwood - aww, I thought it was a neat thing for multiplayer. 
Mining speed was because it needed a cool tool effect, and obsidian

Livingrock, yeah, but I couldn't think of a better alternative :/

**Comment by yrsegal** [comment]
willie, feedback on wiiv's idea for the terra weapon effect?

**Comment by yrsegal** [comment]
I refined the ideas, take another look?

**Comment by yrsegal** [comment]
I actually coded (and balanced) a test version over on [yrsegal/Botania/MC19](http://github.com/yrsegal/Botania/tree/MC19). If you have no complaints with it, I can go ahead and PR it.

**Comment by yrsegal** [comment]
It's been tested to not crash serverside and to not crash when Tinkers is not present.
