### ISSUE TITLE
Elementium pickaxe should destroy 1.8 stones

### ISSUE THREAD

**Issue by luxor-g** [williewillus/Botania#361]

**Comment by williewillus** [comment]
This was discussed at some point but I don't think people came to a conclusion as to whether or not they're valuable enough to void

**Comment by williewillus** [comment]
I guess I'll void them

**Comment by luxor-g** [comment]
Now it even voids sand, which is more valuable, so it should be fine.

**Comment by williewillus** [comment]
turns out they were already on the "semi void" list but the oredict wasn't being checked correctly. fixed now.

9a11ebe
