### ISSUE TITLE
Soulscribe issue, if not then a suggestion

### ISSUE THREAD

**Issue by Hyxaru** [williewillus/Botania#363]
Currently it doesn't affect other end-native creatures. Now I understand not working against the dragon for balance, however it might be interresting to include the endermite and shulker to the list of mobs the soulscribe works against.
Then again the book does specificly quote enderman, though a small line like 'it also seems to have an affect to other creatures alike the enderman, to a lesser effect however.' could work.

**Comment by williewillus** [comment]
it serves its purpose I don't think it needs to be be expanded to the mob no one knows exists, and shulkers aren't really like endermen
