### ISSUE TITLE
Bore Lens not working

### ISSUE THREAD

**Issue by ESClaus** [williewillus/Botania#366]
I was trying to recreate riskable's cake mana farm and bore lens do not break sugarcane.  Is this intended or is this a bug.

**Comment by williewillus** [comment]
Can you link the video?

**Comment by ESClaus** [comment]
Here you go.

https://www.youtube.com/watch?v=21wLyza082Q

I understand this is from 1.7.10 however I didn't think most of it changed that much in later versions.

**Comment by yrsegal** [comment]
I've been able to break sugarcane on the latest version. What version are you on?

**Comment by ESClaus** [comment]
I had it setup with 310 version.  I even broke everything and cheated in stuff just to test and it wouldn't break sugarcane.

**Comment by williewillus** [comment]
cannot reproduce

**Comment by williewillus** [comment]
bore lens works fine on sugar cane

**Comment by williewillus** [comment]
I think I know what you mean now. The Bore REsistance spreaders weren't firing because the burst range got screwed. It'll be fixed next build
