### ISSUE TITLE
Portuguese Blocks recipes messed up

### ISSUE THREAD

**Issue by starg09** [williewillus/Botania#368]
Red, Green, Yellow and Black Portuguese Pavement blocks have wrong recipes for stairs and slabs, all mesed up.
- Red Blocks -> Green Stairs/Slabs
- Green Blocks -> Black Stairs/Slabs
- Black Blocks -> Yellow Stairs/Slabs
- Yellow Blocks -> Red Stairs/Slabs

**Comment by williewillus** [comment]
Woops
