### ISSUE TITLE
Pure daisy emitting light (and melting nearby ice).

### ISSUE THREAD

**Issue by Australican** [williewillus/Botania#369]
A default pure daisy in r1.8-310 emits light as if glowstone, which melts nearby ice.

According to discussion on the matter in IRC, Willie "removed the coloredlights integration because the project's been dead for a year+ and it was taking up space", and "the flowers return -1 by default....which is conveniently 0xFFFFFFFF which truncates to 0xF or full brightness".

Thanks for the consideration.

**Comment by williewillus** [comment]
shoulda fixed this before pushing a build but oh well >.<
