### ISSUE TITLE
Rainbow tracking View Bobbing

### ISSUE THREAD

**Issue by ChloeDawn** [williewillus/Botania#371]
The rainbow in the fancy skybox seems to track Minecraft's "View Bobbing", and wobbles in the sky when walking around. Disabling "View Bobbing" in the video settings makes the rainbow move smoothly across the skybox.

For reference, I am experiencing this on _r1.8-310_ with _fancySkybox.normalWorlds_ set to _true_ in the config, and I am playing in a regular single player world.

**Comment by williewillus** [comment]
this is nearly unsolvable, the rainbows actually render with the sun/moon. If you watch close enough the sun and moon actually bob in vanilla.

See upstream issue: https://github.com/Vazkii/Botania/issues/1705
