### ISSUE TITLE
Ancient wills'  and Terra blade beam's issues

### ISSUE THREAD

**Issue by Hyxaru** [williewillus/Botania#372]
-Ancient wills don't seem to apply at all anymore. I cannot produce the effect.
-Terra blade's beam doesn't work with enchantments, though it used to. I never read in a changelog that it was removed, but it used to apply enchantments like fire aspect. It also worked with the ancient wills.

**Comment by williewillus** [comment]
Terra blade's burst never applied fire aspect, I just tried in 1.7

**Comment by Hyxaru** [comment]
Well that excludes enchantments applying on the beam, I thought it did. How about ancient wills? I am convinced they did apply.

**Comment by EvilZombieLlama** [comment]
cant confirm the others but the will of karil does not seem to be working for me either

**Comment by Lashriel** [comment]
I don't think you can get critical hits with the Terra Beam, can you?

The actual sword-hit does work like that, but I can't seem to get a crit at all with the beam so I'm assuming it doesn't work like that.
