### ISSUE TITLE
Feather feet buff causing damage when in the air

### ISSUE THREAD

**Issue by goroyoshi** [williewillus/Botania#377]
When using a Feather Feet pendant, I take damage randomly when in the air. It was happening with only pendant and band of aura equipped.

**Comment by williewillus** [comment]
what were y[ou using to fly?

**Comment by goroyoshi** [comment]
No flying, just jumping

**Comment by williewillus** [comment]
This is due to this commit https://github.com/williewillus/Botania/commit/a04dfcb15d591d936bbf17898d6c2c5b6002f4cb

and partially due to the fact that you don't have enough mana to constantly sustain the potion effect.

So it runs out when you're midair so you "fall" 3.5 meters and get damaged

**Comment by williewillus** [comment]
not sure if theres a clean solution but a temporary solution is maek sure you have enough mana to keep the effect going without a break

**Comment by williewillus** [comment]
https://github.com/Vazkii/BotaniaV2/issues/8
