### ISSUE TITLE
Ticking player crash when revived with golden laurel crown

### ISSUE THREAD

**Issue by Phizzhead** [williewillus/Botania#378]
https://gist.github.com/Phizzhead/831cdfe75cedecb20e3458add47c34e8

**Comment by williewillus** [comment]
can't reproduce

**Comment by williewillus** [comment]
what potion effects did you have as you died?

**Comment by vladfrangu** [comment]
Did you have any armor that boosts health?

Did you have any potion effects?

You didn't really give @williewillus much info, soo, it can't really be considered a bug, I will try using Blood Magics armor that adds extra health

**Comment by vladfrangu** [comment]
Can't reproduce with Blood Magic / Health boost atribute

**Comment by williewillus** [comment]
No update, closing
