### ISSUE TITLE
Forge 1.10.2 Start-up Crash

### ISSUE THREAD

**Issue by Imnuts7** [williewillus/Botania#383]
Forge: 1.10.2-12.18.0.2002
Botania: unofficial.r1.8-311
https://gist.github.com/Imnuts7/9b13e88ae3bdfaac67e0f3312f7bba46

**Comment by AxolotlAccount** [comment]
same crash happens to me.

**Comment by mindforger** [comment]
@EnderT5 then crashlog please

**Comment by AxolotlAccount** [comment]
https://gist.github.com/EnderT5/c6411c2b2d69860a3bc0a53e7328b821

**Comment by AxolotlAccount** [comment]
please fix it. i want to make a testing pack 1.10.2 but it cant be a good testing pack without botania.

**Comment by williewillus** [comment]
Hopefully should be a one line fix but I can't do it till tonight. Hang in there.

**Comment by AxolotlAccount** [comment]
it is night in turkey now :D

**Comment by williewillus** [comment]
Tonight relative to UTC-5 :P

**Comment by williewillus** [comment]
New build out for 1.10.2, enjoy!
