### ISSUE TITLE
Rod of Bifrost causing lots of server lag

### ISSUE THREAD

**Issue by belathus** [williewillus/Botania#386]
One of the players on the server believes he misclicked with the rod of Bifrost in a random direction, and afterwords I checked the server log and saw that it was generating terrain about 28,000 blocks away. All the players unsurprisingly timed out while the server was generating terrain. Even proper use of this rod seems to cause noticeable server lag, though.

**Comment by williewillus** [comment]
that's definitely impossible, the rod is hard-capped at 100 3x3 platforms, 160 with proficiency. Assuming they all spawn completely spaced out (they don't) it would be 300 blocks max, 480 with proficiency.

Regarding the actual lag, yes that's a problem. I'll probably distribute the block placing over several ticks to alleviate it

**Comment by mindforger** [comment]
@belathus standard forge server or cualdron/bukkit ?

**Comment by belathus** [comment]
Standard forge, 1902. Not sure why the server was generating terrain that
far out, though.

**Comment by belathus** [comment]
I went exploring in the general direction that the rod of bifrost was fired. Over 3000 blocks away, I looked up and saw the bridge, so I'm pretty sure it was, in fact, generating chunks far, far away from where it was fired.

**Comment by williewillus** [comment]
Thanks - pinned it down
