### ISSUE TITLE
Rod of the Black Mesa can easily move Thaumcraft's Aura Nodes

### ISSUE THREAD

**Issue by belathus** [williewillus/Botania#387]
This easily bypasses Thaumcraft's mechanics when it comes to managing vis and aura nodes. It allows you to move the node quickly, for very little mana, without inducing flux, etc.

**Comment by williewillus** [comment]
~~what is the entity class for the node?~~ nvm

**Comment by williewillus** [comment]
Only resolved in 1.9.4/1.10.2 since the 1.8.9 ver has been retired but this won't happen in the future with thaumcraft

**Comment by belathus** [comment]
Bummer that 1.8.9 is retired, but we'll try to make do. Thanks!
