### ISSUE TITLE
Tall flowers drop wrong variants of flowers/don't drop anything

### ISSUE THREAD

**Issue by CrazyManLabs** [williewillus/Botania#388]
I know, that for harvesting tall flowers I have to use shears and this is not an issue.

The issue is different: when I try to grow tall variants of flowers from small ones (using bonemeal) - they are growing as desired. But whenever I try to harvest them with shears - they drop gray/white tall flowers and not that flower, which I destroyed (for example, blue or pink tall flowers). And this is good, if they drop just this, but more times they just drop nothing (just got destroyed and this is it).

Another issue (I think, related to first issue): when trying to use bonemeal on top part of tall flower - it converts to white flower part and this looks strange (bottom part is still from old flower and top is from white). And if try to use bonemeal on bottom part of tall flower - flower sometimes stays, sometimes changes to light-gray variant and sometimes got destroyed without any drop.

Those issues occur on client (single player) and server (multiplayer) sides. Please, fix them.

MC - 1.9.4
Forge - 12.17.0.1976
Botania Unofficial - r1.8-312

**Comment by williewillus** [comment]
I cannot reproduce any of the issues you are describing

**Comment by williewillus** [comment]
1. Growing tall flowers from normal flowers works fine, shearing both halves gives correct color
2. Cannot bonemeal the top half of a tall flower

**Comment by CrazyManLabs** [comment]
If you need screenshots/videos - I can provide them to you (this bug can be easily reproduced on my side)..because it is very strange problem.

**Comment by williewillus** [comment]
If you dont mind, make a world with your testing setup + instructions to reproduce, and send it to me.
Thanks!

**Comment by CrazyManLabs** [comment]
Here it is, world save and MSWord Document with all information (modlist, steps to reproduce and screenshots).

https://drive.google.com/open?id=0BwCtcr24djQnTVBVa2NMcGdlZWc

**Comment by williewillus** [comment]
I simply cannot reproduce this issue in my development environment.

I'm super grateful for your clear report though!

Can you reproduce this issue with botania alone? I think this might be one of your other mods

**Comment by Ryusabre** [comment]
I think I've figured this out, or at least a similar case. The Reap Mod is causing the issue. To solve the problem, add botania:doubleFlower1 and botania:doubleFlower2 to the blacklist in the Reap Mod's config.

**Comment by williewillus** [comment]
cool, thanks for the update, enjoy!

**Comment by CrazyManLabs** [comment]
Yes, blacklisting those IDs fixed this issue. Maybe **@williewillus** need to write about this "feature" on the CurseForge mod page or in README section of repo?

P.S.: Sorry, I can't make a research for this issue because I haven't much time..study and work took all of it.. :(
Thanks anyway, now I can start my holidays..luckily with minecraft and botania without limitations ^^

**Comment by yrsegal** [comment]
That's not botania's fault, though, it's the reap mod's
