### ISSUE TITLE
Feature Request: Crafting With Mana Mirror

### ISSUE THREAD

**Issue by MachiiToya** [williewillus/Botania#389]
I'd like to be able to craft using mana mirror, as an example, let's say I place the mana mirror in my crafting grid and put in a redstone, I would then get mana powder and it would use some mana. Also, I would like to see some modifications for the mana mirror or maybe have the mana mirror read if its linked mana pool has a catalyst for use with this feature.

As an alternate, maybe we could throw redstone on the ground with the mana mirror and an arrow with a check or x pops up like at the mana pool, and when you right click the pile of items with your Wand of The Forest it makes the mana powder depending on whether you have enough mana.

**Comment by williewillus** [comment]
Eh

This could be useful potentially, but whatever it would be it would be world-based, not a crafting recipe. Your second suggestion sounds okay, and I was thinking maybe right clicking on the mirror in hand zaps items on the floor into their result

**Comment by Trcx528** [comment]
How would this interact with alchemy and conjuration?  Would you be able to use a similar mechanic for those?

**Comment by williewillus** [comment]
I feel like I'd just exclude those
