### ISSUE TITLE
Off hand disappearing when crafting duplicate

### ISSUE THREAD

**Issue by Trcx528** [williewillus/Botania#390]
Just a minor bug, when crafting using a runic altar.  If you right click the runic altar with an empty hand it duplicates your last recipe as intended, but also cause any items in your offhand to disappear on the client.  Clicking the offhand slot in your inventory causes the item to return.  This might also apply to the petal apothecary as it uses a similar right click mechanic.

**Comment by vladfrangu** [comment]
This is just a client desync issue.. Probably easy to fix.. I think.

To @williewillus Desync issue? I can't think of anything else

**Comment by williewillus** [comment]
Yes, I need something in forge to fix it

**Comment by yrsegal** [comment]
isn't it just that on the clientside it's taking the item from your offhand but it's not on the server world? wouldn't that just need a check?

**Comment by vladfrangu** [comment]
For instance, as an example, the Yeta Wrench (EnderIO) doesn't do the Shift+RightClick removes machines things with items in offhand. Maybe just disable that altogether?

**Comment by williewillus** [comment]
it's not that simple (to explain at least so I'll spare the details)

it's a fault with the PlayerInteractEvent I made for forge 1.9 so I can't fix this until my fix for that fault gets into forge

**Comment by williewillus** [comment]
#472
