### ISSUE TITLE
Need to know some formats to translate

### ISSUE THREAD

**Issue by vladfrangu** [williewillus/Botania#394]
Mark as help wanted, please!

botaniamisc.color=%s Tinded means something like "Red Tinted" or?

Or better said, %s Something means "Test Something" if %s is Test?

**Comment by yrsegal** [comment]
%s will get replaced by the formatter.

"%s B C", when formatted with "Test", becomes "Test B C".

This isn't an issue, please close this.

**Comment by vladfrangu** [comment]
I couldn't add a tag to it..

**Comment by vladfrangu** [comment]
But thanks!
