### ISSUE TITLE
Spark bug?

### ISSUE THREAD

**Issue by DevilDriver572** [williewillus/Botania#396]
I will be honest, I don't know how or why this is happening. I have a spark over my mana pool and the pool was set to send so I'd refill my band easily.
![2016-07-14_14 48 41](https://cloud.githubusercontent.com/assets/8197944/16851768/074afaf4-49d3-11e6-9f17-e2f409cfb780.png)
Somehow after a certain period of time there would be more sparks on the ground or on the mana pool.
![2016-07-14_14 48 51](https://cloud.githubusercontent.com/assets/8197944/16851769/09dfd320-49d3-11e6-98b6-5b26b73e2b15.png)
Also I'm using 1.10.2 modded with 2007 for forge and r1.8-312 for Botania

**Comment by williewillus** [comment]
Duplicates #343.
Have a fix in the next build that I'm fairly confident will fix it
