### ISSUE TITLE
Horn of the Canopy doesn't drop drops from Roots

### ISSUE THREAD

**Issue by DreadBoy** [williewillus/Botania#399]
It was suggested to me I should report that issue to both mods, here is Roots' issue: https://github.com/elucent/Roots/issues/74. I don't know the cause of this interaction but whenever I use Horn of the Wild in the forest or tree farm leaves don't drop any berries or currants (Roots' drops that should drop from leaves), only saplings and/or apples. As far as I can tell, these drops don't require human interaction to drop.

**Comment by DreadBoy** [comment]
In new version of Roots you need to break leaves by hand to get those drops and I didn't know that.

**Comment by yrsegal** [comment]
You can close this issue yourself, by the way.
