### ISSUE TITLE
Cacophonium does not work.

### ISSUE THREAD

**Issue by luxor-g** [williewillus/Botania#400]

**Comment by Nincodedo** [comment]
What version? What doesn't work about it? Can you reproduce this with just Botania?

**Comment by williewillus** [comment]
More info please

**Comment by luxor-g** [comment]
- Latest botania and forge version (1.10.2).
- It also happens with only botania and baubles.
- It just doesn't work at all, it doesn't reproduce any sound (passive and hostile mobs).
