### ISSUE TITLE
[1.10.2] Crash When Breaking Standing Stone 

### ISSUE THREAD

**Issue by ghost** [williewillus/Botania#404]
Please refer to the issue i posted on elucents issue tracker regarding the above titled crash 

https://github.com/elucent/Roots/issues/78

**Comment by TJOak** [comment]
It looks like you were using a Vitreous pickaxe? You said you tried other picks as well?

**Comment by yrsegal** [comment]
https://github.com/elucent/Roots/blob/master/src/main/java/elucent/roots/block/BlockStandingStoneT2.java#L94

Elu returns null here.

https://github.com/williewillus/Botania/blob/master/src/main/java/vazkii/botania/common/item/equipment/tool/ItemGlassPick.java#L39

`event.getDrops().isEmpty()` is the error, getDrops has to be nullchecked.

**Comment by ghost** [comment]
Yeah it occured using a normal iron pickaxe as well

**Comment by yrsegal** [comment]
that's Elu's fault, then. @elucent

**Comment by ghost** [comment]
He closed the ticket saying it was a botania issue but i will re open the ticket there linking this thanks for the help

**Comment by yrsegal** [comment]
tell him to return Lists.newArrayList() instead of null

**Comment by williewillus** [comment]
waiting on a response from the other end

**Comment by elucent** [comment]
By "other end", are you talking about me? If so, Roots has taken care of this, it'll be in the next update.

**Comment by williewillus** [comment]
alright, thanks a lot! :D
