### ISSUE TITLE
Placed blocks turn into other blocks (workaround: downgrade Forge to 2026-)

### ISSUE THREAD

**Issue by SpectacularNumbers** [williewillus/Botania#408]
Version: r1.8-313 
Modpack: Unstable 4.2.5
Placing the pure daisy turns it into a runic altar. It does not convert any of the blocks placed near it.
When you break the "altar", it turns back into a pure daisy.

https://gyazo.com/bc136afa3d8be727380260292892aa17

**Comment by williewillus** [comment]
Can you do this with botania alone?
Also what forge version are you on?

**Comment by SpectacularNumbers** [comment]
Forge version 12.18.1.2027  (the version unstable is on)

Cannot be replicated with only botania installed.

**Comment by williewillus** [comment]
If possible, can you see if it happens in 2026?

I suspect it's a vanilla bug forge fixed in 2027 that I've been stepping on

**Comment by SpectacularNumbers** [comment]
Works in the unstable pack with the forge version changed to 12.18.1.2026

**Comment by williewillus** [comment]
great, thanks!

**Comment by lilrichy** [comment]
This is happening with all the generating and functioning flowers to me. Only they turn into dark prismatic stairs when placed, and get the flower back when broken. Forge - 12.18.1.2029

**Comment by yrsegal** [comment]
what does WAILA call them in world? what happens when you relog?

**Comment by lilrichy** [comment]
Ok while testing this out a bit i found out that it is only placing the stairs in my server world, waila says it is the stairs not the flowers. Logging out and back in does nothing its still stairs. Breaking the stairs gives back the flower.

In a newly created creative single player world, the flowers place and look correct, but when i log out and back in they are missing the textures "purple and black cube".

**Comment by williewillus** [comment]
@yrsegal you don't need to debug for me, I know the issue :P 

@lilrichy @SpectacularNumbers for now, downgrade forge to 2026 or older, until I can fix it this weekend

**Comment by williewillus** [comment]
Should be fixed in newest build
