### ISSUE TITLE
Some special potatoes don't render properly.

### ISSUE THREAD

**Issue by luxor-g** [williewillus/Botania#409]
The potaoes that have items (like Direwolf20, Etho, etc) don't render them in the right place.

Map with all potatoes: https://mega.nz/#F!Lo1xhKCS!H1cbRNIJGDq2kry_a21-8Q

**Comment by yrsegal** [comment]
oh right, I fixed all the baubles but forgot the potatoes. >.>

**Comment by williewillus** [comment]
@yrsegal wanna fix these as well? xD

**Comment by yrsegal** [comment]
Sure, why not

**Comment by williewillus** [comment]
thanks so much heh, the rendering things are aggravating to do

**Comment by yrsegal** [comment]
do I have permission to fix longstanding minor bugs in the potato while i'm at it? (shia labeouf not stacking with colors, i remember at least one other existing)

**Comment by yrsegal** [comment]
also to shift everything to regex so it's more expandable and safer

**Comment by williewillus** [comment]
yes to the first
no to the latter (why would we need it for one, and for two calling regex in a tight rendering loop is asking for lag and lots of it)

**Comment by yrsegal** [comment]
the second: precompiled regex is pretty fast, and it's needed because some combinations of effects aren't possible without adding regex or complex testing that'd probably be slower

**Comment by williewillus** [comment]
why can't we just do two contains calls?

**Comment by williewillus** [comment]
"pretty fast" is still slower than it is right now :P

**Comment by yrsegal** [comment]
i guess

**Comment by MaPePeR** [comment]
[StackOverflow was recently shut down because of regex](http://stackstatus.net/post/147710624694/outage-postmortem-july-20-2016). 

Even precompiled they can be very slow.

**Comment by williewillus** [comment]
is this being worked on or can I stab at it tonight? (@yrsegal)
