### ISSUE TITLE
[1.10.2] Crash when breaking Botania "Special" flowers with Scythe from BoP

### ISSUE THREAD

**Issue by Carrots4U** [williewillus/Botania#411]
I'm running the latest 1.10.2 Botania build and whenever I attempt to break any "special" botania flower like the Pure Daisy with a Biomes' O Plenty Scythe I get this crash, http://pastebin.com/ECDDfdVx It is reproducible by multiple people running the All the Mods mpdpack, which you can find here, http://minecraft.curseforge.com/projects/all-the-mods

**Comment by williewillus** [comment]
can you do it without optifine?

**Comment by Carrots4U** [comment]
Crash still occurs without optifine, http://pastebin.com/fN3NVvEh

**Comment by williewillus** [comment]
https://github.com/Glitchfiend/BiomesOPlenty/issues/816

**Comment by Carrots4U** [comment]
Thank you for reporting it to the right place, definitely in much more detail than I could.

**Comment by williewillus** [comment]
Closing now as this is a problem that only BOP can handle. Track it on their issue ticket as linked above
