### ISSUE TITLE
Pure Daisy missing texture

### ISSUE THREAD

**Issue by WtfShipoopi** [williewillus/Botania#412]
Updated to the latest version of forge and the mod is completely broken.. 

First things first.. That daybloom has missing textures.. 
![2016-07-29_21 18 37](https://cloud.githubusercontent.com/assets/7692617/17267237/290b0232-55d2-11e6-90f2-a532fab2511e.png)

Further then that placing any flower turns it into the runic alter.

**Comment by williewillus** [comment]
update the mod
