### ISSUE TITLE
[1.10.2] Alchemy Catalyst recipes for stones broken

### ISSUE THREAD

**Issue by Carrots4U** [williewillus/Botania#413]
JEI shows Diorite turns into Granite when thrown into a manapool w/ a Alchemy Catalyst, but instead Diorite turns into Andesite. Andesite is shown to turn into Diorite but instead Andesite just uses mana and stays as Andesite.

**Comment by williewillus** [comment]
Can't reproduce with botania alone - can you find the mod it errors with?

**Comment by Carrots4U** [comment]
Sure I will get back to you, hopefully with an answer!

**Comment by Carrots4U** [comment]
Okay, so when you look into JEI for the mana infusion of Diorite, there are 2 recipes. One of them is just simple Diorite into Granite, but the other one is Diorite into Andesite, but the diorite in that recipe says "accepts any: stone" http://i.imgur.com/KBNqB2v.png, and the other 2 types of stones have the same deal going on, so I'm suspect it's some kind of dictionary issue. Still not sure caused by what.

**Comment by williewillus** [comment]
ah, I see
The smooth stone to andesite recipe is ore dict for some reason so it picks up the other 1.8 stones as well.

Thanks!
