### ISSUE TITLE
Generating Flora Disappears

### ISSUE THREAD

**Issue by psychofad** [williewillus/Botania#416]
mod version: Botania-unofficial.r1.8-314.jar
Forge version: forge 1.10.2-12.18.1.2026

So far I have only tried the Daybloom and the Endoflame, but on a server pack I play on, when I place the generating flower, then teleport away from the chunks using either commands or other teleportation means (RFTools teleporter for example) then return back to the area the generating flora are gone, they do not show up in theoneprobe tooltip, so they don't appear to be invisible, but here is where the weirdness is.  If I say, throw some coal where the endoflame is supposed to be it will still consume the coal and the nearby spreader will start firing bursts of mana.  As the flower is not there, I can not break it by punching the area it is supposed to be, but if I remove the block underneath it, it will drop the flower as an item.  The passive flowers, such as the Daybloom will continue to work as well, but removing the block underneath them will not drop the flower.  This is also happening with the Pure Daisy, but it does not continue to work or drop the flower and just must be replaced entirely.

As I am not the server owner I do not have access to any server logs, but there appears to be no errors in the client log at all. 

I have tried relogging to the server to see if they would show up but they do not.

Also a friend was over when I placed the flower and they said they could not see it right after I placed it, even though I could until I left the chunks.

I am currently playing using the Pughland Unus Decem modpack available on the Technic launcher or as a MultiMC instance from [http://pughland.enjin.com/](url)

**Comment by kwpugh** [comment]
Same server, slightly different outcome.

![2016-07-31_13 15 07](https://cloud.githubusercontent.com/assets/8809210/17278342/df322262-5720-11e6-8243-2a947a94ea27.png)

Forge: 2043
Mod: Botania-unofficial.r1.8-314.jar

**Comment by kwpugh** [comment]
In the pic above, the purple/black blocks are day blooms and exoflames.

They had normal textures when placed.  I let the area and came back about 10 min later.

**Comment by HeavyDeception** [comment]
Its not just Generating Flora its most of the flora Pure Daisy will Despawn when you leave a chunk along with Kekimurus and so on.

**Comment by williewillus** [comment]
yeah there's lots of weirdness with recent forges, I'm going to wait it out a bit more and release another build mid next week

**Comment by williewillus** [comment]
Figured it out. Next build (in a couple days) will have a fix

**Comment by jaquadro** [comment]
@williewillus Could you explain the solution?  I've been getting pelted with similar-symptom reports in Storage Drawers, and would be interested if your solution is applicable.

**Comment by williewillus** [comment]
@jaquadro 

The disappearing:
- Updated forge to 2044+ and it went away

Models disappearing on chunk reload: 
- Made sure my getMetaFromState/getStateFromMeta are truly one to one, had a situation where I was setting a state in a [non-symmetrical manner](https://github.com/williewillus/Botania/commit/072e3a693b87da2376f5ed0ad31cef4b3bfc8cbd#diff-9a4eb8ae05450241235b4b3c74aea496L177)
- Don't set default values for unlisted properties
