### ISSUE TITLE
Botania Crash

### ISSUE THREAD

**Issue by T4ge** [williewillus/Botania#42]
Seems to be a loop crash when I walk too far from the pylons
Crashreport
http://pastebin.com/dmpXkQMc

**Comment by GirafiStudios** [comment]
Update Botania, you're using a build that is like a week old. Pretty sure this got fixed.

**Comment by williewillus** [comment]
yup, you're a week behind! ;p
https://github.com/williewillus/Botania/releases

**Comment by T4ge** [comment]
would you look at that xD will update then :p
