### ISSUE TITLE
Tainted Blood Pendant dupe

### ISSUE THREAD

**Issue by Fey142** [williewillus/Botania#424]
If you place any of the Blood pendants in your off-hand and right-click, it equips it in the pendant slot but one copy still remains in the "off-hand" slot. - Forge 12.18.1.2046, Botania r1.8-315

**Comment by williewillus** [comment]
Is it client side (does it go away on relog?)

**Comment by Fey142** [comment]
It does not, still have 2 items on relog (playing on a private server)
