### ISSUE TITLE
Items despawning

### ISSUE THREAD

**Issue by WtfShipoopi** [williewillus/Botania#425]
When you make your first terrasteel ingot on the Terrestrial Agglomeration plate you cant use spreaders sending manna to it. Other wise the mana-diamond,ingot,peral despawn.

**Comment by williewillus** [comment]
use sparks

**Comment by WtfShipoopi** [comment]
What about people who don't have blaze powder??

**Comment by williewillus** [comment]
by the time you make terrasteel you should long have had nether access...

**Comment by williewillus** [comment]
an alternative option is to use potency lens to increase your spreader throughput. but either way this is by design

**Comment by williewillus** [comment]
the terra plate needs nether access itself to create, so I'm confused as to why sparks are a problem :P
