### ISSUE TITLE
Throwing an EFLN (from Tinker's Construct) at an Entropinnyum still explodes and gives an undefined flower

### ISSUE THREAD

**Issue by zetaPRIME** [williewillus/Botania#427]
...I think the title says about everything on this one.

**Comment by williewillus** [comment]
It only works with TNT (or subclasses of it) by design

**Comment by Lashriel** [comment]
The undefined flower is more a problem than the EFLN still blowing stuff up - the latter is by design.

**Comment by williewillus** [comment]
TiCo bug https://github.com/SlimeKnights/TinkersConstruct/issues/2305
