### ISSUE TITLE
[1.10.2][r1.8-315] Random crash while collecting flowers

### ISSUE THREAD

**Issue by marcin212** [williewillus/Botania#428]
crash log: http://pastebin.com/a38vVzds

**Comment by Fey142** [comment]
can confirm, same is happening to me quite often, escpecially when the flowers are "working" and I break them.

my crash: http://pastebin.com/d2V1dY3U

**Comment by williewillus** [comment]
blargh thought forge had something fixed so I took a safety check out. that'll teach me ><

**Comment by williewillus** [comment]
is this on a server or in SP? I can't get it to happen in SP

**Comment by Fey142** [comment]
Server, and only the client crashes when it happens.

**Comment by williewillus** [comment]
might be a lag thing then, I'll put the check back in. thanks!
