### ISSUE TITLE
Mana Flare Lens not projecting particles

### ISSUE THREAD

**Issue by TropaX** [williewillus/Botania#429]
It seems like the Flare lens is not projecting it's pretty flares, tried on all spreader types.

http://puu.sh/qtVoh/b535ce8da8.jpg

**Comment by williewillus** [comment]
what do you mean, from the burst or from the lens itself? 

Maybe a GIF or video comparing what should be happening vs what actually is happening

**Comment by yrsegal** [comment]
Flare Lenses don't fire bursts, they fire a stream of particles. They're control lenses for that reason.

What should be happening is a long pulsing sin wave of color should be coming out of the spreader.

**Comment by TropaX** [comment]
Can't make a gif/video at the moment, but heres a picture comparison.

This is what is supposed to be happening.
https://pbs.twimg.com/media/CT4oxfIWIAA2_K8.png

This is what is currently happening.
http://puu.sh/quuYw/c9662246ce.jpg
