### ISSUE TITLE
[JEI Integration] NBT Variants show recipes for each item of that ID

### ISSUE THREAD

**Issue by Dijkstra1-zz** [williewillus/Botania#431]
When I look a recipe for one of the flower from Botania it shows me recipes for all flowers I post this [here](https://github.com/mezz/JustEnoughItems/issues/380#issuecomment-238400652), @mezz says you can fix this by use`ISubtypeRegistry`. He said that he would happy to help this.

**Comment by Eufranio** [comment]
This is a very old issue but still there, hope it be fixed :/

**Comment by mezz** [comment]
Ooh, nice use of Java 8 heh
