### ISSUE TITLE
Freezing when loading mods

### ISSUE THREAD

**Issue by McBossKiller** [williewillus/Botania#434]
If i have any other mods used with your mod, other than baubles, My Minecraft will get stuck on loading Botania blocks and items, This has caused my Computer to Crash a few times, yet my minecraft will not crash saying there is memory problems. I really want to use this mod, but this is preventing me to do so.

**Comment by McBossKiller** [comment]
correction, when Forge loads the mods. Minecraft Will not Crash.

**Comment by williewillus** [comment]
Could you give me a log?

**Comment by GabrielCorso** [comment]
How much memory are you allocating to minecraft?

**Comment by McBossKiller** [comment]
I have been experimenting with the mods and found that RFTools is actually the problem, Sorry about that :)
