### ISSUE TITLE
Floral white powder can craft bone blocks

### ISSUE THREAD

**Issue by quat1024** [williewillus/Botania#435]
Which you can craft back into bone meal for free bonemeal.

Uh oh.

**Comment by yrsegal** [comment]
sounds like a forge bug replacing bonemeal with dyeWhite.

**Comment by williewillus** [comment]
dyeWhite being registered for bonemeal is not the bug

**Comment by williewillus** [comment]
the "bug" is just that the bone block should be excluded from forge's OD-replacement pass over vanilla recipes

**Comment by williewillus** [comment]
@quat1024 This is completely out of my control, it's just Forge's OD replacement. This will happen for any mod's items that are registered to `dyeWhite`
https://github.com/MinecraftForge/MinecraftForge/issues/3176
