### ISSUE TITLE
Livingroot block has a messed up model

### ISSUE THREAD

**Issue by quat1024** [williewillus/Botania#436]
Started a new Garden of Glass world and it's decorated with these lovely things.

![2016-08-12_13 25 31](https://cloud.githubusercontent.com/assets/2068021/17631030/4380d632-6090-11e6-8b71-110c696f7ae2.png)

botania:root

**Comment by williewillus** [comment]
Can you do it with Botania alone?

**Comment by quat1024** [comment]
Oops, yeah, happens in regular Botania too.

Livingroots aren't in the creative menu so I did /setblock ~ ~ ~ botania:root, same look.

![2016-08-12_17 50 28](https://cloud.githubusercontent.com/assets/2068021/17638000/521d7252-60b5-11e6-97af-a31710fc5533.png)

**Comment by williewillus** [comment]
0.o

**Comment by williewillus** [comment]
this issue is so wtf, I don't know how to approach it, there is no way that model should be affecting the block 0.o

**Comment by yrsegal** [comment]
Are you registering them both under the name "root"? Since then the item root would be used for the block model.

**Comment by williewillus** [comment]
yes but blockstate jsons should only search in the models/block directory right?

if they search in items, AND search it first, that's the most retarded thing I've ever heard of

Which means that's probably it.

**Comment by yrsegal** [comment]
they don't, huh. i'll try to hunt it down

**Comment by williewillus** [comment]
I'm just going to rename the item model, but submitted an issue to forge in case its a bug
