### ISSUE TITLE
Enchanter uses enchanting table eligibility rules instead of anvil rules

### ISSUE THREAD

**Issue by HeavyDeception** [williewillus/Botania#437]
The shield why cant I enchant it. And other items i can put in and anvil I cant use in the botania enchanter. 

And you cant seem to put thorns on helmets, leggings, and boots.

**Comment by HeavyDeception** [comment]
And you cant seem to put thorns on helmets

**Comment by HeavyDeception** [comment]
Or leggings

**Comment by yrsegal** [comment]
It uses the enchanting table system not the anvil system. You can't apply enchantments you can't get in the enchantment table.

**Comment by HeavyDeception** [comment]
but you can get thorns on the boots, leggings, and helmets?

**Comment by yrsegal** [comment]
with an anvil.

**Comment by HeavyDeception** [comment]
but when you JNI or NEI it it says you can?

**Comment by yrsegal** [comment]
http://minecraft.gamepedia.com/Enchanting#Enchantments

Thorns is primary only for a chestplate, and can be applied with an anvil to the others. Unbreaking can only be applied with an anvil to the shield, so same deal. Whoever made that JEI integration must have messed it up.

**Comment by HeavyDeception** [comment]
Bummer ok but what about the shield and Elytra

**Comment by HeavyDeception** [comment]
I see that there secondary but why is that? its kind of a bummer that you have to use and anvil and loss your enchantment books. is there not a way to add it so you can enchant those items too?

**Comment by HeavyDeception** [comment]
Or a setting.

**Comment by williewillus** [comment]
no configs.

I'll look into it.

**Comment by HeavyDeception** [comment]
Thanks.... At First i was thinking it was a bug now it would be kind of cool to maybe upgrade it in a way so you can enchant anything you can in an anvil too.

**Comment by williewillus** [comment]
4f26ea9 (accidentally put it in with another commit woops)
