### ISSUE TITLE
[1.10.2] Botania client crash with Forge build 2053

### ISSUE THREAD

**Issue by shortybsd** [williewillus/Botania#438]
**Botania version Botania-unofficial.r1.8-315**
**Forge version forge-1.10.2-12.18.1.2053-universal**

I had to update Forge due to JEI, now I have a client crash with Botania. Here is the error:
http://pastebin.com/0a3EVi5n

Server loads fine with no problems. Configs have been updated on the client-side.

**Comment by williewillus** [comment]
is 2053 the exact version of forge where it starts? if not is it possible for you to find that?

**Comment by williewillus** [comment]
and can you get it with botania alone?

**Comment by williewillus** [comment]
my dev environment is on forge 2056 and JEI 3.7.8 and things are working

**Comment by shortybsd** [comment]
Yes, I tried multiple versions of Forge and was getting crazy errors for bucket fluid registry problems but it never specified the mod that caused it. I tried almost every version of Forge and kept getting that same error. I will try 2056 immediately and let you know the outcome. Many thanks for your fast replies!

**Comment by shortybsd** [comment]
**Botania version Botania-unofficial.r1.8-315**
**Forge version forge-1.10.2-12.18.1.2053-universal**
same issue :(
**Client Log**
http://pastebin.com/nb2JJmzN
**Full FML Log**
http://www.shortybsd.org/botania/fml.txt

**Comment by williewillus** [comment]
can you do it with botania alone?

**Comment by shortybsd** [comment]
I sure will, it is probably another mod causing yours to break (modifying your mods NBT tag?) that or no if check was made and it assumed it had a value when it didn't. I will check your code for the error posted to see if a valid if check was made here in a few.

**Comment by shortybsd** [comment]
I loaded your mod alone with no problems. I loaded all the mods I recently updated in my pack and they all work fine. I wonder if it is something with a config. I am going to load all the mods now in MultiMC and see if the issue still happens, will let you know the outcome here in a minute.

**Comment by shortybsd** [comment]
Works fine now. JEI, RFTools, MCMultipart or RefinedStorage configs was part of the issue, not for sure which but loading fine now.

**Comment by williewillus** [comment]
huh, interesting.
the only way would be if something is overriding forge's Item Handler capability, which should be impossible unless a mod is hacking around.
is the issue resolved then?

**Comment by shortybsd** [comment]
Yes sir, hope I don't run into this again. It was a very strange error. Thank you for responding and being the great mod author you are.
