### ISSUE TITLE
Port related issues.

### ISSUE THREAD

**Issue by luxor-g** [williewillus/Botania#439]
Small list of issues I've gathered in one report in order to not make 4 tiny ones.
- Botania's prismarine shard still exits (probably overlooked?).
- Trodden dirt and trodden dirt slab are now pointless.
- Coarse dirt crafting recipe (via botania), its tooltip and it appearing on the botania tab are no longer necessary.
- Chiseled stone bricks and moss stone are now craftable in vanilla.

**Comment by williewillus** [comment]
1. It's a meta variant of manaResource, so I don't feel like just removing one of them leaving a gap
2. They give you a speed boost when walking on them and idk if people want them on the vanilla ones
3. It'll probably stay, noted, noted.
4. They'll probably stay too

**Comment by yrsegal** [comment]
You could setup an onUpdate to set the botania prismarine to vanilla prismarine, maybe? Basically remapping it.

Trodden stuff is visually different than the vanilla stuff, it should stay.

Coarse Dirt doesn't feel alchemical, since it's merely a mix of gravel + dirt, so I feel it shouldn't stay.

The others sound fine :P

**Comment by luxor-g** [comment]
I think the recipe for moss stone should be removed/ changed. The vanilla recipe is cheaper (1 vine instead of 9) and only require one step.

**Comment by vladfrangu** [comment]
First of all, crafting Prismarine is amazing. Recipe wise, of they are
conflicting, make them interchangeable. So minecraft prosmarine blocks turn
into botania prismarine blocks.

As for the mossy stuff.. How bout you make it 8 non-mossy but the same kind
of material and 1 vine, so you would get some more

**Comment by williewillus** [comment]
okay the verdict is
- removing coarse dirt tooltip, spawner tooltip, coarse dirt from creative tab
- removing moss stone recipe

All else will stay as is for now

ba3f337
