### ISSUE TITLE
Aiming at a block while collecting dragon breath also collects ender air

### ISSUE THREAD

**Issue by EnderiumSmith** [williewillus/Botania#440]
If you have a block selected when clicking on the dragon breath location a second bottle is used for ender air. It should not result in ender air if a dragon breath was collected.

**Comment by williewillus** [comment]
I need MinecraftForge/MinecraftForge#3070 to be merged before I can fix this

**Comment by EnderiumSmith** [comment]
@williewillus cant you search for nearby ender breath? This will also cover missing the hitbox of dragon breath.

**Comment by williewillus** [comment]
#472
