### ISSUE TITLE
End to end SideOnly check

### ISSUE THREAD

**Issue by williewillus** [williewillus/Botania#443]
- [x] Blocks
- [x] Items
- [x] Entities
- [x] Other

**Comment by mindforger** [comment]
would you care to give a minute of your time and write line of explanation? i am interested :) as a friend currently experiments with sponge and wants to add EIO

thank you very much

**Comment by yrsegal** [comment]
It's an internal modding thing, if a sideonly method that wasn't marked sideonly at some point is reflected it crashes.
