### ISSUE TITLE
[1.10.2]Client Crash Rendering SpecialFlower ??

### ISSUE THREAD

**Issue by ghost** [williewillus/Botania#445]
Not sure which flower its referring to I teleport to a freinds base and my client crashes only 

Crash Report [Gist](https://gist.github.com/Stuart74/d73f10b871c883594e2d13e22a3d28c3)

Forge Version: 2056
Botania Version : 1.8-3.1.5

**Comment by ghost** [comment]
I was told to report this if i had this flower in my inventory 

[Screenshot](http://puu.sh/qDfhe/89430a62db.jpg)

**Comment by williewillus** [comment]
update to 316

**Comment by ghost** [comment]
still got the rendering problem it just does not crash the client this time round. It has no texture and still get that flower that says report it

**Comment by yrsegal** [comment]
That flower is permanent, though

**Comment by williewillus** [comment]
yeah unless you can redo the steps that gave you it, just trash it.

**Comment by vladfrangu** [comment]
Why is that flower even in the code still? Is it useful for anything? It looks like a Poppy

**Comment by mindforger** [comment]
it's purpose is to bring people like you to ask why you have them in the first place and the details help to nail down the issue :) works absolutely brilliant IMHO

when everything works fine, you will never see it, when there is something borked it will appear and help to debug everything

**Comment by williewillus** [comment]
@KingDGrizzle it's simply a magic flower with no identifying NBT data attached, so I can't make it go away even if I wanted to :P 

Giving it a good appearance + tooltip to report seems to be working
