### ISSUE TITLE
[Suggestion]Comparator in Alchemy Catalyst

### ISSUE THREAD

**Issue by Susjin** [williewillus/Botania#446]
In Botania 1.7.10, if you put an comparator not in the mana pool, but in the Alchemy Catalyst, it will do the same thing as if it is the the pool, if you can implement this, it would be awesome!

**Comment by yrsegal** [comment]
This was never explicitly defined in the Alchemy Catalyst. Do you have any
pictures of it working as you state?

**Comment by Susjin** [comment]
I don't have pictures but i remember doing it in the Direwolf20 pack, but i used Project:Red comparator, i don't know if that was it fault, but it worked

EDIT: Also worked in FTB Infinity Evolved Skyblock

**Comment by vladfrangu** [comment]
I don't remember Dire doing that, in his modpack.. He did it on the side as far as I can remember

**Comment by Susjin** [comment]
I didn't said that Dire did it, but i said that i did it, in his modpack

**Comment by vladfrangu** [comment]
Was there a block next to the mana pool and above the comparator? Was the comparator on the alchemy catalyst?

**Comment by Susjin** [comment]
I don't think so, the Project:Red comparator can be put in walls, so the mana pool was in the middle of the room, at it botton was the Alchemy Catalyst, and at the bottom of the alchemy catalyst was the comparator(placed in the wall), that emit the signal

**Comment by vladfrangu** [comment]
If you can re-build it and screenshot it, that would be awesome

**Comment by Susjin** [comment]
I'll try

**Comment by Susjin** [comment]
Here it is, and now i figure that if the comparator is placed on the side of the catalyst it does not work, because i never tried it

https://imgur.com/a/1gzD1

**Comment by vladfrangu** [comment]
I'm pretty sure thats vanilla

**Comment by vladfrangu** [comment]
And its still in the came. Soo

**Comment by williewillus** [comment]
Someone explain concisely and clearly what exactly this is asking for, because I can't see it :P

**Comment by williewillus** [comment]
Otherwise this is being closed

**Comment by yrsegal** [comment]
nothing. he's asking for an existing vanilla feature to exist.

**Comment by vladfrangu** [comment]
Yep.. In vanilla. If you place a comparator next to a solid block next to a block that can output a comparator signal, it can pull it. And he thinks its a 1.7 feature
