### ISSUE TITLE
Crash on joining server

### ISSUE THREAD

**Issue by robaimes** [williewillus/Botania#451]
This issue is extremely minor and probably would not be widely come across. Basically, having Botania installed client side and trying to connect to a server that does not have it installed will result in a crash.

As I said, an uncommon occurrence. But, as an example, modpacks distributing through ATLauncher have 'Optional mods'. A server may not chose to install this, but a player might have done. This is an instance where this issue would occur.
- Crash: http://pastebin.com/60FKrJrb 
- JEI Issue: https://github.com/mezz/JustEnoughItems/issues/401

Relevant mod versions:
- `forge-1.10.2-12.18.1.2065-universal`
- `jei_1.10.2-3.9.0.245`
- `Botania-unofficial.r1.8-316`

**Comment by vladfrangu** [comment]
Well.. Why would you install a mod that the server doesn't have?
You won't be able to use said mod anyways soo

**Comment by Sataana** [comment]
Usercase:

Install a modpack with over 250 mods, 100+ are optionals
You have access to 5 different servers, some have Botania, some dont.
All variants of the same modpacks, just different optionals enabled / / disabled

**Comment by vladfrangu** [comment]
Well, still.. I don't think this can be classified as a "bug". Make more instances for each server.

**Comment by vladfrangu** [comment]
MultiMC would help you for this

**Comment by robaimes** [comment]
As I said, a minor issue. but it is an issue that users would encounter in the scenario I outlined.

But I don't recall other mods having this behavior.

**Comment by vladfrangu** [comment]
Well, true. I recall joining a vanilla server with TheOneProbe without crashing.

Back to the topic.

It might be a JEI - Botania - Client Side issue, maybe due to items being available client side? Cause you won't be able to use the mods, and will give A LOT of isues

**Comment by robaimes** [comment]
That's why it's been reported to both sides, as per the OP there is an open issue on the JEI repo.

**Comment by vladfrangu** [comment]
I saw xD

**Comment by williewillus** [comment]
Not sure what the best solution is here, and it's such a niche case.

FML should be blocking you from connecting so it might even be an issue there.

If anyone has ideas hit up the forge or botania v2 repos
