### ISSUE TITLE
UPDATE: Missing texture on Shields with Added Item Banners

### ISSUE THREAD

**Issue by LGcommisar** [williewillus/Botania#453]
EDIT: Not a bug - Just missing textures.  I knocked out a set of them for you to use, if you'd like.

![2016-08-23_23 07 44](https://cloud.githubusercontent.com/assets/21146965/17917034/97ce7bdc-6986-11e6-8564-8da20418e73a.png)

**Comment by williewillus** [comment]
make a pull request so your name can be on the contribution log :)

**Comment by LGcommisar** [comment]
Just figuring out this Git stuff, pull request incoming.
