### ISSUE TITLE
Crash with Guardian

### ISSUE THREAD

**Issue by utoc** [williewillus/Botania#457]
Primary crash: http://pastebin.com/CqJM1Rz5
Crash when chunks with guardian were reloaded: http://pastebin.com/kKRSs0nv
And another crash for good measure: http://pastebin.com/sXt6B0hN

Running Botania-unofficial.r1.8-317 on FML 2073

If you need full server logs, please don't hesitate to let me know.

The user that initiated the fight has done this on the sever now 6 times he said; this time after updating to 317 seems to gone awry.  I don't have any other information but am available for any troubleshooting.  At this point the server is unplayable and I will have to use MCEdit to remove the entity.

We've tested this in SSP and it doesn't seem to be an issue, only multiplayer and only this one time.. which happens to be the first Gaia fight after updating to 317 with FML 2073 (we previously ran 2068)

EDIT: After clearing the offending entity from the players region file; he made a second ingot and the crash repeated itself just the same.

EDIT EDIT: And this is the boss made with the Gaia ingot.  2.0 Gaia.

EDIT^3: We tested Gaia 1.0.  Crashtastic in the same manner.

**Comment by williewillus** [comment]
fixed in 318
