### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by gchpaco** [williewillus/Botania#459]
Looking at the source I'm not sure how this could happen, but it's crashing every time I try to load the world for me.

[crash-2016-08-26_09.07.54-server.txt](https://github.com/williewillus/Botania/files/440098/crash-2016-08-26_09.07.54-server.txt)

**Comment by williewillus** [comment]
a mod's machine or something is returning `true` from `hasCapability` but `null` from `getCapability`
 <.<
https://github.com/williewillus/Botania/blob/master/src/main/java/vazkii/botania/common/item/equipment/bauble/ItemItemFinder.java#L174

Are you playing on a modpack I can readily install? 

If so I could get your world and do more extensive debugging

**Comment by gchpaco** [comment]
All The Mods.  I can send it to you.

**Comment by williewillus** [comment]
Awesome, throw it up somewhere and i'll take a look

**Comment by gchpaco** [comment]
Sent privately (don't want to overwhelm my dropbox).

**Comment by williewillus** [comment]
It's an IE tile entity being finicky, Refer IE ticket ^

For now if anyone has a "Spectator" bauble equipped you can edit it out of their Bauble inventory with an NBT editor to unbreak the save
