### ISSUE TITLE
[feature request] 1.10.2 add config option to turn off all shedding

### ISSUE THREAD

**Issue by Zygus42** [williewillus/Botania#464]
1.10.2 - please add a config option to turn off all shedding.  When a lot of mobs are added, the list becomes so large that finding the entries for the vanilla mobs in order to stop their shedding becomes a chore.  Alternatively make the default for all vanilla mobs to have their shedding off and let people switch them on manually.

**Comment by williewillus** [comment]
Wait so is your problem that you want to disable all shedding or you want to disable all vanilla shedding?

**Comment by williewillus** [comment]
The first is easy with a pinch of regex on the config file

**Comment by Zygus42** [comment]
I would like to turn off all shedding, but most of the shedding is turned off by default already.  The only ones that are set to a number in the default config file are the vanilla mobs.

**Comment by esotericist** [comment]
A hard override in the main config list would be very helpful. Similar to how quark's config has a 'turn off this feature' setting separate from the individual entries
