### ISSUE TITLE
Dupe with band of mana

### ISSUE THREAD

**Issue by MasterZeddicus** [williewillus/Botania#466]
When wearing a Band of Mana, with a band of aura (or any item that passively generates mana to a tablet.)  Occasionally removing the band of mana will create a dupicate.  This is in botania v.1.8-320  Can be use very abusively while dropping onto a mana pool to generate mana.
Reproduction of this Dupe:
Get band of mana
Get band of aura
Charge band of mana
Click the band of mana in and out of the baubles slot a few times.

**Comment by williewillus** [comment]
This is simply a critical fault with how baubles is coded (sharing things between client and server the wrong way) and is quite beyond my control. I'll investigate in more detail if it's my fault but I doubt there's anything to be done about it. 

Which makes me want to drop baubles even more but that's a problem for another day ;P
