### ISSUE TITLE
Inventory icon for Livingwood Avatar is missing

### ISSUE THREAD

**Issue by CrazyManLabs** [williewillus/Botania#467]
As title states, there is no icon in inventory for this item:
![Inventory in creative](https://cloud.githubusercontent.com/assets/11625072/18083654/b3f37008-6eac-11e6-8a7e-31e76ffee683.png)
![Inventory in survival](https://cloud.githubusercontent.com/assets/11625072/18083846/a51818b2-6ead-11e6-99cd-7e55eb288812.png)
But model of this item is visible, when placed in world:
![World](https://cloud.githubusercontent.com/assets/11625072/18083655/b40cde8a-6eac-11e6-95b1-584cab7193f0.png)

Specs:
MC 1.10.2
Forge 12.18.1.2076 (latest)
Botania r1.8-320

I think, this issue is [low-priority], but as I noticed it - you might be interested in it :)

**Comment by vladfrangu** [comment]
This has been noticed with the Coocoon too! (Or however you say that);

**Comment by williewillus** [comment]
adf0d08

**Comment by vladfrangu** [comment]
Well, I've found a bug, that I wasn't expect to.. Yey
