### ISSUE TITLE
Floating flowers: FPS drop + [Possibly Unrelated | Optifine] [Strange bug] Crash with connected textures enabled

### ISSUE THREAD

**Issue by CrazyManLabs** [williewillus/Botania#469]
The first part of this issue is pretty much straight forward:
With only Forge and Botania installed I faced with FPS drop (in the past I never noticed this problem). FPS drops whenever I place/break Floating Flower, but a little bit later (maybe half a second or so) after that FPS returns to its' normal value. But _sometimes_ game "lags" only on first flower placed or last flower broken (by "first/last flower" I mean that there is no other flowers in the world before placing/after breaking)..

---

The second part is..IDK..very strange and new to me.
It can be reproduced like this:
1) Install MC + Forge + Botania + OptiFine (I leaved all my mods enabled, but it can be reproduced just in this combination)
2) Enable "Connected Textures" feature in OptiFine
3) Start game, load world (I tested only in flat world with "Redstone ready" template, so maybe only sandstone walls can cause this problem)
4) 2 possible ways here:
4.1)
Place 2 Floating Flowers on the ground next to each other
![2016-08-31_18 06 01](https://cloud.githubusercontent.com/assets/11625072/18134189/4431238c-6fa6-11e6-87e4-4c70af280fc0.png)
-> Break block under/near them (on screenshots blocks, that need to be broken, highlighted)
![2016-08-31_18 06 13](https://cloud.githubusercontent.com/assets/11625072/18134187/44308efe-6fa6-11e6-8ae5-5d60fa027938.png)
![2016-08-31_18 09 46](https://cloud.githubusercontent.com/assets/11625072/18134190/4433bff2-6fa6-11e6-978b-dc9d0e44043f.png)
 -> Instant crash

Here are screenshots, where you can see, that blocks, that are further away from flowers, can be broken without any problem..
![2016-08-31_18 06 05](https://cloud.githubusercontent.com/assets/11625072/18134188/4430fe84-6fa6-11e6-93d3-e1253326c993.png)
![2016-08-31_18 09 43](https://cloud.githubusercontent.com/assets/11625072/18134191/4435d440-6fa6-11e6-95fa-217ee21cec4a.png)

4.2)
Break some blocks in one line
![2016-08-31_18 18 20](https://cloud.githubusercontent.com/assets/11625072/18134535/5f987bf6-6fa7-11e6-9930-1ab82175b36d.png)
-> Place Floating Flower on edge of this gap
![2016-08-31_18 18 30](https://cloud.githubusercontent.com/assets/11625072/18134534/5f7cbaa6-6fa7-11e6-819f-c6bec5dedad2.png)
-> Instant crash

I think this issue is optifine-related, but (as I told below) it never happened before.. And another reason for open issue here is part of log, that contains calls of botania methods on top of call-stack:
`
java.lang.NullPointerException: Tesselating block model
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)
    at com.google.common.collect.StandardTable.put(StandardTable.java:138)
    at com.google.common.collect.HashBasedTable.put(HashBasedTable.java:55)
    at vazkii.botania.client.model.FloatingFlowerModel.getModel(FloatingFlowerModel.java:135)
    at vazkii.botania.client.model.FloatingFlowerModel.func_188616_a(FloatingFlowerModel.java:104)
    at ConnectedTextures.getNeighbourIcon(ConnectedTextures.java:1325)
    at ConnectedTextures.isNeighbour(ConnectedTextures.java:1284)
    at ConnectedTextures.isNeighbour(ConnectedTextures.java:1264)
`
I think, that latest changes in Floating Flowers can cause this problem (possible "caching models" feature (as I can call it from code) or maybe new models causing it), but I can't tell, if I'm right.

CrashDump:
[crash-2016-08-31_18.18.35-client.txt](https://github.com/williewillus/Botania/files/447615/crash-2016-08-31_18.18.35-client.txt)

---

Specs:
MC 1.10.2
Forge 12.18.1.2076
Botania r1.8-320
OptiFine 1.10.2_HD_U_C3

**Comment by williewillus** [comment]
This is an issue with connected textures. My model's getQuads is being passed an IBlockState with no Extended State data filled in (i.e. connected textures is asking Botania for the model of a floating flower, without specifying the type of flower nor the island type)
