### ISSUE TITLE
Garden of Glass End Portal unbreakable

### ISSUE THREAD

**Issue by Theta-Dev** [williewillus/Botania#470]
I noticed that the craftable End Portal Frame in Garden of Glass can't be broken in Survival Mode.

I don't think this to be very clever, because it might lead to griefing, trolling or simply misplacements. Could you change this and make the End Portal Frame breakable if you are in a Garden of Glass World?

Maybe you could also remove the crafting recipe for the vanilla end portal and add a new way to get to the end (similar to the end cake from Ex Astris).

**Comment by vladfrangu** [comment]
Cause it crafts the vanilla block, and its unbreakable. Maybe a pick or a tool to pick it up and move it would be interesting
