### ISSUE TITLE
Crash to Desktop when putting tools in crafting grid

### ISSUE THREAD

**Issue by psychofad** [williewillus/Botania#471]
forge-1.10.2-12.18.1.2076
Botania-unofficial.r1.8-320

Like the title says, when I put pickaxes, shovels, or axes into the crafting grid from Mekanism or Cyclic (only ones I have tested so far, vanilla are fine) I get crashed to desktop with the following crash report.

[http://pastebin.com/Bg5VYC5Z](http://pastebin.com/Bg5VYC5Z)

I am posting this here because Botania is the common denominator and if I remove Botania this does not happen.  I posted this issue for Mekanism on his github and he said it was not his issue.

**Comment by williewillus** [comment]
Could you Link the mekanism ticket?

**Comment by vladfrangu** [comment]
I don't know if this is the issue. But were you trying to apply a ivy on an emerald pickaxe? Maybe that caused the crash, since you said that when removing Botania, everything was fine

**Comment by psychofad** [comment]
@williewillus 

sure thing, here ya go [https://github.com/aidancbrady/Mekanism/issues/3704](https://github.com/aidancbrady/Mekanism/issues/3704)

@KingDGrizzle 

No, actually i was going to add enchantments using enchantment tokens from Silent Gems mod, but as soon as I put the pick into the crafting grid it crashed me to desktop ( I never had a chance to put anything else into the crafting grid)

**Comment by vladfrangu** [comment]
Maybe its AGAIN a tool that hasn't properly assigned its repair material?

Not an expert, so what I'm asking might NOT be the case

**Comment by psychofad** [comment]
well, the Mekanism author did not think so, and this is happening with a bunch of different mod's pickaxes, so since Botania is listed in the crash log of every one of them I thought it best to address it here first, then if all the other mods just have it wrong, at least then i can reference this issue going forward.

**Comment by psychofad** [comment]
For completeness I have also notified the Cyclic author of the issue so he can look into it on his end.

**Comment by williewillus** [comment]
this is whoever that tool's mod author not setting their ToolMaterial's repairMaterial properly.

**Comment by psychofad** [comment]
Ok, I will update the other issues with that information.  Thanks!

**Comment by Lothrazar** [comment]
Sorry for the trouble.  I am dumb.  I forgot to add

`TOOL_MATERIAL.setRepairItem(new ItemStack(Items.EMERALD));`

EDIT: fixed in Cyclic release 1.7.4. for future referenc:  https://github.com/PrinceOfAmber/Cyclic/issues/88

**Comment by williewillus** [comment]
no prob
