### ISSUE TITLE
[1.7.10] Crash when going through the Thaumcraft interaction page in the Lexica

### ISSUE THREAD

**Issue by chaos234** [williewillus/Botania#476]
First things first, the crash report: https://paste.ee/p/CErKZ
Referenz to #69 because it is indeed the same problem which should be fixed from what I have seen with your commit.

Cur. Version: Botania 1.8-249

I am not sure why but after the try to switch to the next page (Brew Recipe Page) my client crashes, even with and without optifine installed (only to force out a problem with it).

I am not sure if you'll provide any fixes for this, if there is a fix possible but if so and even if we are straigth going to MC 1.13 and having MC 1.10/1.12 it would be great to get this bug fixed.

**Comment by williewillus** [comment]
The commit that fixed the linked issue was to fix interactions with TC5 in 1.8, so I'm not sure if it's the same issue.

Either way, this repository is inactive, and unfortunately new 1.7 releases are no longer being made
