### ISSUE TITLE
Lexica Botania 1st person item model

### ISSUE THREAD

**Issue by williewillus** [williewillus/Botania#5]

**Comment by meelock** [comment]
also whats with the m8 spam... its kind of annoying.

... fyi i was not trying to be annyoing or anything...

**Comment by GirafiStudios** [comment]
Dude, it's his repo. The issues made is used as a reminder..

**Comment by williewillus** [comment]
I kindly ask that you only post useful things on this tracker and not random ~~junk~~ stuff I don't understand.

Debug output is to be expected in debug builds, it's for my personal use (I'll disable it, but please be clearer next time about what you want :P)

If you need to reach me find me on IRC.

**Comment by williewillus** [comment]
64e1282

**Comment by williewillus** [comment]
reopining for 1.10 (should've reopened it a long time ago, I keep forgetting because there's no ticket for it)

**Comment by williewillus** [comment]
4552a45

**Comment by CrazyManLabs** [comment]
Today I updated MC to 1.10.2 (Forge, Botania, all other mods were downloaded and installed today too) and can't see lexica model/texture in my hand at all.. :( When I choose it in my hotbar - hand disappears, but lexica not appering instead. I don't know, if it is my side fault or what.

Screenshot 1 - Regular lexica selected (No model, texture or hand)
![screenshot 1 - regular lexica selected no model texture or hand](https://cloud.githubusercontent.com/assets/11625072/17437952/2ba78ca2-5b29-11e6-9dc8-6e44b8fdb02a.png)

Screenshot 2 - Regular lexica opened (No model, texture or hand)
![screenshot 2 - regular lexica opened no model texture or hand](https://cloud.githubusercontent.com/assets/11625072/17437953/2ba94a24-5b29-11e6-842a-c28a136b97c1.png)

Screenshot 3 - Lexica with elven knowledge selected (No model, texture or hand)
![screenshot 3 - lexica with elven knowledge selected no model texture or hand](https://cloud.githubusercontent.com/assets/11625072/17437950/2ba73194-5b29-11e6-8d30-e309bd389931.png)

Screenshot 4 - Lexica with elven knowledge opened (No model, texture or hand)
![screenshot 4 - lexica with elven knowledge opened no model texture or hand](https://cloud.githubusercontent.com/assets/11625072/17437954/2bad5ef2-5b29-11e6-91d9-4ec71c63931f.png)

Screenshot 5 - Nothing selected (Hand model)
![screenshot 5 - nothing selected hand model](https://cloud.githubusercontent.com/assets/11625072/17437951/2ba748b4-5b29-11e6-9b07-33faba53dc99.png)

If need configuration:
MC 1.10.2
Forge 12.18.1.2046
Botania r1.8-315

P.S.: Disabling minimap not solving the issue.. :\

P.P.S.: This is screenshot from 1.9.4 with Botania r1.8-313 and Forge 12.17.0.1976
![screenshot 1 9 4](https://cloud.githubusercontent.com/assets/11625072/17438362/24751c90-5b2b-11e6-8bab-6245d83eb091.png)

~~UPDATE: this is on my side, disabling all mods fixes issue..so I will determine, what causing it..
UPDATE2: it was Optifine. Hmmm.. I will try to configure it :\ Nope, I can't fix it.. may be optifine changes graphics engine to much :(~~
UPDATE3: latest version of OptiFine (1.10.2 HD U C3) fixes issue with models, now all of them drawing correctly :)
