### ISSUE TITLE
Botania's own versions of andesite, diorite and granite aren't necessary anymore in 1.8

### ISSUE THREAD

**Issue by NerdMcBoon** [williewillus/Botania#51]
I never really played the 1.7.10 version of Botania, but I guess it adds it's own versions of the new vanilla 1.8 stone types? They are still in your port, but aren't really needed anymore, as 1.8 already has them by default.

![botaniagranite](https://cloud.githubusercontent.com/assets/16770970/12423043/f3bae952-bec9-11e5-9358-32f3f9b9723c.png)

Also, the recipe for the brick versions of andesite, diorite and granite, that Botania adds, collide with the vanilla 1.8 recipes for the polished versions of the blocks.
Currently the brick version of andesite, for example, uses 4 andesite, which is also the vanilla recipe for polished andesite, so the brick versions aren't craftable at the moment.
My suggestion would be to change the recipe from 4 andesite/diorite/granite to 4 polished andesite/diorite/granite, that wouldn't make the recipe more expensive and it would work.

It's really just a small thing, and I understand how this can be easily overlooked in a port, but I thought it couldn't hurt to report it.

Keep up the good work!

**Comment by yrsegal** [comment]
they're there for backwards compatability.

**Comment by williewillus** [comment]
^^ yup so people's buildings don't mysteriously vanish. also, there's 1:1 recipes to turn everything into vanilla.

the recipe conflicts were also there in 1.7.10, not sure how to resolve them yet.

**Comment by TheWhiteWolves** [comment]
this will probably need a bigger discussion later on whether they stay in or are removed, vaz's decision in the end i guess, but for now a suggestion @williewillus could be to remove botania's recipes (obviously leave in any that are legit ones we added that vanilla didn't), then phase out their use, eventually everyone will use the vanilla ones (you might want to give them ore dict entries if they dont already to maintain compatability aswell)

**Comment by williewillus** [comment]
I've already done all of what I can which is
1. One to one recipes from botania to vanilla where applicable
2. All recipes in botania switched to either OD (with both registered) or using vanilla materials.
3. Recipe conflicts from upstream left as-is

**Comment by TheWhiteWolves** [comment]
you could remove/comment out the registering of the crafting recipes for the botania stuff, the ones from upstream (basically any we added) and remove the world gen of them maybe?

**Comment by williewillus** [comment]
Already did, all stuff that vanilla + botania both have, you can't make the botania variant anymore (now rare and collectible! (tm) )
We don't worldgen, all the stuff is mana infused.

**Comment by yrsegal** [comment]
an idea: make it so whenever you break a botania block with a relevant vanilla counterpart, it becomes the vanilla version when dropped. pick blocking should work the same way; the botania versions shouldn't be found in creative.

**Comment by TheWhiteWolves** [comment]
thats a good one, eventually they should be able to be phased out and noone (hopefully) will notice

**Comment by yrsegal** [comment]
would it be possible to tick the block and replace it with the vanilla variant? same with the item form of the block, in-inv.

**Comment by williewillus** [comment]
that's probably not going to be very performant, a better way would probably be to remove the block then insert a substitution into the registry pointing towards vanilla.

but as we've said, this isn't a particularly high priority issue, I'll deal with it when everything else has been ironed out.

**Comment by NerdMcBoon** [comment]
Ahh, I guess I should have checked if the 1.7.10 version has the same problem before reporting. Sorry about that!

For now, I just removed the duplicate and uncraftable blocks from JEI, which works just fine. Maybe I'll add a recipe for the bricks using CraftTweaker as well.

I don't quite understand how the recipe conflicts could be in 1.7.10 as well, though. 1.7.10 didn't have the andesite, diorite and granite blocks, they were introduced in 1.8. The Chisel mod also added those blocks to 1.7.10, so maybe that's were the conflicts were coming from?

**Comment by williewillus** [comment]
Botania added them in 1.7

**Comment by williewillus** [comment]
gonna close this as a non-issue there's already migration mechanisms in place, and the conventional software thing to do is to deprecate in one version, remove in the next. so consider the botania 1.8 things to be "deprecated" and they'll get removed a couple major versions in, or in 1.9.
