### ISSUE TITLE
Armor models don't animate when breaking blocks

### ISSUE THREAD

**Issue by williewillus** [williewillus/Botania#52]
Dumping here for now, investigate later (upstream?)

**Comment by TheWhiteWolves** [comment]
can confirm they are animating in 1.7

**Comment by williewillus** [comment]
Actually, this appears to be a Forge issue: https://github.com/MinecraftForge/MinecraftForge/issues/2400

**Comment by williewillus** [comment]
Note to self - Forge has fixed the issue, but it requires me to update to a newer forge version than the current recommended, which I'm not inclined to do unless a bunch of packs are already using something newer
