### ISSUE TITLE
Rod of the shaded mesa and Thaumcraft's aura nodes

### ISSUE THREAD

**Issue by Hyxaru** [williewillus/Botania#61]
The rod of the shaded mesa can move aura nodes as they are entities. This interaction is quite gamebreaking. Please forgive me if this is not the right github to report this issue.

**Comment by TheWhiteWolves** [comment]
@williewillus It might be worth adding an entity blacklist into the API for this and then asking @Azanor to register the aura node in the blacklist.

I might be able to look at implementing one upstream which u can then pull into here after if that works for you.

**Comment by williewillus** [comment]
sounds good

**Comment by TheWhiteWolves** [comment]
@williewillus Added a blacklist to the shaded mesa now so you can pull that now, ill pop over to azanors repo and link him to this with the request

**Comment by dragsta** [comment]
Do you know when the next build jar will be out? Thanks

**Comment by williewillus** [comment]
FIrst half of next week, probably

**Comment by williewillus** [comment]
Merged API changes in from upstream, will be in next build
