### ISSUE TITLE
Prismarine conflicts (both blocks and recipes)

### ISSUE THREAD

**Issue by oitsjustjose** [williewillus/Botania#62]
I know the port is still WIP and a lot is unplanned, but I wasn't sure if this one slipped between the cracks, so **just in case!**

Botania still adds Prismarine, even though it's a vanilla item now. Not a big deal, except the alchemy catalyst converts Quartz to _Vanilla_ Prismarine, and Botania does not use _Vanilla_ Prismarine in any of its recipes.

Easy fix for the most part, but I also wanted to ask - does Botania plan to remove the (now redundant) 1.8 blocks at some point? You've got bigger fish to fry, but I'm curious :P

**Comment by williewillus** [comment]
All recipes should use vanilla prismarine. Which ones do not?

**Comment by oitsjustjose** [comment]
[All of them](http://gfycat.com/DeadlyVerifiableAnkole). I'm on the latest release, by the way :)
