### ISSUE TITLE
Random crash 

### ISSUE THREAD

**Issue by gigabit101** [williewillus/Botania#63]
http://pastebin.com/f1FhNhg1

**Comment by GirafiStudios** [comment]
You're quite a few versions behind, pretty sure this got fixed - or at least there was made a workaround.

**Comment by williewillus** [comment]
update to the latest build

**Comment by gigabit101** [comment]
I have still happens

**Comment by yrsegal** [comment]
new log?

**Comment by gigabit101** [comment]
http://pastebin.com/M3zhFTQY

**Comment by gigabit101** [comment]
its diff because I added the Distributor it just happens to random people on the server at random times
