### ISSUE TITLE
When will the mana spreaders get implemented? 

### ISSUE THREAD

**Issue by jawsawn** [williewillus/Botania#64]
I know if you craft it with hand you will get a black purple no texture block, but when you place it it mostly works without any issues...  Also It doesn't show up on the JEI aswell. When will it be fixed? It is an important block for survival playability.

**Comment by williewillus** [comment]
It is only missing its texture. Everything else is there. Set JEI to not hide missing texture for now.

**Comment by jawsawn** [comment]
How one does interact with jei O_o

**Comment by TheWhiteWolves** [comment]
Option button in the bottom corner or its config file would be the best starting places :expressionless:

**Comment by williewillus** [comment]
I'll get the texture done in the next build, lol
