### ISSUE TITLE
TileJadedAmaranthus crash

### ISSUE THREAD

**Issue by gigabit101** [williewillus/Botania#65]
http://pastebin.com/KTSHNZed

**Comment by dragsta** [comment]
I also posted about this same issue yesterday but no one has responded as of yet.
I had the problem with agricarnations and hopperhawks though (floating and non). It is my belief that it is a problem with the way the flowers are grabbing mana from mana pools for I have not had any problems with flowers that don't take mana nor the hopperhawk without mana.

**Comment by williewillus** [comment]
Should be bandaided by 071bcef again, until I start the big refactor to fix the root cause of all of this

Let me know if this still happens in the next build.
