### ISSUE TITLE
Constant crashing

### ISSUE THREAD

**Issue by cakei** [williewillus/Botania#66]
After placing down floating agricarnations, stacked and not stacked, the server would constantly crash to the point only a backup would make it playable. This also happened with normal agricartions are placed down. 
http://pastebin.com/fC71QwWd

**Comment by williewillus** [comment]
See if you can reproduce without other mods (especially those coremods), there's almost no reason that crash should be happening in the place it is. Anyways, I'll add some safeguards.

**Comment by cakei** [comment]
Alright I tested your suggestions and it seems that removing thaumicinfusions caused the first issue but now a new issue? http://pastebin.com/Msh8kFtR

**Comment by williewillus** [comment]
That's (hopefully) solved by the next build (early next week): 071bcef
