### ISSUE TITLE
Trodden Dirt speed behavior issues

### ISSUE THREAD

**Issue by oitsjustjose** [williewillus/Botania#68]
It's really difficult to fit into a 15 second video for GFYcat, so I guess I've got to ask that you check this one if you can:

Trodden dirt has odd speed boost issues. I think I recall that a change in 1.8 was how that was handled separately, but I don't remember for sure. Essentially, if you stand on the trodden dirt and just _tap_ (not hold) your Forward keybind, Trodden Dirt keeps you moving forward. Additionally, the left & right movement seems boosted too, which makes staying _on_ the dirt nearly impossible if it turns any.

Let me know if you need some confirmation or something on this, but like I said, it's pretty tough to demonstrate. That being said, this is also a tiny bug and should be on the bottom of your list of priorities IMO - I can live without it and just continue using double slabs / slabs ;)

**Comment by williewillus** [comment]
yeah something changed in how 1.8 calls the "entity walking over block" method and I can't quite figure it out yet, thanks for bringing it to my attention though!
