### ISSUE TITLE
Crash when reading thaumcraft intergration

### ISSUE THREAD

**Issue by Hyxaru** [williewillus/Botania#69]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ThaumcraftLoader (Thaumcraft-1.8.9-5.1.4.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 23-1-16 12:19
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
    at vazkii.botania.common.lexicon.page.PageBrew.renderRecipe(PageBrew.java:54)
    at vazkii.botania.common.lexicon.page.PageRecipe.renderScreen(PageRecipe.java:56)
    at vazkii.botania.client.gui.lexicon.GuiLexiconEntry.func_73863_a(GuiLexiconEntry.java:201)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:309)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1103)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at vazkii.botania.common.lexicon.page.PageBrew.renderRecipe(PageBrew.java:54)
    at vazkii.botania.common.lexicon.page.PageRecipe.renderScreen(PageRecipe.java:56)
    at vazkii.botania.client.gui.lexicon.GuiLexiconEntry.func_73863_a(GuiLexiconEntry.java:201)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:309)

-- Screen render details --
Details:
    Screen name: vazkii.botania.client.gui.lexicon.GuiLexiconEntry
    Mouse location: Scaled: (300, 167). Absolute: (901, 334)
    Screen size: Scaled: (534, 279). Absolute: (1600, 837). Scale factor of 3

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['Hyxaru'/319, l='MpServer', x=-867,28, y=67,38, z=134,06]]
    Chunk stats: MultiplayerChunkCache: 288, 288
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: -922,00,4,00,192,00 - World: (-922,4,192), Chunk: (at 6,0,0 in -58,12; contains blocks -928,0,192 to -913,255,207), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
    Level time: 388466 game time, 6000 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 177 total; [EntityAuraNode['Aura Node'/7, l='MpServer', x=-977,50, y=30,50, z=99,50], EntityAuraNode['Aura Node'/11, l='MpServer', x=-964,50, y=92,50, z=104,50], EntitySheep['Sheep'/23, l='MpServer', x=-937,19, y=64,00, z=199,59], EntityCow['Cow'/24, l='MpServer', x=-945,06, y=64,00, z=197,91], EntityCow['Cow'/26, l='MpServer', x=-947,91, y=64,00, z=211,06], EntityChicken['Chicken'/32, l='MpServer', x=-931,47, y=64,00, z=180,66], EntityItem['item.item.feather'/33, l='MpServer', x=-930,78, y=64,00, z=180,03], EntityItem['item.item.egg'/34, l='MpServer', x=-930,91, y=64,00, z=180,56], EntitySheep['Sheep'/35, l='MpServer', x=-941,97, y=64,00, z=197,94], EntityChicken['Chicken'/36, l='MpServer', x=-936,41, y=64,00, z=203,44], EntityChicken['Chicken'/37, l='MpServer', x=-928,34, y=64,00, z=203,28], EntityPig['Pig'/41, l='MpServer', x=-926,22, y=64,00, z=214,22], EntityPig['Pig'/44, l='MpServer', x=-924,06, y=64,00, z=186,91], EntitySheep['Sheep'/45, l='MpServer', x=-916,78, y=64,00, z=189,69], EntityPig['Pig'/46, l='MpServer', x=-923,97, y=64,00, z=206,75], EntityMooshroom['Mooshroom'/47, l='MpServer', x=-922,13, y=64,00, z=198,06], EntityChicken['Chicken'/48, l='MpServer', x=-918,47, y=64,00, z=207,63], EntityCow['Cow'/49, l='MpServer', x=-916,88, y=64,00, z=204,94], EntityAuraNode['Aura Node'/57, l='MpServer', x=-900,50, y=91,50, z=81,50], EntityCow['Cow'/58, l='MpServer', x=-906,19, y=64,00, z=205,22], EntityCow['Cow'/59, l='MpServer', x=-907,84, y=64,00, z=204,09], EntitySheep['Sheep'/60, l='MpServer', x=-911,06, y=64,00, z=195,97], EntityChicken['Chicken'/61, l='MpServer', x=-903,59, y=64,00, z=200,22], EntityCow['Cow'/62, l='MpServer', x=-908,88, y=64,00, z=196,06], EntityChicken['Chicken'/63, l='MpServer', x=-908,41, y=64,00, z=205,59], EntityAuraNode['Aura Node'/69, l='MpServer', x=-883,50, y=64,50, z=3,50], EntityChicken['Chicken'/70, l='MpServer', x=-886,59, y=64,00, z=185,34], EntityItem['item.item.egg'/71, l='MpServer', x=-890,69, y=64,00, z=177,06], EntityChicken['Chicken'/72, l='MpServer', x=-886,59, y=64,00, z=198,66], EntityPig['Pig'/73, l='MpServer', x=-885,88, y=64,00, z=203,81], EntityPig['Pig'/75, l='MpServer', x=-891,78, y=64,00, z=208,91], EntityPlayerSP['Hyxaru'/319, l='MpServer', x=-867,28, y=67,38, z=134,06], EntityAuraNode['Aura Node'/78, l='MpServer', x=-867,50, y=66,50, z=90,50], EntityThaumcraftGolem['Golem'/80, l='MpServer', x=-857,69, y=64,00, z=111,59], EntityCorporeaSpark['Corporea Spark'/81, l='MpServer', x=-849,50, y=66,50, z=119,50], EntityItemFrame['entity.ItemFrame.name'/82, l='MpServer', x=-849,50, y=65,50, z=120,03], EntityAuraNode['Aura Node'/83, l='MpServer', x=-838,50, y=83,50, z=38,50], EntityAuraNode['Aura Node'/84, l='MpServer', x=-832,50, y=65,50, z=57,50], EntitySpark['Spark'/88, l='MpServer', x=-840,50, y=67,50, z=77,50], EntitySpark['Spark'/89, l='MpServer', x=-840,50, y=67,50, z=74,50], EntitySpark['Spark'/90, l='MpServer', x=-840,50, y=67,50, z=71,50], EntitySpark['Spark'/91, l='MpServer', x=-834,50, y=67,50, z=92,50], EntitySpark['Spark'/92, l='MpServer', x=-837,50, y=67,50, z=92,50], EntitySpark['Spark'/93, l='MpServer', x=-840,50, y=67,50, z=92,50], EntitySpark['Spark'/94, l='MpServer', x=-840,50, y=67,50, z=89,50], EntitySpark['Spark'/95, l='MpServer', x=-840,50, y=67,50, z=86,50], EntitySpark['Spark'/96, l='MpServer', x=-840,50, y=67,50, z=83,50], EntitySpark['Spark'/97, l='MpServer', x=-840,50, y=67,50, z=80,50], EntityItemFrame['entity.ItemFrame.name'/98, l='MpServer', x=-839,97, y=67,50, z=99,50], EntityItemFrame['entity.ItemFrame.name'/99, l='MpServer', x=-839,97, y=67,50, z=101,50], EntityItemFrame['entity.ItemFrame.name'/100, l='MpServer', x=-839,97, y=67,50, z=103,50], EntityItemFrame['entity.ItemFrame.name'/101, l='MpServer', x=-839,97, y=67,50, z=105,50], EntityItemFrame['entity.ItemFrame.name'/102, l='MpServer', x=-839,97, y=67,50, z=107,50], EntityItemFrame['entity.ItemFrame.name'/103, l='MpServer', x=-839,97, y=67,50, z=109,50], EntityItemFrame['entity.ItemFrame.name'/104, l='MpServer', x=-839,03, y=67,50, z=109,50], EntityItemFrame['entity.ItemFrame.name'/105, l='MpServer', x=-839,03, y=67,50, z=107,50], EntityItemFrame['entity.ItemFrame.name'/106, l='MpServer', x=-839,03, y=67,50, z=105,50], EntityItemFrame['entity.ItemFrame.name'/107, l='MpServer', x=-839,03, y=67,50, z=103,50], EntityItemFrame['entity.ItemFrame.name'/108, l='MpServer', x=-839,03, y=67,50, z=101,50], EntityItemFrame['entity.ItemFrame.name'/109, l='MpServer', x=-839,03, y=67,50, z=99,50], EntityItemFrame['entity.ItemFrame.name'/110, l='MpServer', x=-835,03, y=67,50, z=109,50], EntityItem['item.item.feather'/42094, l='MpServer', x=-886,13, y=64,00, z=199,53], EntityItemFrame['entity.ItemFrame.name'/111, l='MpServer', x=-835,03, y=67,50, z=107,50], EntityItemFrame['entity.ItemFrame.name'/112, l='MpServer', x=-835,03, y=67,50, z=105,50], EntityItemFrame['entity.ItemFrame.name'/113, l='MpServer', x=-835,03, y=67,50, z=103,50], EntityItemFrame['entity.ItemFrame.name'/114, l='MpServer', x=-835,03, y=67,50, z=101,50], EntityItemFrame['entity.ItemFrame.name'/115, l='MpServer', x=-835,03, y=67,50, z=99,50], EntityItemFrame['entity.ItemFrame.name'/116, l='MpServer', x=-835,97, y=67,50, z=99,50], EntityItemFrame['entity.ItemFrame.name'/117, l='MpServer', x=-835,97, y=67,50, z=101,50], EntityItemFrame['entity.ItemFrame.name'/118, l='MpServer', x=-835,97, y=67,50, z=103,50], EntityItemFrame['entity.ItemFrame.name'/119, l='MpServer', x=-835,97, y=67,50, z=105,50], EntityItemFrame['entity.ItemFrame.name'/120, l='MpServer', x=-835,97, y=67,50, z=107,50], EntityItemFrame['entity.ItemFrame.name'/121, l='MpServer', x=-835,97, y=67,50, z=109,50], EntityCorporeaSpark['Corporea Spark'/122, l='MpServer', x=-840,50, y=68,50, z=99,50], EntityCorporeaSpark['Corporea Spark'/123, l='MpServer', x=-840,50, y=68,50, z=101,50], EntityCorporeaSpark['Corporea Spark'/124, l='MpServer', x=-840,50, y=68,50, z=103,50], EntityCorporeaSpark['Corporea Spark'/125, l='MpServer', x=-840,50, y=68,50, z=105,50], EntityCorporeaSpark['Corporea Spark'/126, l='MpServer', x=-840,50, y=68,50, z=107,50], EntityCorporeaSpark['Corporea Spark'/127, l='MpServer', x=-840,50, y=68,50, z=109,50], EntityCorporeaSpark['Corporea Spark'/128, l='MpServer', x=-838,50, y=68,50, z=109,50], EntityCorporeaSpark['Corporea Spark'/129, l='MpServer', x=-838,50, y=68,50, z=107,50], EntityCorporeaSpark['Corporea Spark'/130, l='MpServer', x=-838,50, y=68,50, z=105,50], EntityCorporeaSpark['Corporea Spark'/131, l='MpServer', x=-838,50, y=68,50, z=103,50], EntityCorporeaSpark['Corporea Spark'/132, l='MpServer', x=-838,50, y=68,50, z=101,50], EntityCorporeaSpark['Corporea Spark'/133, l='MpServer', x=-838,50, y=68,50, z=99,50], EntityCorporeaSpark['Corporea Spark'/134, l='MpServer', x=-836,50, y=68,50, z=99,50], EntityCorporeaSpark['Corporea Spark'/135, l='MpServer', x=-834,50, y=68,50, z=99,50], EntityCorporeaSpark['Corporea Spark'/136, l='MpServer', x=-834,50, y=68,50, z=101,50], EntityCorporeaSpark['Corporea Spark'/137, l='MpServer', x=-836,50, y=68,50, z=101,50], EntityCorporeaSpark['Corporea Spark'/138, l='MpServer', x=-834,50, y=68,50, z=103,50], EntityCorporeaSpark['Corporea Spark'/139, l='MpServer', x=-836,50, y=68,50, z=103,50], EntityCorporeaSpark['Corporea Spark'/140, l='MpServer', x=-834,50, y=68,50, z=109,50], EntityCorporeaSpark['Corporea Spark'/141, l='MpServer', x=-836,50, y=68,50, z=109,50], EntityCorporeaSpark['Corporea Spark'/142, l='MpServer', x=-834,50, y=68,50, z=107,50], EntityCorporeaSpark['Corporea Spark'/143, l='MpServer', x=-836,50, y=68,50, z=107,50], EntityCorporeaSpark['Corporea Spark'/144, l='MpServer', x=-834,50, y=68,50, z=105,50], EntityCorporeaSpark['Corporea Spark'/145, l='MpServer', x=-836,50, y=68,50, z=105,50], EntityCorporeaSpark['Corporea Spark'/146, l='MpServer', x=-832,50, y=68,50, z=109,50], EntityCorporeaSpark['Corporea Spark'/147, l='MpServer', x=-832,50, y=68,50, z=107,50], EntityCorporeaSpark['Corporea Spark'/148, l='MpServer', x=-832,50, y=68,50, z=105,50], EntityCorporeaSpark['Corporea Spark'/149, l='MpServer', x=-832,50, y=68,50, z=99,50], EntityCorporeaSpark['Corporea Spark'/150, l='MpServer', x=-832,50, y=68,50, z=101,50], EntityCorporeaSpark['Corporea Spark'/151, l='MpServer', x=-832,50, y=68,50, z=103,50], EntityItemFrame['entity.ItemFrame.name'/152, l='MpServer', x=-837,50, y=65,50, z=120,03], EntityCorporeaSpark['Corporea Spark'/153, l='MpServer', x=-837,50, y=66,50, z=119,50], EntityCorporeaSpark['Corporea Spark'/154, l='MpServer', x=-839,50, y=66,50, z=119,50], EntityCorporeaSpark['Corporea Spark'/155, l='MpServer', x=-841,50, y=66,50, z=119,50], EntityCorporeaSpark['Corporea Spark'/156, l='MpServer', x=-843,50, y=66,50, z=119,50], EntityCorporeaSpark['Corporea Spark'/157, l='MpServer', x=-845,50, y=66,50, z=119,50], EntityCorporeaSpark['Corporea Spark'/158, l='MpServer', x=-847,50, y=66,50, z=119,50], EntityItemFrame['entity.ItemFrame.name'/159, l='MpServer', x=-839,50, y=65,50, z=120,03], EntityItemFrame['entity.ItemFrame.name'/160, l='MpServer', x=-841,50, y=65,50, z=120,03], EntityItemFrame['entity.ItemFrame.name'/161, l='MpServer', x=-843,50, y=65,50, z=120,03], EntityItemFrame['entity.ItemFrame.name'/162, l='MpServer', x=-845,50, y=65,50, z=120,03], EntityItemFrame['entity.ItemFrame.name'/163, l='MpServer', x=-847,50, y=65,50, z=120,03], EntityCorporeaSpark['Corporea Spark'/164, l='MpServer', x=-846,50, y=65,50, z=121,50], EntityCorporeaSpark['Corporea Spark'/165, l='MpServer', x=-844,50, y=65,50, z=121,50], EntitySpark['Spark'/172, l='MpServer', x=-816,50, y=67,50, z=71,50], EntitySpark['Spark'/173, l='MpServer', x=-816,50, y=67,50, z=74,50], EntitySpark['Spark'/174, l='MpServer', x=-816,50, y=67,50, z=77,50], EntitySpark['Spark'/175, l='MpServer', x=-828,50, y=70,50, z=80,50], EntitySpark['Spark'/176, l='MpServer', x=-816,50, y=67,50, z=80,50], EntitySpark['Spark'/177, l='MpServer', x=-816,50, y=67,50, z=83,50], EntitySpark['Spark'/178, l='MpServer', x=-816,50, y=67,50, z=86,50], EntitySpark['Spark'/179, l='MpServer', x=-816,50, y=67,50, z=89,50], EntitySpark['Spark'/180, l='MpServer', x=-816,50, y=67,50, z=92,50], EntitySpark['Spark'/181, l='MpServer', x=-819,50, y=67,50, z=92,50], EntitySpark['Spark'/182, l='MpServer', x=-822,50, y=67,50, z=92,50], EntitySpark['Spark'/183, l='MpServer', x=-825,50, y=67,50, z=92,50], EntitySpark['Spark'/184, l='MpServer', x=-828,50, y=67,50, z=92,50], EntitySpark['Spark'/185, l='MpServer', x=-831,50, y=67,50, z=92,50], EntityItemFrame['entity.ItemFrame.name'/186, l='MpServer', x=-831,03, y=67,50, z=109,50], EntityItemFrame['entity.ItemFrame.name'/187, l='MpServer', x=-831,03, y=67,50, z=107,50], EntityItemFrame['entity.ItemFrame.name'/188, l='MpServer', x=-831,03, y=67,50, z=105,50], EntityItemFrame['entity.ItemFrame.name'/189, l='MpServer', x=-831,03, y=67,50, z=99,50], EntityItemFrame['entity.ItemFrame.name'/190, l='MpServer', x=-831,03, y=67,50, z=101,50], EntityItemFrame['entity.ItemFrame.name'/191, l='MpServer', x=-831,03, y=67,50, z=103,50], EntityItemFrame['entity.ItemFrame.name'/192, l='MpServer', x=-831,97, y=67,50, z=99,50], EntityItemFrame['entity.ItemFrame.name'/193, l='MpServer', x=-831,97, y=67,50, z=101,50], EntityItemFrame['entity.ItemFrame.name'/194, l='MpServer', x=-831,97, y=67,50, z=103,50], EntityItemFrame['entity.ItemFrame.name'/195, l='MpServer', x=-831,97, y=67,50, z=109,50], EntityItemFrame['entity.ItemFrame.name'/196, l='MpServer', x=-831,97, y=67,50, z=107,50], EntityItemFrame['entity.ItemFrame.name'/197, l='MpServer', x=-831,97, y=67,50, z=105,50], EntityItemFrame['entity.ItemFrame.name'/198, l='MpServer', x=-827,03, y=67,50, z=109,50], EntityItemFrame['entity.ItemFrame.name'/199, l='MpServer', x=-827,03, y=67,50, z=107,50], EntityItemFrame['entity.ItemFrame.name'/200, l='MpServer', x=-827,03, y=67,50, z=105,50], EntityItemFrame['entity.ItemFrame.name'/201, l='MpServer', x=-827,03, y=67,50, z=103,50], EntityItemFrame['entity.ItemFrame.name'/202, l='MpServer', x=-827,03, y=67,50, z=101,50], EntityItemFrame['entity.ItemFrame.name'/203, l='MpServer', x=-827,03, y=67,50, z=99,50], EntityItemFrame['entity.ItemFrame.name'/204, l='MpServer', x=-827,97, y=67,50, z=99,50], EntityItemFrame['entity.ItemFrame.name'/205, l='MpServer', x=-827,97, y=67,50, z=101,50], EntityItemFrame['entity.ItemFrame.name'/206, l='MpServer', x=-827,97, y=67,50, z=103,50], EntityItemFrame['entity.ItemFrame.name'/207, l='MpServer', x=-827,97, y=67,50, z=109,50], EntityItemFrame['entity.ItemFrame.name'/208, l='MpServer', x=-827,97, y=67,50, z=107,50], EntityItemFrame['entity.ItemFrame.name'/209, l='MpServer', x=-827,97, y=67,50, z=105,50], EntityCorporeaSpark['Corporea Spark'/210, l='MpServer', x=-830,50, y=68,50, z=109,50], EntityCorporeaSpark['Corporea Spark'/211, l='MpServer', x=-830,50, y=68,50, z=107,50], EntityCorporeaSpark['Corporea Spark'/212, l='MpServer', x=-830,50, y=68,50, z=105,50], EntityCorporeaSpark['Corporea Spark'/213, l='MpServer', x=-830,50, y=68,50, z=103,50], EntityCorporeaSpark['Corporea Spark'/214, l='MpServer', x=-830,50, y=68,50, z=101,50], EntityCorporeaSpark['Corporea Spark'/215, l='MpServer', x=-830,50, y=68,50, z=99,50], EntityCorporeaSpark['Corporea Spark'/216, l='MpServer', x=-826,50, y=68,50, z=99,50], EntityCorporeaSpark['Corporea Spark'/217, l='MpServer', x=-828,50, y=68,50, z=99,50], EntityCorporeaSpark['Corporea Spark'/218, l='MpServer', x=-826,50, y=68,50, z=101,50], EntityCorporeaSpark['Corporea Spark'/219, l='MpServer', x=-828,50, y=68,50, z=101,50], EntityCorporeaSpark['Corporea Spark'/220, l='MpServer', x=-826,50, y=68,50, z=103,50], EntityCorporeaSpark['Corporea Spark'/221, l='MpServer', x=-828,50, y=68,50, z=103,50], EntityCorporeaSpark['Corporea Spark'/222, l='MpServer', x=-826,50, y=68,50, z=105,50], EntityCorporeaSpark['Corporea Spark'/223, l='MpServer', x=-828,50, y=68,50, z=105,50], EntityCorporeaSpark['Corporea Spark'/224, l='MpServer', x=-826,50, y=68,50, z=107,50], EntityCorporeaSpark['Corporea Spark'/225, l='MpServer', x=-828,50, y=68,50, z=107,50], EntityCorporeaSpark['Corporea Spark'/226, l='MpServer', x=-826,50, y=68,50, z=109,50], EntityCorporeaSpark['Corporea Spark'/227, l='MpServer', x=-828,50, y=68,50, z=109,50], EntityAuraNode['Aura Node'/229, l='MpServer', x=-781,50, y=64,50, z=213,50], EntityAuraNode['Aura Node'/230, l='MpServer', x=-770,50, y=65,50, z=270,50], EntityAuraNode['Aura Node'/231, l='MpServer', x=-759,50, y=64,50, z=158,50], EntityAuraNode['Aura Node'/244, l='MpServer', x=-733,50, y=64,50, z=9,50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 387955376 bytes (369 MB) / 810930176 bytes (773 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.19 Powered by Forge 11.15.0.1701 6 mods loaded, 6 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.18} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.0.1701.jar) 
    UCHIJAAAA   Forge{11.15.0.1701} [Minecraft Forge](forge-1.8.9-11.15.0.1701.jar) 
    UCHIJAAAA   Baubles{1.1.3.0} [Baubles](Baubles-1.8.9-1.1.3.0.jar) 
    UCHIJAAAA   Botania{r1.8-249} [Botania](Botania.r1.8-248-MC1.8-d0e4e43.jar) 
    UCHIJAAAA   Thaumcraft{5.1.4} [Thaumcraft](Thaumcraft-1.8.9-5.1.4.jar) 
    Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.4.jar)

```
GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4229' Renderer: 'Intel(R) HD Graphics 3000'
Launched Version: 1.8.9-forge1.8.9-11.15.0.1701
LWJGL: 2.9.4
OpenGL: Intel(R) HD Graphics 3000 GL version 3.1.0 - Build 9.17.10.4229, Intel
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 4x Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz
```

**Comment by williewillus** [comment]
Is this all thaumcraft integration pages or just the brew page?

**Comment by Hyxaru** [comment]
Perhaps, I didn't get to read that part because it crashed or a page before. Will test.

**Comment by Hyxaru** [comment]
After the page of alternative botania blocks to reduce infusion altar stability.
