### ISSUE TITLE
Rod of the shaded mesa blacklist suggestions

### ISSUE THREAD

**Issue by Hyxaru** [williewillus/Botania#70]
The enderdragon and the wither are worthy candidates for a blacklist.

**Comment by yrsegal** [comment]
As well as the Gaia Guardian and its landmines and missiles, if they aren't already.

**Comment by TheWhiteWolves** [comment]
you know, I never considered what needed to be blacklisted I only added it with the thought of sorting out the Aura Node problem :stuck_out_tongue_closed_eyes:

**Comment by TheWhiteWolves** [comment]
damnit, why did you make me look at this, at this point I wish i had made it a whitelist for the rod.

**Comment by TheWhiteWolves** [comment]
Funny thing I ran into while adding in some blacklists [https://gfycat.com/InnocentFarflungCougar](https://gfycat.com/InnocentFarflungCougar)

**Comment by yrsegal** [comment]
works with horses, and pigs

**Comment by TheWhiteWolves** [comment]
ye, they not blacklisted so it grabs em, I was considering blacklisting em but thought its too much of a fun thing to do

**Comment by yrsegal** [comment]
make it so you can't shade-mesa something being ridden?

**Comment by howtonotwin** [comment]
Maybe add a config for it as a list of blacklisted entities? That way mods that don't blacklist things themselves and aren't specifically accounted for by Botania can be added by the user. (And maybe ridden entities could have a separate boolean value.)

**Comment by williewillus** [comment]
I'd rather vaz decide these himself :p

**Comment by TheWhiteWolves** [comment]
I've only added in basic stuff as defaults, Bosses (Ender Dragon, Wither, Gaia Guardian) and things that shouldn't be move cos they either are to do with a boss (Ender Crystals, Gaia's Landmines, etc.) or are some kind of block like enity (Sparks, Item Frames, etc.), other than them it will be upto vaz is she wants to blacklist more or for other mods to add their own entities to the list.

**Comment by williewillus** [comment]
Closing this for now as the basics have already been added, more can be brought up on a case by case basis.
