### ISSUE TITLE
Loonium and redstone disabling

### ISSUE THREAD

**Issue by Hyxaru** [williewillus/Botania#72]
I've noticed the Loonium (loot generating flower) continues to work even if a redstone signal is applied to it. Normaly this would disable its functions (Not sure if it would in botania 1.7.10 , but I think it should also prevent the flower from pulling mana from it's associated pool, theoraticly)

This might also apply to other flowers using redstone disabling functions, but I know it works normaly on the rannuncarpus.

**Comment by TheWhiteWolves** [comment]
Can't reproduce this, had one sat for about 20 minutes in the below setup and nothing has happened with the redstone signal applied with the lever on the right.

![2016-01-24_13 50 43](https://cloud.githubusercontent.com/assets/1471503/12536589/8756ae82-c2a1-11e5-9202-44c08c2c986c.png)

**Comment by Hyxaru** [comment]
Nevermind can't reproduce it anymore after using the newer version. It still absorbs mana when disabled to fill its bar, but that is not a problem I gues.

**Comment by TheWhiteWolves** [comment]
ye all flowers will fill their internal buffer even when turned off, that just how vaz made it.
