### ISSUE TITLE
Need to load after thaumcraft again

### ISSUE THREAD

**Issue by williewillus** [williewillus/Botania#74]
dumping this here so I don't forgot

Turns out we removed our after:thaumcraft dep a little too soon, we _need_ to go after tc because it doesn't init its potions until postInit, and since B is before T our integration binds to a null potion and crashes.

**Comment by yrsegal** [comment]
But doesn't Azanor need first for the Exoflamable blocks and the apothecary?

**Comment by williewillus** [comment]
I don't see why the apothecary needs to be initted at all, it's an instanceof check at runtime. Not sure about the exoflame thing

Either way, doing potions in postinit is a little weird, I'll see what I can do when I can actually catch him on IRC :p

**Comment by williewillus** [comment]
See https://github.com/Azanor/thaumcraft-5/issues/335

**Comment by Hyxaru** [comment]
Azanor solved it.

**Comment by williewillus** [comment]
Is it resolved in a public thaumcraft build?

**Comment by GirafiStudios** [comment]
There is no beta builds of Thaumcraft atm. The latest one of CurseForge is the latest :)

**Comment by williewillus** [comment]
Okay I will test it once more when I get home then reenable the lexicon integration
