### ISSUE TITLE
1.8.9 Server Crash

### ISSUE THREAD

**Issue by king05** [williewillus/Botania#77]
Hi, 
I have made a minecraft 1.8.9 Server for my modpack and when i add RFTools the server crashes...
The mod works fine on Client side.
Here are the crash report:
http://pastebin.com/yG4s4DCW
and the fml log:
http://pastebin.com/FX2QyGKZ

I'll link RFTools and Buildcraft in a moment. 
I hope you can help me.

Sincerly king05

Edit:
here is the Buildcraft issue:
https://github.com/AlexIIL/Buildcraft_1.8_Issues/issues/101
and here is the RFTools issue:
https://github.com/McJty/RFTools/issues/433
The crash report told me to contact you three authors...

**Comment by GirafiStudios** [comment]
You don't have the required lib mod for RF Tools called Mcjtylib, at least not in the crash report.

**Comment by king05** [comment]
I have this version from curse:
mcjtylib-1.8.9-1.8.1beta4 (1).jar
http://minecraft.curseforge.com/projects/mcjtylib/files

**Comment by GirafiStudios** [comment]
Can you try with only Buildcraft, McjtyLib & RF Tools?

**Comment by king05** [comment]
i had tried everything...
only buildcraft, only rftools, only botania, buildcraft and botania, buildcraft and rftools, and botania and rftools.... but the server crashes everytime with the same crash report...

**Comment by yrsegal** [comment]
Have you tried it without botania and gotten the same crash?

**Comment by king05** [comment]
yes... than it says contact buildcraft author and rftools author...

**Comment by GirafiStudios** [comment]
So this crash happens without Botania? This have nothing to do with Botania at all.. :p

**Comment by Razorskills** [comment]
Are you using Java 8?

**Comment by king05** [comment]
@GirafiStudios but the crash also appears when i disable buildcraft and rftools and activate botania...

**Comment by Razorskills** [comment]
nvm just checked the log, you have java 7. I believe they have a java 8 dependency. Try upgrading java and see if you crash again.

**Comment by GirafiStudios** [comment]
Right. It's because you're not using Java 8, Botania requires that. I assume the other 2 mods requires it too since they are crashing. Good catch @Razorskills!

**Comment by king05** [comment]
ok i have to say it then to the server owner... thanks for the moment.... i say then if it works
thanks for the fast support

**Comment by king05** [comment]
i just downloadet the server to try it on my local computer with java 8 and it works fine... thanks for the help
