### ISSUE TITLE
Crash when trying to use Rod of the Seas

### ISSUE THREAD

**Issue by zepheris** [williewillus/Botania#78]
I have a copy of my crash report. http://paste.ee/p/RFjdB

This is the first time I've used Botania (I'm mostly a tech mod guy). I've never used the Rod of the Seas before, but I'm assuming I can just right click on the ground to spawn a water block.

When I try, the game crashes. It crashes every time. (easily reproducible)
Let me know if you need additional information
My current mod list:
![image](https://cloud.githubusercontent.com/assets/4251071/12573313/b7f59d64-c3b4-11e5-931c-4f83ac5020b4.png)

**Comment by TheWhiteWolves** [comment]
can you reproduce this with only Botania installed?

**Comment by TheWhiteWolves** [comment]
@williewillus Looks to be something to do with this point [ItemWaterRod.java Line 29](https://github.com/williewillus/Botania/blob/MC18/src/main/java/vazkii/botania/common/item/rod/ItemWaterRod.java#L29), could be that `ItemStack stackToPlace` is null
