### ISSUE TITLE
Solegnolia Petit doesnt work

### ISSUE THREAD

**Issue by tjsd** [williewillus/Botania#79]
The normal version is fine, but the petit version of it has no effect.

Pack: FTB Unstable v3.0.15
Botania Build: Botania.r1.8-248-MC1.8-d0e4e43

**Comment by TheWhiteWolves** [comment]
are you stood within its range?

**Comment by tjsd** [comment]
I am to blocks away from the flower, the flower has mana, the coal is on the 3rd block on the other side of the flower, and the ring sucks up all the coal. The normal version works fine.

**Comment by TheWhiteWolves** [comment]
the range on the petit version is only 1 block, try putting on a manaseer monocle and look at the flower, it will show you its range, but from what you're saying it sounds like both you and the blocks you are picking up are outside its 1 block radius

**Comment by williewillus** [comment]
Can't reproduce, placed solegnolia petite, dropped item within its radius (use manaseer monocle), equipped ring. Ring doesn't pick up until solegnolia is broken.
