### ISSUE TITLE
Crash (when I open thaumonomicon from TC5)

### ISSUE THREAD

**Issue by Fey142** [williewillus/Botania#82]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ThaumcraftLoader (Thaumcraft-1.8.9-5.1.4.jar)
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  FMLPlugin (InventoryTweaks-1.60-beta-30.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 27.1.2016 0:35
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
    at vazkii.botania.common.item.equipment.bauble.ItemBloodPendant.getItemForBrew(ItemBloodPendant.java:150)
    at vazkii.botania.common.item.equipment.bauble.ItemBloodPendant.func_150895_a(ItemBloodPendant.java:63)
    at thaumcraft.client.gui.GuiResearchRecipe.<init>(GuiResearchRecipe.java:126)
    at thaumcraft.client.gui.GuiResearchBrowser.func_73864_a(GuiResearchBrowser.java:949)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:554)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at vazkii.botania.common.item.equipment.bauble.ItemBloodPendant.getItemForBrew(ItemBloodPendant.java:150)
    at vazkii.botania.common.item.equipment.bauble.ItemBloodPendant.func_150895_a(ItemBloodPendant.java:63)
    at thaumcraft.client.gui.GuiResearchRecipe.<init>(GuiResearchRecipe.java:126)
    at thaumcraft.client.gui.GuiResearchBrowser.func_73864_a(GuiResearchBrowser.java:949)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:554)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)

-- Affected screen --
Details:
    Screen name: thaumcraft.client.gui.GuiResearchBrowser

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['Fey142'/345102, l='MpServer', x=149,41, y=63,00, z=185,06]]
    Chunk stats: MultiplayerChunkCache: 441, 441
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: 120,00,64,00,256,00 - World: (120,64,256), Chunk: (at 8,4,0 in 7,16; contains blocks 112,0,256 to 127,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 3331884 game time, 3250071 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 85 total; [EntityZombie['Zombie'/353029, l='MpServer', x=84,50, y=32,00, z=119,50], EntitySkeleton['Skeleton'/352007, l='MpServer', x=229,50, y=24,00, z=109,50], EntityCreeper['Creeper'/323456, l='MpServer', x=163,59, y=73,00, z=193,47], EntityAuraNode['Aura Node'/136, l='MpServer', x=157,50, y=65,49, z=180,49], EntityAuraNode['Aura Node'/137, l='MpServer', x=157,50, y=65,47, z=189,50], EntityAuraNode['Aura Node'/138, l='MpServer', x=158,49, y=65,49, z=179,50], EntityAuraNode['Aura Node'/139, l='MpServer', x=158,49, y=65,50, z=190,49], EntityZombie['Zombie'/349577, l='MpServer', x=168,16, y=40,00, z=212,28], EntitySkeleton['Skeleton'/349833, l='MpServer', x=82,50, y=21,00, z=151,50], EntityEnderman['Enderman'/351369, l='MpServer', x=154,88, y=54,00, z=115,56], EntityCreeper['Creeper'/350613, l='MpServer', x=163,59, y=55,00, z=253,06], EntityAuraNode['Aura Node'/345111, l='MpServer', x=175,50, y=18,50, z=127,50], EntityAuraNode['Aura Node'/22, l='MpServer', x=10,50, y=88,50, z=228,50], EntityAuraNode['Aura Node'/151, l='MpServer', x=166,47, y=65,50, z=189,50], EntityManaBurst['Mana Burst'/353682, l='MpServer', x=191,48, y=73,50, z=247,98], EntityAuraNode['Aura Node'/152, l='MpServer', x=165,50, y=65,50, z=190,47], EntityCreeper['Creeper'/353565, l='MpServer', x=125,50, y=39,00, z=157,50], EntityAuraNode['Aura Node'/153, l='MpServer', x=166,49, y=65,49, z=180,50], EntityZombie['Zombie'/351647, l='MpServer', x=103,50, y=21,00, z=185,50], EntityBat['Bat'/348447, l='MpServer', x=69,34, y=32,74, z=117,55], EntitySkeleton['Skeleton'/350619, l='MpServer', x=84,50, y=19,00, z=144,50], EntityBat['Bat'/352677, l='MpServer', x=75,45, y=17,05, z=172,02], EntityBat['Bat'/352934, l='MpServer', x=104,52, y=36,60, z=243,79], EntityAuraNode['Aura Node'/164, l='MpServer', x=178,50, y=83,34, z=176,50], EntityBat['Bat'/351137, l='MpServer', x=79,45, y=38,01, z=113,46], EntityAuraNode['Aura Node'/165, l='MpServer', x=188,28, y=72,97, z=250,59], EntityBat['Bat'/353186, l='MpServer', x=81,11, y=58,02, z=217,70], EntitySkeleton['Skeleton'/322860, l='MpServer', x=132,84, y=72,00, z=199,59], EntityItem['item.item.bone'/340525, l='MpServer', x=126,88, y=67,00, z=204,09], EntityAuraNode['Aura Node'/345132, l='MpServer', x=133,50, y=71,50, z=68,50], EntityAuraNode['Aura Node'/169, l='MpServer', x=192,50, y=97,50, z=196,50], EntityZombie['Zombie'/352047, l='MpServer', x=136,50, y=37,00, z=126,50], EntitySkeleton['Skeleton'/330408, l='MpServer', x=176,13, y=39,00, z=216,22], EntityCreeper['Creeper'/347957, l='MpServer', x=115,50, y=32,00, z=118,50], EntityItem['item.item.bone'/338868, l='MpServer', x=162,94, y=77,00, z=175,34], EntityBat['Bat'/346935, l='MpServer', x=101,41, y=24,10, z=117,88], EntityAuraNode['Aura Node'/345143, l='MpServer', x=63,50, y=42,50, z=41,50], EntitySkeleton['Skeleton'/352432, l='MpServer', x=76,50, y=18,00, z=141,50], EntityAuraNode['Aura Node'/345011, l='MpServer', x=264,50, y=89,50, z=180,50], EntityAuraNode['Aura Node'/195125, l='MpServer', x=252,50, y=89,50, z=168,50], EntityZombie['Zombie'/351417, l='MpServer', x=84,50, y=18,00, z=129,50], EntityCreeper['Creeper'/352313, l='MpServer', x=83,50, y=21,00, z=200,50], EntityRabbit['Rabbit'/196, l='MpServer', x=225,09, y=114,00, z=204,50], EntityBat['Bat'/353217, l='MpServer', x=75,47, y=52,16, z=175,66], EntityBat['Bat'/353216, l='MpServer', x=106,31, y=15,22, z=156,16], EntityPlayerSP['Fey142'/345102, l='MpServer', x=149,41, y=63,00, z=185,06], EntityRabbit['Rabbit'/70, l='MpServer', x=84,63, y=63,00, z=144,50], EntityAuraNode['Aura Node'/198, l='MpServer', x=242,50, y=101,50, z=299,50], EntitySkeleton['Skeleton'/348738, l='MpServer', x=106,50, y=19,00, z=121,50], EntityCreeper['Creeper'/349762, l='MpServer', x=99,50, y=16,00, z=129,50], EntitySkeleton['Skeleton'/283597, l='MpServer', x=161,44, y=46,00, z=203,06], EntityAuraNode['Aura Node'/175822, l='MpServer', x=234,50, y=89,50, z=182,50], EntityZombie['Zombie'/352713, l='MpServer', x=187,50, y=70,00, z=182,50], EntitySkeleton['Skeleton'/324809, l='MpServer', x=163,16, y=77,00, z=176,19], EntitySkeleton['Skeleton'/349003, l='MpServer', x=220,50, y=35,00, z=168,50], EntityAuraNode['Aura Node'/345163, l='MpServer', x=70,50, y=90,50, z=47,50], EntityBrainyZombie['Angry Zombie'/352088, l='MpServer', x=130,56, y=30,00, z=200,13], EntityEnderman['Enderman'/352728, l='MpServer', x=169,91, y=36,00, z=215,59], EntityCreeper['Creeper'/351834, l='MpServer', x=101,50, y=26,00, z=125,50], EntitySkeleton['Skeleton'/352090, l='MpServer', x=84,50, y=14,00, z=119,50], EntityCreeper['Creeper'/352474, l='MpServer', x=154,94, y=19,00, z=141,44], EntitySquid['Squid'/337637, l='MpServer', x=184,50, y=62,00, z=172,47], EntityBat['Bat'/353124, l='MpServer', x=127,47, y=20,22, z=180,91], EntityEnderman['Enderman'/271206, l='MpServer', x=148,36, y=61,00, z=196,65], EntityEnderman['Enderman'/351079, l='MpServer', x=104,50, y=12,00, z=150,50], EntitySkeleton['Skeleton'/353511, l='MpServer', x=207,80, y=63,00, z=263,50], EntityZombie['Spined Zombie'/353638, l='MpServer', x=139,34, y=55,00, z=210,34], EntityZombie['Zombie'/349921, l='MpServer', x=220,50, y=36,00, z=156,50], EntityAuraNode['Aura Node'/154724, l='MpServer', x=242,50, y=89,50, z=183,50], EntityCreeper['Creeper'/352483, l='MpServer', x=187,50, y=72,00, z=183,50], EntityCreeper['Creeper'/349037, l='MpServer', x=216,50, y=28,00, z=227,50], EntitySpider['Spider'/351085, l='MpServer', x=75,50, y=17,00, z=108,50], EntitySpider['Spider'/351084, l='MpServer', x=91,50, y=18,00, z=149,50], EntityBat['Bat'/336361, l='MpServer', x=171,78, y=49,10, z=177,69], EntityAuraNode['Aura Node'/110, l='MpServer', x=118,50, y=74,50, z=158,50], EntityRabbit['Rabbit'/111, l='MpServer', x=110,72, y=73,00, z=163,84], EntityCreeper['Creeper'/323700, l='MpServer', x=166,97, y=64,00, z=192,47], EntitySkeleton['Skeleton'/353651, l='MpServer', x=104,50, y=17,00, z=163,50], EntityItem['item.item.rottenFlesh'/327667, l='MpServer', x=151,06, y=79,00, z=151,63], EntityAuraNode['Aura Node'/189813, l='MpServer', x=235,50, y=88,50, z=164,50], EntityItem['item.item.string'/346878, l='MpServer', x=129,91, y=15,00, z=207,94], EntitySpider['Spider'/347390, l='MpServer', x=124,28, y=42,09, z=150,00], EntityCreeper['Creeper'/346745, l='MpServer', x=152,50, y=17,00, z=216,50], EntityZombie['Zombie'/353017, l='MpServer', x=91,50, y=22,00, z=171,50], EntitySkeleton['Skeleton'/323451, l='MpServer', x=136,63, y=69,00, z=209,91]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 374470384 bytes (357 MB) / 1144012800 bytes (1091 MB) up to 2134114304 bytes (2035 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
    FML: MCP 9.19 Powered by Forge 11.15.1.1723 25 mods loaded, 25 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJA  FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.1.1723.jar) 
    UCHIJA  Forge{11.15.1.1723} [Minecraft Forge](forge-1.8.9-11.15.1.1723.jar) 
    UCHIJA  Baubles{1.1.3.0} [Baubles](Baubles-1.8.9-1.1.3.0.jar) 
    UCHIJA  Botania{r1.8-249} [Botania](Botania.r1.8-248-MC1.8-eb7a6ae.jar) 
    UCHIJA  BuildCraft|Core{7.2.0-pre7} [BuildCraft](buildcraft-7.2.0-pre7.jar) 
    UCHIJA  BuildCraft|Energy{7.2.0-pre7} [BC Energy](buildcraft-7.2.0-pre7.jar) 
    UCHIJA  BuildCraft|Transport{7.2.0-pre7} [BC Transport](buildcraft-7.2.0-pre7.jar) 
    UCHIJA  BuildCraft|Robotics{7.2.0-pre7} [BC Robotics](buildcraft-7.2.0-pre7.jar) 
    UCHIJA  BuildCraft|Builders{7.2.0-pre7} [BC Builders](buildcraft-7.2.0-pre7.jar) 
    UCHIJA  BuildCraft|Factory{7.2.0-pre7} [BC Factory](buildcraft-7.2.0-pre7.jar) 
    UCHIJA  BuildCraft|Silicon{7.2.0-pre7} [BC Silicon](buildcraft-7.2.0-pre7.jar) 
    UCHIJA  chiselsandbits{mc1.8.9-v1.8.6} [Chisels & Bits](chiselsandbits-mc1.8.9-v1.8.6.jar) 
    UCHIJA  fastleafdecay{1.6} [Fast Leaf Decay](FastLeafDecay-1.8-1.6.jar) 
    UCHIJA  inventorytweaks{1.60-beta-30-48a432c} [Inventory Tweaks](InventoryTweaks-1.60-beta-30.jar) 
    UCHIJA  IronChest{6.0.121.768} [Iron Chest](ironchest-1.8.9-6.0.121.768.jar) 
    UCHIJA  JEI{2.22.4.106} [Just Enough Items](jei_1.8.9-2.22.4.106.jar) 
    UCHIJA  Thaumcraft{5.1.4} [Thaumcraft](Thaumcraft-1.8.9-5.1.4.jar) 
    UCHIJA  JEIAddons{0.10.0.35} [Just Enough Items Addons](JEIAddons_1.8.9-0.10.0.35.jar) 
    UCHIJA  journeymap{5.1.3} [JourneyMap](journeymap-1.8.8-5.1.3-unlimited.jar) 
    UCHIJA  mantle{1.8.9-0.7.jenkins72} [Mantle](Mantle-1.8.9-0.7.jar) 
    UCHIJA  Morpheus{1.8.9-2.0.57} [Morpheus](Morpheus-1.8.9-2.0.57.jar) 
    UCHIJA  tconstruct{1.8.9-2.0.2.jenkins61} [Tinkers' Construct](TConstruct-1.8.9-2.0.2.jar) 
    UCHIJA  Waila{1.6.0} [Waila](Waila-1.6.0-B3_1.8.8.jar) 
    UCHIJA  WailaHarvestability{1.1.6} [Waila Harvestability](WailaHarvestability-mc1.8.x-1.1.6.jar) 
    Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.4.jar)

CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
FMLPlugin (InventoryTweaks-1.60-beta-30.jar)
  invtweaks.forge.asm.ContainerTransformer
    GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4276' Renderer: 'Intel(R) HD Graphics 4000'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not

**Comment by TheWhiteWolves** [comment]
@williewillus I guess this might be related to Issue #74

**Comment by williewillus** [comment]
yes
