### ISSUE TITLE
Request - 1.8.9 Branch

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [williewillus/Botania#83]
It finally has a true stable release!!!

**Comment by williewillus** [comment]
?

**Comment by yrsegal** [comment]
I think they want you to port to 1.8.9. Isn't your fork stable on 1.8.9 already?

**Comment by GirafiStudios** [comment]
The MC1.8 branch is on 1.8.9

**Comment by williewillus** [comment]
Judging from the ticket on Vaz's tracker, I think it's a request for me to start building for the 1.8.9 stable Forge that just came out 

Which I may consider doing soon, if there aren't any more Forge builds that add something I'd really like to use

**Comment by williewillus** [comment]
Latest build is based on recommended forge
