### ISSUE TITLE
Saplings

### ISSUE THREAD

**Issue by Majestyc2k1** [williewillus/Botania#85]
Saplings are disappearing when used in the Alchemy Catalyst.

**Comment by williewillus** [comment]
What do you mean? like they just get eaten and nothing comes back?

**Comment by GirafiStudios** [comment]
What kind of saplings? I just tested oak saplings and you get spruce saplings, no problem there :)
And what build of Botania are you using?

**Comment by yrsegal** [comment]
are there any endoflames nearby?

**Comment by Majestyc2k1** [comment]
Yes, there are endoflames nearby. I put in a birch to make a jungle, but it disappeared/got eaten. Nothing returned. I also tried oak, same thing. I tried it on both 0.5.2.2 and 0.5.3.

**Comment by yrsegal** [comment]
Yeah. Endoflames do that. This has been closed as intended on upstream many, many times.

**Comment by yrsegal** [comment]
If you want, give it a whirl with endoflames in the same places in 1.7. Same thing happens. Seperate mana production and mana usage.

**Comment by Majestyc2k1** [comment]
So nothing is going to be done to fix this?

**Comment by GirafiStudios** [comment]
It's a problem with how you have setup your stuff..

**Comment by howtonotwin** [comment]
Why do you not expect an Endoflame to burn a piece of fuel when it's in range? This is 100% intended behavior.

**Comment by Majestyc2k1** [comment]
If I throw something into the Catalyst (especially when the screen shows the transformation) and the visual and audio effect plays like any other item, I expect it to work. But anyways, I will make a different setup. Thank you for the information.
