### ISSUE TITLE
Disappearing generating flora

### ISSUE THREAD

**Issue by monkeyfuzzz** [williewillus/Botania#87]
im running FTB unstable on 1.8.9 and after crafting some dayblooms and placing then near my mana spreader , within 2-3 hours of gameplay i come back to  them and they are gone. (also no generating flora reciepes in NEI)

**Comment by williewillus** [comment]
I don't know where you've been the last couple months, Vaz made passive generating flowers decay after several irl hours of gameplay like... last October?? Idk :p

Read the "Caveats of Passive Generation" entry in the lexicon.

Can't fix, won't fix
