### ISSUE TITLE
Throwing Flare Chakram at the Ender Dragon makes the save unplayable

### ISSUE THREAD

**Issue by nicholaspels** [williewillus/Botania#88]
EDIT: I have since tried this on 3.0.16, and the issue still persists.

I was in creative mode fighting the Ender Dragon, and I decided to try a flare chakram on it. Unfortunately, it immediately crashed my game upon hitting, and whenever I tried to reload, I would get into the game for about half a second before it crashes again. I can no longer access my world because of this bug.

This was from version 3.0.15 of the FTB Unstable Pack.
Here's the crash report:

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.1.4.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  LoadingPlugin (RandomThings-MC1.8.9-3.5.8.jar)
  thaumicinfusion (ThaumicInfusion-1.8.9-4.76.jar)
  LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 1/24/16 10:22 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
    at vazkii.botania.common.entity.EntityThornChakram.func_70184_a(EntityThornChakram.java:134)
    at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(SourceFile:204)
    at vazkii.botania.common.entity.EntityThornChakram.func_70071_h_(EntityThornChakram.java:60)
    at net.minecraft.world.World.func_72866_a(World.java:1860)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:699)
    at net.minecraft.world.World.func_72870_g(World.java:1829)
    at net.minecraft.world.World.func_72939_s(World.java:1661)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:544)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Thread.java:745)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at vazkii.botania.common.entity.EntityThornChakram.func_70184_a(EntityThornChakram.java:134)
    at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(SourceFile:204)
    at vazkii.botania.common.entity.EntityThornChakram.func_70071_h_(EntityThornChakram.java:60)
    at net.minecraft.world.World.func_72866_a(World.java:1860)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:699)
    at net.minecraft.world.World.func_72870_g(World.java:1829)

-- Entity being ticked --
Details:
    Entity Type: Botania.botania:thornChakram (vazkii.botania.common.entity.EntityThornChakram)
    Entity ID: 4181
    Entity Name: Thorn Chakram
    Entity's Exact location: -29.11, 110.70, 30.68
    Entity's Block location: -30.00,110.00,30.00 - World: (-30,110,30), Chunk: (at 2,6,14 in -2,1; contains blocks -32,0,16 to -17,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Entity's Momentum: -1.22, -0.48, -0.67
    Entity's Rider: ~~ERROR~~ NullPointerException: null
    Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1661)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:544)

-- Affected level --
Details:
    Level name: Secret Hitler
    All players: 1 total; [EntityPlayerMP['Gekuu9'/4164, l='Secret Hitler', x=-11.39, y=116.37, z=40.49]]
    Chunk stats: ServerChunkCache: 961 Drop: 0
    Level seed: -1776436689544362
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 0 game time, 0 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 865651648 bytes (825 MB) / 2156920832 bytes (2057 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
    IntCache: cache: 7, tcache: 0, allocated: 15, tallocated: 95
    FML: MCP 9.19 Powered by Forge 11.15.0.1715 68 mods loaded, 68 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.18} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.0.1715.jar) 
    UCHIJAAAA   Forge{11.15.0.1715} [Minecraft Forge](forge-1.8.9-11.15.0.1715.jar) 
    UCHIJAAAA   Baubles{1.1.3.0} [Baubles](Baubles-1.8.9-1.1.3.0.jar) 
    UCHIJAAAA   aura{unspecified} [Aura Cascade](AuraCascade-1.8.8-v0.2.2a.jar) 
    UCHIJAAAA   bagginses{2.1.4} [Bagginses](Bagginses-1.8.9-2.1.4.jar) 
    UCHIJAAAA   BetterThanBunnies{1.8.9-1.0.0} [BetterThanBunnies](BetterThanBunnies-1.8.9-1.0.0.jar) 
    UCHIJAAAA   BloodMagic{1.8.9-2.0.0-6} [Blood Magic: Alchemical Wizardry](BloodMagic-1.8.9-2.0.0-6.jar) 
    UCHIJAAAA   Botania{r1.8-249} [Botania](Botania.r1.8-248-MC1.8-d0e4e43.jar) 
    UCHIJAAAA   BuildCraft|Core{7.2.0-pre6} [BuildCraft](buildcraft-7.2.0-pre6.jar) 
    UCHIJAAAA   BuildCraft|Transport{7.2.0-pre6} [BC Transport](buildcraft-7.2.0-pre6.jar) 
    UCHIJAAAA   BuildCraft|Factory{7.2.0-pre6} [BC Factory](buildcraft-7.2.0-pre6.jar) 
    UCHIJAAAA   BuildCraft|Silicon{7.2.0-pre6} [BC Silicon](buildcraft-7.2.0-pre6.jar) 
    UCHIJAAAA   BuildCraft|Robotics{7.2.0-pre6} [BC Robotics](buildcraft-7.2.0-pre6.jar) 
    UCHIJAAAA   BuildCraft|Energy{7.2.0-pre6} [BC Energy](buildcraft-7.2.0-pre6.jar) 
    UCHIJAAAA   BuildCraft|Builders{7.2.0-pre6} [BC Builders](buildcraft-7.2.0-pre6.jar) 
    UCHIJAAAA   Chameleon{1.8.9-0.2.1} [Chameleon](Chameleon-1.8.9-0.2.1.jar) 
    UCHIJAAAA   mcmultipart{1.0.5} [MCMultiPart](MCMultiPart-1.0.5-universal.jar) 
    UCHIJAAAA   CharsetLib{0.1.5} [‽](Charset-0.1.5-b37aba7a5bca21e7e21dcb88.jar) 
    UCHIJAAAA   CharsetTweaks{0.1.5} [*](Charset-0.1.5-b37aba7a5bca21e7e21dcb88.jar) 
    UCHIJAAAA   CharsetWires{0.1.5} [+](Charset-0.1.5-b37aba7a5bca21e7e21dcb88.jar) 
    UCHIJAAAA   CharsetAudio{0.1.5} [♫](Charset-0.1.5-b37aba7a5bca21e7e21dcb88.jar) 
    UCHIJAAAA   CharsetStorage{0.1.5} [#](Charset-0.1.5-b37aba7a5bca21e7e21dcb88.jar) 
    UCHIJAAAA   CharsetPipes{0.1.5} [|](Charset-0.1.5-b37aba7a5bca21e7e21dcb88.jar) 
    UCHIJAAAA   CharsetGates{0.1.5} [&](Charset-0.1.5-b37aba7a5bca21e7e21dcb88.jar) 
    UCHIJAAAA   chisel{@VERSION@} [Chisel](Chisel-MC1.8.9-0.0.2.6.jar) 
    UCHIJAAAA   chiselsandbits{mc1.8.9-v1.8.3} [Chisels & Bits](chiselsandbits-mc1.8.9-v1.8.3.jar) 
    UCHIJAAAA   compasscoords{1.8.9-0.2.6} [Compass Co-ords](CompassCoords-1.8.9-0.2.6.jar) 
    UCHIJAAAA   ComputerCraft{1.78} [ComputerCraft](ComputerCraft1.78.jar) 
    UCHIJAAAA   crafttweaker{3.0.0} [crafttweaker](CraftTweaker-Customized-1.8.8-3.0.1.jar) 
    UCHIJAAAA   CustomMainMenu{1.9.3} [Custom Main Menu](CustomMainMenu-MC1.8.8-1.9.3.jar) 
    UCHIJAAAA   ShetiPhianCore{3.0.3} [ShetiPhian-Core](ShetiPhianCore-1.8.9-3.0.3.jar) 
    UCHIJAAAA   EnderTanks{1.2.0} [EnderTanks](EnderTanks-1.8.9-1.2.0.jar) 
    UCHIJAAAA   ezstorage{1.0} [EZ Storage](ezstorage-1.8.9-1.2.2.jar) 
    UCHIJAAAA   fastleafdecay{1.6} [Fast Leaf Decay](FastLeafDecay-1.8-1.6.jar) 
    UCHIJAAAA   flatcoloredblocks{mc1.8.9-v1.3} [Flat Colored Blocks](flatcoloredblocks-mc1.8.9-v1.5.jar) 
    UCHIJAAAA   Waila{1.6.0} [Waila](Waila-1.6.0-B3_1.8.8.jar) 
    UCHIJAAAA   FTBL{2.0.2} [FTBLib](FTBLib-1.8.9-2.0.2.jar) 
    UCHIJAAAA   FTBU{2.0.2} [FTBUtilities](FTBUtilities-1.8.9-2.0.2.jar) 
    UCHIJAAAA   furnus{1.5} [Furnus](Furnus-1.8.9-1.5.jar) 
    UCHIJAAAA   graves{1.8.9-b23-universal} [Graves Mod](graves-1.8.9-b23-universal.jar) 
    UCHIJAAAA   hopperducts{1.4.6} [Hopper Ducts](hopperducts-mc1.8.8-1.4.6.jar) 
    UCHIJAAAA   k4lib{1.8.9-1.0.7} [K4Lib](k4lib-1.8.9-1.0.7-universal.jar) 
    UCHIJAAAA   HydCraft{1.8.9-3.1.20} [Hydraulicraft](HydCraft-1.8.9-3.1.20-universal.jar) 
    UCHIJAAAA   IGWMod{1.2.3-3} [In-Game wiki Mod](IGW-Mod-1.8.9-1.2.3-3-universal.jar) 
    UCHIJAAAA   inventorysorter{0.7.4+26} [Simple Inventory sorting](inventorysorter-1.8.9-0.7.4+26.jar) 
    UCHIJAAAA   IronChest{6.0.121.768} [Iron Chest](ironchest-1.8.9-6.0.121.768.jar) 
    UCHIJAAAA   JEI{2.21.0.98} [Just Enough Items](jei_1.8.9-2.21.0.98.jar) 
    UCHIJAAAA   Thaumcraft{5.1.4} [Thaumcraft](Thaumcraft-1.8.9-5.1.4.jar) 
    UCHIJAAAA   JEIAddons{0.9.0.32} [Just Enough Items Addons](JEIAddons_1.8.9-0.9.0.32.jar) 
    UCHIJAAAA   journeymap{5.1.3} [JourneyMap](journeymap-1.8.8-5.1.3-unlimited.jar) 
    UCHIJAAAA   jeresources{0.2.1.@BUILD@} [Just Enough Resources](JustEnoughResources-1.8.9-0.2.1.jar) 
    UCHIJAAAA   llor{1.0.4-mc1.8.8} [Light Level Overlay Reloaded](LLOverlayReloaded-1.0.4-mc1.8.8.jar) 
    UCHIJAAAA   mantle{1.8.9-0.7.jenkins72} [Mantle](Mantle-1.8.9-0.7.jar) 
    UCHIJAAAA   testdummy{1.0} [MmmMmmMmmMmm](MmmMmmMmmMmm-1.9b.jar) 
    UCHIJAAAA   Morpheus{1.8.9-2.0.57} [Morpheus](Morpheus-1.8.9-2.0.57.jar) 
    UCHIJAAAA   fodc{1.7.1} [Ore Dictionary Converter](OreDictionaryConverter-1.7.1.jar) 
    UCHIJAAAA   playerrugs{0.0.1} [Player Rugs](PlayerRugs-1.8.8-1.2.0.jar) 
    UCHIJAAAA   PneumaticCraft{1.13.2-3} [PneumaticCraft](PneumaticCraft-1.8.9-1.13.2-3-universal.jar) 
    UCHIJAAAA   progressiveautomation{1.6.16} [Progressive Automation](ProgressiveAutomation-1.8.9-1.6.16.jar) 
    UCHIJAAAA   RandomThings{3.5.8} [Random Things](RandomThings-MC1.8.9-3.5.8.jar) 
    UCHIJAAAA   ResourceLoader{1.4} [Resource Loader](ResourceLoader-MC1.8.8-1.4.jar) 
    UCHIJAAAA   rftools{4.20beta12} [RFTools](rftools-1.8.9-4.20beta12.jar) 
    UCHIJAAAA   simpleretrogen{2.2.2+3} [Simple Retrogen](simpleretrogen-1.8.9-2.2.2+3.jar) 
    UCHIJAAAA   StorageDrawers{1.8.9-2.2.1} [Storage Drawers](StorageDrawers-1.8.9-2.2.1.jar) 
    UCHIJAAAA   tconstruct{1.8.9-2.0.2.jenkins61} [Tinkers' Construct](TConstruct-1.8.9-2.0.2.jar) 
    UCHIJAAAA   thaumicinfusion{4.76} [Thaumic Infusion](ThaumicInfusion-1.8.9-4.76.jar) 
    UCHIJAAAA   wawla{1.4.7} [What Are We Looking At](Wawla-1.4.7-1.8+.jar) 
    Loaded coremods (and transformers): 
NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  net.fybertech.nwr.NowWithRendering
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.4.jar)

FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
LoadingPlugin (RandomThings-MC1.8.9-3.5.8.jar)
  lumien.randomthings.asm.ClassTransformer
thaumicinfusion (ThaumicInfusion-1.8.9-4.76.jar)
  drunkmafia.thaumicinfusion.common.asm.BlockTransformer
  drunkmafia.thaumicinfusion.common.asm.WorldTransformer
LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
  lumien.resourceloader.asm.ClassTransformer
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - chiselsandbitsIntegration (Enabled/Not Forced)
        - TinkerDebug (Enabled/Not Forced)

```
Profiler Position: N/A (disabled)
Player Count: 1 / 8; [EntityPlayerMP['Gekuu9'/4164, l='Secret Hitler', x=-11.39, y=116.37, z=40.49]]
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'fml,forge'`
```

**Comment by williewillus** [comment]
I can't reproduce, summoned a NoAI dragon and spammed chakrams at it, nothing happened.

Can you do it with just botania?

**Comment by nicholaspels** [comment]
Well this is odd... I can no longer reproduce it. The world I had in it originally is now accessible, which is very odd since I've tested it previously in 1.0.16, and it still crashed. Not really sure what has fixed it, but I guess it's solved?
