### ISSUE TITLE
Terrafirma Rod crash

### ISSUE THREAD

**Issue by Tim2162286** [williewillus/Botania#90]
i attempted to use the terrafirma rod in creative, and got a crash. after restarting the world, i gave myself a stack of dirt and a rod of the lands, and got the exact same crash. Unfortunately i was stupid ad deleted my crash logs, but when i will try and remember to replicated the crash and post the log later.

**Comment by williewillus** [comment]
yes, logs would be great, along with what build you're using

**Comment by Tim2162286** [comment]
Here is the crash log, I am currently using the FTB Unstable 1.8 pack as a base, but have added a few extra mods.
[crash-2016-01-31_02.30.23-client.txt](https://github.com/williewillus/Botania/files/111190/crash-2016-01-31_02.30.23-client.txt)

Looking at the crash log, i believe the crash is happening in this method, but i haven't read through enough of the code to have an idea why the stack variable is null. (possibly stack never gets initialized?)

```
public void onUsingTick(ItemStack stack, EntityPlayer player, int count) {
        if(count != getMaxItemUseDuration(stack) && count % 10 == 0)
            terraform(stack, player.worldObj, player);
```

As a side note, I also noticed that the Terra pick now has an even diameter rather than an odd diameter like it used to. not sure if this was intended or not.
