### ISSUE TITLE
Can't get GOG pebbles.

### ISSUE THREAD

**Issue by chrissquest** [williewillus/Botania#92]
So, this is just probably a dumb mistake, but when I right click on grass/ dirt with an empty hand, nothing happens. Same for shifting. I have latest botania and garden of glass, and just updated forge. This is a modpack, list of mods here: http://pastebin.com/fPLgvEKx

Thanks for reading.
EDIT: Nothing in gog seems to be working, is there something else I need to do?

**Comment by williewillus** [comment]
I can do all GoG things fine - just started my own play through

is the world type the GoG worldtype? Those events won't trigger if it isn't, even if the GoG jar is present

**Comment by chrissquest** [comment]
Yeah, didn't know you had to do that, it works now thank you!
