### ISSUE TITLE
Multiple Cosmetic Baubles not rendering correctly

### ISSUE THREAD

**Issue by TheWhiteWolves** [williewillus/Botania#99]
The Kamui Eye bauble is incorrectly rendering itself.

Below is how it is rendering in 1.8

![2016-02-06_19 22 21](https://cloud.githubusercontent.com/assets/1471503/12868834/3f4abcda-cd07-11e5-82e0-1687615d2893.png)
![2016-02-06_19 22 24](https://cloud.githubusercontent.com/assets/1471503/12868833/3f4a9d7c-cd07-11e5-95c9-35bd6f2d2c94.png)
![2016-02-06_19 22 55](https://cloud.githubusercontent.com/assets/1471503/12868835/3f4e3928-cd07-11e5-9b8e-b70f03f5ce72.png)
![2016-02-06_19 22 16](https://cloud.githubusercontent.com/assets/1471503/12868836/3f4ef430-cd07-11e5-9979-d33ac507c371.png)

This is the 1.7 render.

![2016-02-06_19 27 20](https://cloud.githubusercontent.com/assets/1471503/12868851/c936cf2e-cd07-11e5-9c42-ec906baecfa9.png)

---

Instance:
minecraft-1.8.9
forge-11.15.1.1732

Mods:
Baubles-1.8.9-1.1.3.0
Botania.r1.8-248-MC1.8-779cc76
jei_1.8.9-2.25.6.140

**Comment by TheWhiteWolves** [comment]
Going to turn this into a multiple piece issue and group several renders together.

**Comment by TheWhiteWolves** [comment]
Wiked Eyepatch: [Minor]

1.8

![2016-02-06_19 40 34](https://cloud.githubusercontent.com/assets/1471503/12868913/9055e148-cd09-11e5-956c-cdba25651310.png)

1.7

![2016-02-06_19 41 15](https://cloud.githubusercontent.com/assets/1471503/12868918/9b05a722-cd09-11e5-9939-4e2881d94372.png)

**Comment by TheWhiteWolves** [comment]
Clock Eye:

1.8

![2016-02-06_19 42 23](https://cloud.githubusercontent.com/assets/1471503/12868928/cf6dad8e-cd09-11e5-85bb-aa333188ceac.png)

1.7

![2016-02-06_19 43 03](https://cloud.githubusercontent.com/assets/1471503/12868929/db0b83c8-cd09-11e5-8650-f16988cc0404.png)

**Comment by TheWhiteWolves** [comment]
Unicorn Horn:

1.8

![2016-02-06_19 43 38](https://cloud.githubusercontent.com/assets/1471503/12868934/fdabe60c-cd09-11e5-9b1b-b58cb89eb0ba.png)

1.7

![2016-02-06_19 44 28](https://cloud.githubusercontent.com/assets/1471503/12868943/10392848-cd0a-11e5-86c8-f7c3c4ef5ca9.png)

**Comment by TheWhiteWolves** [comment]
Devil Horns: (hard to see but they are in your neck)

1.8

![2016-02-06_19 45 11](https://cloud.githubusercontent.com/assets/1471503/12868957/3936ffea-cd0a-11e5-8524-5acd8731f4aa.png)

1.7

![2016-02-06_19 46 00](https://cloud.githubusercontent.com/assets/1471503/12868961/48eec38c-cd0a-11e5-93bf-61720065b521.png)

**Comment by TheWhiteWolves** [comment]
Alien Antenna:

1.8

![2016-02-06_19 47 51](https://cloud.githubusercontent.com/assets/1471503/12868972/a61a2786-cd0a-11e5-8b7f-0d5d3f0a8c98.png)

1.7

![2016-02-06_19 48 20](https://cloud.githubusercontent.com/assets/1471503/12868973/aa47c19c-cd0a-11e5-8493-aa744492c8ab.png)

**Comment by TheWhiteWolves** [comment]
Hyper Plus:

1.8

![2016-02-06_19 49 34](https://cloud.githubusercontent.com/assets/1471503/12868976/d59ad9ce-cd0a-11e5-8f04-2226ee692a68.png)

1.7

![2016-02-06_19 50 04](https://cloud.githubusercontent.com/assets/1471503/12868978/da8d96a6-cd0a-11e5-9e62-0bcacd6ab60c.png)

**Comment by TheWhiteWolves** [comment]
Thick Eyebrows:

1.8

![2016-02-06_19 50 51](https://cloud.githubusercontent.com/assets/1471503/12868989/07c3dffe-cd0b-11e5-9bed-aa83d1ff8e10.png)

1.7

![2016-02-06_19 51 07](https://cloud.githubusercontent.com/assets/1471503/12868990/0de936cc-cd0b-11e5-9ae0-0136262c2c4a.png)

**Comment by TheWhiteWolves** [comment]
Lusitanic Shield: (hard to see the 1.7 one as I can't turn off my cape in 1.7, but the issue is the scale)

1.8

![2016-02-06_19 52 05](https://cloud.githubusercontent.com/assets/1471503/12869000/6f8f9f56-cd0b-11e5-822b-6ce098c87daa.png)

1.7

![2016-02-06_19 53 14](https://cloud.githubusercontent.com/assets/1471503/12869003/755bbdd4-cd0b-11e5-9cbe-e99e4da52d6f.png)
![2016-02-06_19 53 40](https://cloud.githubusercontent.com/assets/1471503/12869004/756fbe24-cd0b-11e5-9317-0323884eddb6.png)

**Comment by yrsegal** [comment]
D: now I know you were at minecon but I didn't get to meet you

**Comment by TheWhiteWolves** [comment]
:P maybe next time its over this side of the world

**Comment by williewillus** [comment]
~~What version is this in?
Many of these were fixed~~

Just kidding, there hasn't been a build since I fixed them

**Comment by TheWhiteWolves** [comment]
ahh makes sense then, if you have already done em all then I'll close this if you want

**Comment by williewillus** [comment]
Yeah they should all show up properly in next release
They still look weird when crouching, but that's for another issue ticket
